### ISSUE TITLE
No 'Edit node' action icon on Microsoft Edge

### ISSUE THREAD

**Issue by twkrol** [n8n-io/n8n#1438] opened 2021-02-13 15:04 UTC
**Describe the bug**
On Microsoft Edge there is no 'Edit node' button above the node icon. On Firefox there are 5 action icons for node: remove, activate/deactivate, duplicate, edit and execute but on Edge the 'Edit node' action icon is missing.
Not many users will notice this, but when you use touch screen there is no double click event on the node icon, so you're unable to edit node properties without mouse or trackpad.

**To Reproduce**
1. Go to n8n editor on Microsoft Edge
2. Click on a node
3. Notice there are 4 action icons shown above, but no Edit node
4. Compare with Firefox

**Expected behavior**
There should be 5 action icons above node icon when clicked, regardless of browser used.

**Environment (please complete the following information):**
 - OS: Windows 10 20H2
 - n8n Version 0.107.0
 - Node.js Version [docker]

**Additional context**
It would be good to handle double tap event on a node as well, not only double click as the surface pro doesn't trigger double click with the pen.

**Comment by lublak** [comment] 2021-02-25 06:40
@twkrol hey, i test it myself.
Both browsers show no edit button.

Firefox:
![grafik](https://user-images.githubusercontent.com/44057030/109112424-eba1f380-773a-11eb-8d71-e950d85838cb.png)

Edge:
![grafik](https://user-images.githubusercontent.com/44057030/109112457-fbb9d300-773a-11eb-9bbc-1bb8dace6992.png)

The edit button should only be shown when the unit has touch.

Touch:
![grafik](https://user-images.githubusercontent.com/44057030/109113543-b5fe0a00-773c-11eb-9233-637ce7601bea.png)

I test it with the Edge Version: 88.0.705.74

Which edge and firefox version do you have?
Can you look in about:config in firefox for "Multiprocess Windows"?

**Comment by twkrol** [comment] 2021-02-25 11:08
Hi @lublak - thank you for your response.

In meantime I've upgraded n8n and the browsers to:
- n8n v0.109.0
- Firefox v86.0
- Edge v88.0.705.74 (same as yours)

On the Firefox it works as expected (the edit button is visible) but on the Edge it is not :(
There is no "Multiprocess Windows" in about:config in my Firefox.

I'm testing on Microsoft Surface Pro 7 with touch screen and pen.

**Comment by lublak** [comment] 2021-02-26 19:29
@twkrol i try it in the next few days.
I think here is the function which tests the touch functionality:
https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/mixins/deviceSupportHelpers.ts#L6

**Comment by mutdmour** [comment] 2021-08-03 12:16
thanks @twkrol for the report. We are adding for double tap to open a node so that should allow you to open nodes without the `edit` action.

**Comment by Joffcom** [comment] 2022-01-07 11:01
Hey @twkrol,

Are you still seeing this issue?

**Comment by Joffcom** [comment] 2023-01-17 10:12
Hey @twkrol,

I am closing this one for now and if the issue is still occurring let me know and we can open it again.

**Closed by Joffcom** 2023-01-17 10:12 UTC
Labels: ui
