### ISSUE TITLE
Workflow tags missing after successful import using n8n client

### ISSUE THREAD

**Issue by Stams89** [n8n-io/n8n#7649] opened 2023-11-08 10:49 UTC
When trying to import a workflow with the n8n client, the workflow is imported successfully but the workflow tags are missing. 

**To Reproduce**

1. Download a simple workflow containing tags
Example workflow
```json
{
  "name": "My workflow",
  "nodes": [
    {
      "parameters": {},
      "id": "34c6d4a9-0eab-4f31-b752-0b198efd2df7",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        620,
        260
      ]
    },
    {
      "parameters": {
        "jsCode": "// Loop over input items and add a new field called 'myNewField' to the JSON of each one\nfor (const item of $input.all()) {\n  item.json.myNewField = 1;\n}\n\nreturn $input.all();"
      },
      "id": "e0bbbdb1-8627-423e-aa85-1606c25fb5b3",
      "name": "Code",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        840,
        260
      ]
    }
  ],
  "pinData": {},
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Code",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "executionOrder": "v1"
  },
  "versionId": "91d73652-f0e6-4f58-8da6-120751df7dff",
  "id": "ZyZxYSDelF7QJHZE",
  "meta": {
    "instanceId": "fceda3c62573df7b4287c415423be281adf1e6f22810070e8d10bcca736e432d"
  },
  "tags": [
    {
      "createdAt": "2023-11-02T16:11:14.402Z",
      "updatedAt": "2023-11-02T16:11:14.402Z",
      "id": "NHqWyrslIcO7IssA",
      "name": "test"
    },
    {
      "name": "new",
      "id": "y8SnB0mgxV4nrwUf",
      "createdAt": "2023-11-08T08:26:07.295Z",
      "updatedAt": "2023-11-08T08:26:07.295Z"
    }
  ]
}
```

2. Open a terminal and execute 'n8n import:workflow --input=/path/to/the/workflow.json' 

**Expected behavior**
The workflow gets imported with the tags

**Environment (please complete the following information):**

- OS: Ubuntu 20.04.4 LTS
- n8n Version 1.8.2
- Node.js Version 20.5.0
- Database system: SQLite 
- Operation mode: own

**Additional context**
- The workflow tags get created in case they don't exist
- The same steps work as expected on n8n Version 0.203.1.

**Comment by Joffcom** [comment] 2023-11-08 11:09
Hey @Stams89,

Thanks for flagging this! I have taken a look and this issue's a duplicate of what we've got on Issue #5477. For now I am going to mark this one as closed and we will treat the other issue as the main one for this.

**Closed by Joffcom** 2023-11-08 11:09 UTC
