### ISSUE TITLE
Webhook Error with 0.221.0

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#5765] opened 2023-03-23 18:21 UTC
**Describe the bug**

All requests arriving at the Webhook node are generating an error, but no log, no data. Simply the workflow is marked with error without any information.

![n8n-io-Workflow-Automation](https://user-images.githubusercontent.com/257004/227310563-38cc0656-3aee-442d-8c78-9c973571cdd6.png)

**To Reproduce**

1. Check Running Workflows

**Expected behavior**

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 0.221.0
- Node.js Version [e.g. 16.17.0]
- Database system postgres
- Operation mode queue

**Additional context**

**Comment by luizeof** [comment] 2023-03-23 18:22
A member sent me a log that he found.

![IMAGE 2023-03-23 15:21:35](https://user-images.githubusercontent.com/257004/227311031-c3172d2f-2e91-49b8-88d4-7f5dcc2585b2.jpg)

**Comment by tiagocordeiro** [comment] 2023-03-23 18:31
Same here

![Captura de Tela 2023-03-23 às 14 57 38](https://user-images.githubusercontent.com/6535995/227313312-0c4ab484-5216-43b5-96d1-ede072ea4be9.png)

**Comment by Joffcom** [comment] 2023-03-23 18:54
Thanks for the report @luizeof and  @tiagocordeiro we will get this sorted.

Unrelated to this are you both running something like watchtower or was the upgrade done manually?

**Comment by eliasff** [comment] 2023-03-23 19:06
Here the same, almost every execution is marked as "Failed". I have to open one by one to see if it's true or not

**Comment by devanshkaloti** [comment] 2023-03-23 19:14
Hi All,

Not sure if this is related but we're also getting "Problem running workflow -- require(...).Webhook is not a constructor" for all webhook connectors. 0.220.0. If it is unrelated, we will create a new issue.

**Comment by netroy** [comment] 2023-03-23 19:16
@devanshkaloti that sounds like a different problem. Can you please open a new issue, and add more details, including a stacktrace (if possible). 🙏🏽

**Comment by netroy** [comment] 2023-03-23 19:35
@luizeof @tiagocordeiro Thanks for reporting this.
Can one of you please try this docker image? `n8nio/n8n:0.221.1-rc`

If this image fixes the issue, we'll create a new release `0.221.1`.

**Comment by MeesJ** [comment] 2023-03-23 20:41
I can reproduce this issue on my end as well. `n8nio/n8n:0.221.1-rc` does not solve the issue on my end.

**Comment by netroy** [comment] 2023-03-23 21:05
@MeesJ did you update the main server, the worker, **and the webhook server**?

**Comment by MeesJ** [comment] 2023-03-23 21:08
> @MeesJ did you update the main server, the worker, **and the webhook server**?

I don't know what you mean exactly. I'm running n8n in a single instance, which is now running on the `n8nio/n8n:0.221.1-rc` image.

**Comment by netroy** [comment] 2023-03-23 21:19
@MeesJ in that case the issue you are facing is something else. This issue only exists in the separate webhook server running in the queue mode. 

Can you please open a new issue with stacktrace of the error you are seeing?

**Comment by goulahyane** [comment] 2023-03-24 03:59
Experiencing the same with the latest image `docker.n8n.io/n8nio/n8n`. 
Trying `n8nio/n8n:0.221.1-rc` and updating this thread accordingly. 

![image](https://user-images.githubusercontent.com/22414158/227420853-eb883d6a-88a3-464d-bd7c-4a1664e25c9c.png)

**Comment by goulahyane** [comment] 2023-03-24 04:12
**Update**: i've tried `0.221.1-rc` tag and it seems like the image is struggling to start. 

![image](https://user-images.githubusercontent.com/22414158/227422415-aacc4f67-b5f6-43ab-bd8b-237b7bb21772.png)

**Comment by netroy** [comment] 2023-03-24 07:53
@goulahyane Can you please try to upgrade to `0.221.1`?

**Comment by luizeof** [comment] 2023-03-24 09:42
@netroy it works!

![success](https://user-images.githubusercontent.com/257004/227483902-178f3d8b-40b1-404c-8243-25c6bcf931ad.png)

**Closed** 2023-03-24 09:47 UTC

**Comment by goulahyane** [comment] 2023-03-24 15:15
Hey @netroy, just tested the latest pushed image, seems to be solving the issue. 
Thanks for your reactivity guys!

**Comment by janober** [comment] 2023-03-30 15:47
Fix got released with [`n8n@0.222.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.222.0)
