### ISSUE TITLE
Broken workflow cannot be deactivated after manual run

### ISSUE THREAD

**Issue by terenaa** [n8n-io/n8n#2415] opened 2021-11-05 18:40 UTC
**Describe the bug**
When trying to **deactivate** a broken workflow after manual run an error message is shown - "Problem activating workflow".

**To Reproduce**
1. Run manually any active workflow with broken node
2. Try to deactivate that workflow from board or workflow list
3. See error

**Expected behavior**
Workflow can be deactivated even if it's broken.

**Environment:**
 - OS: Debian 10.10 + Docker with Portainer
 - n8n Version: 0.147.1
 - Node.js Version: 12.16.2
 - Database system: MySQL 5.7
 - Operation mode: probably default?

**Comment by Joffcom** [comment] 2023-01-17 12:43
Hey @terenaa,

Are you still seeing this issue on the latest release?

**Comment by terenaa** [comment] 2023-01-17 16:56
Hey @Joffcom,

Yup, problem still exists using 0.211.2. When I run manually an active workflow (the switch is green) and workflow fails then it cannot be **deactivated**. Instead there is an error:

```
Problem activating workflow
Please resolve outstanding issues before you activate it
```

...but I try to **deactivate** broken workflow.

**Comment by Joffcom** [comment] 2023-01-18 11:15
Hey @terenaa,

Good news, I have just worked out what you meant by a broken node and have managed to reproduce it by using an expression with an odd value where it shouldn't be. I have created an internal ticket which we will be tracking as `N8N-5971` for this one.

Out of interest how did you find the issue, Was there an issue with the trigger node you were using?

**Comment by terenaa** [comment] 2023-01-19 15:20
Hey @Joffcom,

Good to hear that! 🎉 

I'm sorry for no description what "broken node/workflow" means.

I cannot remember how I found the issue. Probably I was trying to change something with no success and thought "fine, I'll deactivate this for now", and boom - error.

**Comment by Joffcom** [comment] 2023-01-19 18:12
Hey @terenaa,

Fair enough,I guess the good news is we should have this fixed soon 😃

**Comment by Joffcom** [comment] 2024-01-04 09:15
Hey @terenaa,

I have just given this a go in `1.23.0` and it looks like it is resolved now. My steps for testing were to add a webhook node, Activate the workflow then change it to use an invalid option for the authentication, give it a manual run then try to deactivate.

As this is no longer reproducible I think we can safely close this one, If you do ever happen to run into this again let m eknow and we can open it again.

**Closed by Joffcom** 2024-01-04 09:15 UTC
Labels: in linear
