### ISSUE TITLE
Notion trigger doesn't work

### ISSUE THREAD

**Issue by seba5496** [n8n-io/n8n#1995] opened 2021-07-16 05:59 UTC
**Describe the bug**
When trying to use the Notion Trigger, adding the database ID, a message is shown, saying "Cannot read property of 'plain_text' of undefined

**To Reproduce**
1. New Notion Trigger
2. Set Credentials (Which works on other Notion nodes)
3. Set any pooling time
4. Select Page added to database as the event
5. The database field surrounded by red, and shows an alert symbol
6. Hover over the symbol and the message shows as follows

**Expected behavior**
Run without issues, listening for events.

**Environment (please complete the following information):**
Running on docker 3.5.1 for Windows 10, with:
Docker Engine. 20.10.7
Docker Compose 1.29.2
NODE_VERSION: 14.15.5
YARN_VERSION: 1.22.5
n8n Version: 0.129.0
![image](https://user-images.githubusercontent.com/47981550/125899510-cc48e1be-d10f-4265-9a3c-5f05f1f88028.png)
![image](https://user-images.githubusercontent.com/47981550/125899524-5e0f9d7f-6026-4908-99e5-b70dc7c90bd9.png)

**Comment by edlinklater** [comment] 2021-07-16 10:06
Hi @seba5496, I'm unable to reproduce this when selecting database name from the dropdown. Where has the UUID string in the database field come from in your screenshot?

**Comment by seba5496** [comment] 2021-07-17 00:25
Yes sorry, it seems like a weird random bug, now it works fine, it might have been bad credentials 'cause I pulled again the Docker container.
Thanks anyways 😬

**Comment by janober** [comment] 2021-07-17 18:49
Thanks a lot @edlinklater and @seba5496 ! I close this issue for now. If you run into problems again simply comment here again.

**Closed by janober** 2021-07-17 18:49 UTC
