### ISSUE TITLE
Node SET Does not turn string into number

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#5105] opened 2023-01-08 21:56 UTC
**Describe the bug**

Node SET Does not turn string into number. 

Only works with explict conversion

```
{{ Number($json["id"]) }}
```

![string-yo-number](https://user-images.githubusercontent.com/257004/211221028-2f32c3d9-31a1-46f7-a2dc-bfeb1e25e0df.png)

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment] 2023-01-09 11:21
Hey @luizeof,

Thanks for the report I have created an internal ticket which we will be tracking as `node-161`

**Comment by Joffcom** [comment] 2023-06-14 15:20
Closing this one as the issue is solved.

**Closed by Joffcom** 2023-06-14 15:20 UTC
Labels: node/issue, in linear
