### ISSUE TITLE
Trigger workflows with sub workflows in batch mode run Indefinitely 

### ISSUE THREAD

**Issue by jwaldrip** [n8n-io/n8n#1607] opened 2021-03-30 15:17 UTC
**Describe the bug**
I have several workflows that re-invoke themselves recursively until the last page of results is processed. These workflows run indefinitely (even when a timeout is specified). This started happening in batch mode and doesn't happen when we run the workflow manually.

**To Reproduce**
1. Ensure N8N is in queue/redis mode.
2. Create a workflow that calls itself recursively until there are no items left to be processed
3. Add A interval trigger.
4. (optionally add a timeout) 
5. Wait
6. See hundreds of ghost processes stacking up. 😢 

**Expected behavior**
I expect the processes to finish, OR at the very least, for the timeout to work.

**Environment (please complete the following information):**
 - n8n Version [e.g. 0.103.0] - Official Container in Kubernetes

**Additional Context**
Restarting the Pod in K8S drops all the running processes and clears the queue.

**Comment by krynble** [comment] 2021-03-30 15:31
Hello @jwaldrip 

Thank you for your report.

I will be looking into the mentioned issue and will keep you posted.

**Comment by krynble** [comment] 2021-04-06 09:23
Hello @jwaldrip 

Sorry for the time it took to come back to this issue.

I made a few tests now and I had interesting findings.

I am using the latest version (latest build from main / master branch).

Please note that the workflow I am using is the following: [recursion-test.txt](https://github.com/n8n-io/n8n/files/6263209/recursion-test.txt)

1. As long as my recursion is correct (recursion base + step), n8n seems to be working.
2. I see ghost processes spawning during the execution. This is a known behavior as now n8n runs things distributed in queue mode and we cannot safely tell if a process is still running or crashed. I waited for a while and it all came back to normal (executions displayed as `Success` instead of `Unknown`)
3. I am having a few issues stopping executions. I will be investigating this
4. Also timeouts do not seem to be applied properly.

With the attached workflow it is easy to reproduce the issue. Simply change the `If` node to compare the input with `1000` instead of `0`. This is an invalid recursion base and therefore would cause an infinite loop, causing n8n to generate bazilions of processes and unable to stop them as they keep spawning.

Will keep investigating and updating this issue.

**Comment by krynble** [comment] 2021-04-07 14:47
Hello again @jwaldrip 

I just opened a pull request to fix the issue with the timout not being followed correctly. It is under review and should be released after some more testing and review.

In the meantime, I would like to ask you to use the workflow I provided in the previous comment to check if it runs fine in your instance.

It seems to be that the recursion is working fine but with the considerations I wrote such as that the executions will display as `Unknown` until the whole execution finishes.

If you are still encountering the same issue, I would gently ask you for a reproducible problem with an example workflow so I can test it.

**Comment by krynble** [comment] 2021-04-19 07:41
Hello @jwaldrip 

Just updating that version 0.116.0 released over the weekend brings some fixes to the issue you mentioned.

Note: you must set the timeout in the workflow that starts first. Timeouts set in subworkflows are not taken into consideration.

I will be closing this issue and would ask you to reopen it if your problem is not solved.

Thanks!

**Closed by krynble** 2021-04-19 07:41 UTC
