### ISSUE TITLE
ERROR 400 with woocommerce node

### ISSUE THREAD

**Issue by mperochon** [n8n-io/n8n#4861] opened 2022-12-08 13:37 UTC
**Describe the bug**

I’m trying to use the woocommerce node to get products information from my customer, but for each action (get product or order), I get a 400 error.

```
NodeApiError: Bad request - please check your parameters
    at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1015:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.woocommerceApiRequestAllItems (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/WooCommerce/GenericFunctions.js:29:24)
    at async Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/WooCommerce/WooCommerce.node.js:260:40)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:28)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:585:53
```

**To Reproduce**

1. Create a woocommerce credentials with API KEY
2. Create a woocommerce node
3. Use the config to get all products
![image](https://user-images.githubusercontent.com/14574344/206459621-3a3a50d0-679d-4ef1-87e4-747226329804.png)
4. Execute the node.
5. See error

**Expected behavior**
Get all products from woocommerce API.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.206.1
- Environment : Docker
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode: own

**Additional context**
I tried to use another node like Github and the node works successfully and I also tried the HTTP Request node and I got the products with success.

**Comment by Joffcom** [comment] 2022-12-16 06:50
Hey @mperochon

There was a similar issue raised on our support forum [here](https://community.n8n.io/t/woocommerce-node-get-error-400-everytime/20603/6) but I was not able to reproduce the issue.

Are you linked with that user at all or is this a different case of the same issue?

**Comment by Joffcom** [comment] 2023-06-14 14:53
Closing for now as not able to reproduce it, If you are still seeing this issue let me know and we can open it again.

**Closed by Joffcom** 2023-06-14 14:53 UTC
