### ISSUE TITLE
The icons have moved a bit

### ISSUE THREAD

**Issue by hawkkiller** [n8n-io/n8n#4653] opened 2022-11-18 16:27 UTC
Icons' paddings are strange on a self-hosted n8n variant`'
<img width="1714" alt="Снимок экрана 2022-11-18 в 17 21 21" src="https://user-images.githubusercontent.com/62852417/202753242-69854440-5716-46ef-bc1a-380190c14342.png">

**To Reproduce**

1. Setup self-hosted n8n using docker
2. Go to a workflow page
3. See the icons.

**Environment**
linux\ubuntu-latest

**Expected behavior**
Icons are not moved.

**Comment by Joffcom** [comment] 2022-11-18 16:32
Hey @hawkkiller,

I have just checked on my local `0.203.1` instance and I am not seeing the same thing, Can you confirm the version of n8n you are running and what browser you are using?

**Comment by hawkkiller** [comment] 2022-11-18 16:35
@Joffcom 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/62852417/202754999-70535a91-ae7a-4f25-b47e-ec100621faed.png">
Yes, Im using this version too. Browser - Google Chrome. Just checked  - Works well in safari

**Comment by Joffcom** [comment] 2022-12-01 10:39
Hey @hawkkiller,

Are you seeing this on 0.204.0 as well?

**Comment by hawkkiller** [comment] 2022-12-02 19:52
@Joffcom hi.
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/62852417/205374906-27111f58-1882-4313-83b8-f1170819cad5.png">

**Comment by Joffcom** [comment] 2023-01-23 11:50
Hey @hawkkiller,

Does it happen in Chrome if you use private browsing? I am still not able to reproduce this and I am not sure why. I just noticed you mentioned a self hosted n8n variant, Is it a custom image or just our normal image?

**Comment by hawkkiller** [comment] 2023-01-23 13:05
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/62852417/214046009-af8ac1bd-ffb1-43f4-9e32-7715111f9ff3.png">
Hi @Joffcom. Yes, it is still reproducible. I have not changed anything, just n8n official docker image.

**Comment by Joffcom** [comment] 2023-06-14 14:34
Hey @hawkkiller,

I am going to mark this as closed as I am not able to reproduce it and I am out of devices and browsers to test on, If you fancy digging a bit more the questions above would be useful and we can reopen this whenever you are ready.

**Closed by Joffcom** 2023-06-14 14:34 UTC
