### ISSUE TITLE
n8n v1.8.2 - npm upstream dependency conflict

### ISSUE THREAD

**Issue by pablorq** [n8n-io/n8n#7380] opened 2023-10-09 08:46 UTC
**Describe the bug**
It seems to be an upstream dependency on n8n core modules.

**To Reproduce**

1. Setup n8n docker container
2. Start container
3. Run `npm install --prefix=/usr/local/lib/node_modules/n8n/` command
4. Receive an ERROR for upstream dependency conflict 

**Expected behavior**
No errors on n8n core packages.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 23.04
- n8n Version: 1.8.2
- Node.js Version: 18.17.1
- Database system: postgres:11
- Operation mode: ? [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
Docker compose file (portainer version):

```
# Based on https://raw.githubusercontent.com/n8n-io/n8n/master/docker/compose/withPostgres/docker-compose.yml

version: '3.8'

volumes:
  db_data:

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${N8N_LOCAL_FILES}/n8n-config/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

  main:
    image: docker.n8n.io/n8nio/n8n:1.8.2
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
    ports:
      - 5678:5678
    links:
      - postgres
    depends_on:
      - postgres

# environment
# POSTGRES_USER=postgresuser
# POSTGRES_PASSWORD=mysecretpassword
# POSTGRES_DB=n8n
# POSTGRES_NON_ROOT_USER=postgresnonrootuser
# POSTGRES_NON_ROOT_PASSWORD=mysecretpassword
# N8N_LOCAL_FILES=/home/user/n8n-local-files [ EDIT THIS!!! ]
# N8N_VERSION=1.3.1
```

Content of ${N8N_LOCAL_FILES}/n8n-config/init-data.sh to initialize n8n database:

```
#!/bin/bash
set -e;


if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi
```

Output from container's console:

```
~ $ whoami
node

~ $ npm install --prefix=/usr/local/lib/node_modules/n8n/
npm notice 
npm notice New major version of npm available! 9.5.1 -> 10.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.0
npm notice Run npm install -g npm@10.2.0 to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: n8n-core@1.8.1
npm ERR! Found: n8n-nodes-base@1.8.2
npm ERR! node_modules/n8n-nodes-base
npm ERR!   n8n-nodes-base@"1.8.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer n8n-nodes-base@"1.8.1" from n8n-core@1.8.1
npm ERR! node_modules/n8n-core
npm ERR!   n8n-core@"1.8.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: n8n-nodes-base@1.8.1
npm ERR! node_modules/n8n-nodes-base
npm ERR!   peer n8n-nodes-base@"1.8.1" from n8n-core@1.8.1
npm ERR!   node_modules/n8n-core
npm ERR!     n8n-core@"1.8.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/node/.npm/_logs/2023-10-09T08_39_06_088Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-10-09T08_39_06_088Z-debug-0.log

~ $ 
```

**Comment by Joffcom** [comment] 2023-10-09 08:49
Hey @pablorq,

I don't fully understand what you are trying to do here, Could you share more information on what the actual goal is as the container would already have n8n installed so there would be no need to try and intall it again.

**Comment by netroy** [comment] 2023-10-09 08:49
isn't this a duplicate of #7364?
also, please don't install anything in `/usr/local/lib/node_modules/n8n/`.

**Comment by pablorq** [comment] 2023-10-09 09:10
> isn't this a duplicate of #7364? also, please don't install anything in `/usr/local/lib/node_modules/n8n/`.

No. I is not. I've closed the old one (#7364) and created this new one with only the data related to this issue.

**Comment by pablorq** [comment] 2023-10-09 09:13
Hi @netroy!

Please have in mind that nothing is installed in `/usr/local/lib/node_modules/n8n/`.

The install option is used to raise the error.

**Comment by Joffcom** [comment] 2023-10-09 09:14
Hey @pablorq,

What are you actually trying to do?

**Comment by pablorq** [comment] 2023-10-09 09:18
Just let you know that there's a dependency error between `n8n-nodes-base` and `n8n-core`.

Yes, the docker image is already built and works. But there's a dependency error.

I'm just reporting that. If you are aware of it and it's ok for you, please solve this issue.

Regards!

**Comment by Joffcom** [comment] 2023-10-09 09:20
Hey @pablorq,

Perfect in that case for now I am going to mark this as closed as there no context on what you are trying to do and there is no issue when actually running n8n.

**Closed by Joffcom** 2023-10-09 09:20 UTC
