### ISSUE TITLE
Unable to build and start n8n

### ISSUE THREAD

**Issue by dxh9845** [n8n-io/n8n#6586] opened 2023-07-03 21:02 UTC
**Describe the bug**
N8N fails to start with the following error.

```
➜ pnpm run start

> n8n@0.234.0 start /Users/danielherzig/cf-repos/n8n
> run-script-os


> n8n@0.234.0 start:default
> cd packages/cli/bin && ./n8n

License manager not initialized
n8n ready on 0.0.0.0, port 5678
Initializing n8n process
ServiceNotFoundError: Service with "MaybeConstructable<Push>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
    at ContainerInstance.get (/Users/danielherzig/cf-repos/n8n/node_modules/.pnpm/typedi@0.10.0_patch_hash=62r6bc2crgimafeyruodhqlgo4/node_modules/src/container-instance.class.ts:75:11)
    at Function.get (/Users/danielherzig/cf-repos/n8n/node_modules/.pnpm/typedi@0.10.0_patch_hash=62r6bc2crgimafeyruodhqlgo4/node_modules/src/container.class.ts:61:32)
    at Server.start (/Users/danielherzig/cf-repos/n8n/packages/cli/src/Server.ts:337:25)
    at Start.run (/Users/danielherzig/cf-repos/n8n/packages/cli/src/commands/start.ts:333:21)
    at Start._run (/Users/danielherzig/cf-repos/n8n/node_modules/.pnpm/@oclif+command@1.8.18_@oclif+config@1.18.5_supports-color@8.1.1/node_modules/@oclif/command/lib/command.js:43:20)
    at Config.runCommand (/Users/danielherzig/cf-repos/n8n/node_modules/.pnpm/@oclif+config@1.18.5_supports-color@8.1.1/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/Users/danielherzig/cf-repos/n8n/node_modules/.pnpm/@oclif+command@1.8.18_@oclif+config@1.18.5_supports-color@8.1.1/node_modules/@oclif/command/lib/main.js:28:9)
    at Main._run (/Users/danielherzig/cf-repos/n8n/node_modules/.pnpm/@oclif+command@1.8.18_@oclif+config@1.18.5_supports-color@8.1.1/node_modules/@oclif/command/lib/command.js:43:20)
```

**To Reproduce**

1. git pull latest
2. Run `pnpm install`, then `pnpm build`, then `pnpm start`
3. See error

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04] macOS Ventura Version 13.4.1 (22F82)
- n8n Version [e.g. 0.200.1]: Last commit is: e63b3982d200ade34461b9159eb1e988f494c025
- Node.js Version [e.g. 16.17.0]: v18.3.0
- Database system: SQLite
- Operation mode: own?

**Additional context**

**Comment by dxh9845** [comment] 2023-07-03 21:03
Because this error seemingly comes from the typedi package, I have tried to apply the patch here: patches/typedi@0.10.0.patch

But it doesn't apply cleanly.

**Comment by dxh9845** [comment] 2023-07-03 21:18
Here's what's registered on the "globalInstance.services" property on the container

```
0:
class LoadNodesAndCredentials
1:
class NodeTypes
2:
class AuthIdentityRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(AuthIdentity_1.AuthIdentity, dataSource.manager);\n    }\n}
3:
class AuthProviderSyncHistoryRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(AuthProviderSyncHistory_1.AuthProviderSyncHistory, dataSource.manager);\n    }\n}
4:
class CredentialsRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(CredentialsEntity_1.CredentialsEntity, dataSource.manager);\n    }\n}
5:
class EventDestinationsRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(EventDestinations_1.EventDestinations, dataSource.manager);\n    }\n}
6:
class ExecutionDataRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(ExecutionData_1.ExecutionData, dataSource.manager);\n    }\n}
7:
class ExecutionMetadataRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(ExecutionMetadata_1.ExecutionMetadata, dataSource.manager);\n    }\n}
8:
class License
9:
class ExecutionRepository
10:
class InstalledNodesRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(InstalledNodes_1.InstalledNodes, dataSource.manager);\n    }\n}
11:
class InstalledPackagesRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(InstalledPackages_1.InstalledPackages, dataSource.manager);\n    }\n}
12:
class RoleRepository
13:
class SettingsRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(Settings_1.Settings, dataSource.manager);\n    }\n}
14:
class SharedCredentialsRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(SharedCredentials_1.SharedCredentials, dataSource.manager);\n    }\n}
15:
class SharedWorkflowRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(SharedWorkflow_1.SharedWorkflow, dataSource.manager);\n    }\n}
16:
class TagRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(TagEntity_1.TagEntity, dataSource.manager);\n    }\n}
17:
class UserRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(User_1.User, dataSource.manager);\n    }\n}
18:
class VariablesRepository extends typeorm_1.Repository {\n    constructor(dataSource) {\n        super(Variables_1.Variables, dataSource.manager);\n    }\n}

```

**Comment by Joffcom** [comment] 2023-07-04 08:04
Hey @dxh9845,

Oddly I am not seeing this here, Can you try using the latest version and see if it is still an issue. When you did your pull was it also the first time you had ran n8n?

**Comment by netroy** [comment] 2023-07-04 08:10
@dxh9845 can you make sure that you are on the correct version of pnpm with `corepack enable && corepack prepare --activate`

**Comment by dxh9845** [comment] 2023-07-05 16:05
```n8n/packages/cli on  dherzig/AS-9787/refresh-main [$!?] is 📦 v0.234.0 via ⬢ v18.3.0 at ☸️  cfctl-pdx-b (ninjapanel-staging)  took 11m 23s
➜ corepack enable && corepack prepare --activate

n8n/packages/cli on  dherzig/AS-9787/refresh-main [$!?] is 📦 v0.234.0 via ⬢ v18.3.0 at ☸️  cfctl-pdx-b (ninjapanel-staging)
➜ pnpm -v
8.6.5```

**Comment by netroy** [comment] 2023-07-05 16:32
not sure if that's the cause, but your version is `8.6.5`, while n8n [expects](https://github.com/n8n-io/n8n/blob/master/package.json#L10) `8.6.1`.
Either way, I'm working on getting rid of that patch soon.

**Comment by netroy** [comment] 2023-07-28 06:43
@dxh9845 were you able to resolve this issue? can you please also share more info on what changes you are making to the code?
This error only happens when there is a circular dependency between service classes. since we aren't seeing this issue, I'm assuming that either your changes might be introducing the circular dependencies, or you are hitting some code path that the rest of us aren't.

**Comment by netroy** [comment] 2023-08-16 17:30
@dxh9845 any updates on this? if not, maybe we should close this ticket.

**Comment by dxh9845** [comment] 2023-08-16 18:48
Hey sorry we ended up having to reimplement the build from the main branch, so we stopped trying to fix this error. We can close for now. Thanks.

**Closed** 2023-08-16 18:48 UTC
