### ISSUE TITLE
ActiveCampaign Node Trigger Bug

### ISSUE THREAD

**Issue by kaueca** [n8n-io/n8n#9195] opened 2024-04-23 04:49 UTC
### Bug Description

After updating from version 1.34.2 to 1.37.3, it is no longer possible to use Node Trigger and the Api returns a timeout, in addition to N8N entering a large loading

### To Reproduce

Open the ActiveCampaign node Trigger, try to add an authentication key via api, now try to work with the data or save the workflow

### Expected behavior

Integrate and receive triggers correctly

### Operating System

Ubuntu 22.04 64bit with Docker

### n8n Version

1.37.3

### Node.js Version

16.x

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-04-23 07:24
Hey @kaueca,

I am not able to reproduce this, When you say the API returns a timeout can you be more specific and share the error message?

Can you also try `1.38.1` and let me know if you get the same issue there?

**Comment by Joffcom** [comment] 2024-05-15 19:44
Moving to closed for now, We can open it again if this is still an issue.

**Closed by Joffcom** 2024-05-15 19:44 UTC
