### ISSUE TITLE
Convert port to number automatically

### ISSUE THREAD

**Issue by botzill** [n8n-io/n8n#863] opened 2020-08-20 08:09 UTC
Hi.

I try to deploy this using kubernetes and helm chat and when I give the PG port I can give it a string. Is posible to convert it to integer automatically? I get this:

```
(node:7) UnhandledPromiseRejectionWarning: Error: There was an error: Port should be >= 0 and < 65536. Received NaN.
    at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
    at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
    at /usr/local/lib/node_modules/n8n/dist/commands/start.js:114:22
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by RicardoE105** [comment] 2020-08-25 15:01
Hey, pal @ahsanv any idea what might be happening here? @botzill since this a question and not a confirmed bug can you please post this in the community, you might be able to find an answer there. https://community.n8n.io/

**Comment by DerFetzer** [comment] 2020-09-24 22:50
I have the same problem, but I am using the sqlite database. So it might not be related to postgres.
The only environment variables I am using are both timezone ones.
What can I do to provide further information?

**Comment by DerFetzer** [comment] 2020-09-26 22:35
@RicardoE105 I have found the cause of the problem. Kubernetes is creating quite a few environment variables inside the containers with pod and service information. So if you have a service with the name `n8n` Kubernetes is creating variables including `N8N_PORT=tcp://x.x.x.x:y` which is a variable that n8n tries to read and parse to a number.
Solution would be to name the service something else for example `n8n-svc`.

**Comment by RicardoE105** [comment] 2020-09-26 22:39
ahh cool. @janober @ahsanv @BHesseldieck are better suited to answer this.

**Comment by janober** [comment] 2020-12-13 18:00
Closing this issue as it is nothing we can fix in n8n (unless we would rename the variable which would break it for existing users) the problem is that k8s automatically creates environment variables which interfere with n8n. The solution seems to be naming the service not "n8n" or setting the variable specifically to the intended value.

If anybody disagrees please simply comment.

**Closed by janober** 2020-12-13 18:00 UTC

**Comment by zhongjie-chen** [comment] 2021-08-16 05:38
mark
