### ISSUE TITLE
Gitlab trigger can't active

### ISSUE THREAD

**Issue by SpyFax** [n8n-io/n8n#5185] opened 2023-01-18 04:32 UTC
**Describe the bug**
Gitlab Trigger use `Listen for event` to test, it's working fine. But when I try to active this workflow, it show can't active
![image](https://user-images.githubusercontent.com/121141484/213083655-23457ed1-b147-4db2-8a9f-57315fdc8938.png)

**To Reproduce**

1. Click `Listen For Event`
2. Test webhook appera in Gitlab 
![image](https://user-images.githubusercontent.com/121141484/213083880-b43d2ad1-8ae7-4865-9f7a-8f990fe5af95.png)

3. Click test webhook at Gitlab, N8N can recive data 
![image](https://user-images.githubusercontent.com/121141484/213084086-6c5ae487-ba6c-4bd6-a983-cb81b34b21e0.png)

4. Click `Inactive` to active this workflow, show error.  
![image](https://user-images.githubusercontent.com/121141484/213084209-bbd12c64-d800-4639-88c9-8b18bc9237ec.png)

**Environment (please complete the following information):**

- OS: Docker base on Debian 11
- n8n Version: 0.211.1
- Node.js Version: v18.13.0
- Database system: postgres 14.6
- Operation mode: own

**Comment by Joffcom** [comment] 2023-01-18 08:29
Hey @SpyFax,

Thanks for reporting this one, I have just given it a quick go and it appears to be working for me. Looking at your screenshot again you appear to be using a self hosted version of Gitlab, What version are you using?

**Comment by Joffcom** [comment] 2023-01-18 09:39
Hey @SpyFax,

I would assume that would work ok, I did my test on the hosted version though. I will look to get a self hosted instance set up to see if I can reproduce this.

When it fails does anything appear in the Gitlab logs?

**Comment by SpyFax** [comment] 2023-01-18 10:08
> Hey @SpyFax,
> 
> I would assume that would work ok, I did my test on the hosted version though. I will look to get a self hosted instance set up to see if I can reproduce this.
> 
> When it fails does anything appear in the Gitlab logs?

Hey @Joffcom 
I'm use `sudo gitlab-ctl tail  | grep n8n` to filter log
`Listen For Event` have log like this, seems N8N make a post request to Gitlab
<img width="1852" alt="image" src="https://user-images.githubusercontent.com/121141484/213143306-c69bb200-86ad-491c-b042-7e99fda4d0af.png">

`active` don't have log

**Comment by SpyFax** [comment] 2023-01-28 07:32
Hey @Joffcom 
I'm try to create a new Workflow of Gitlab trigger, and immediate active this Workflow. then it work, I can see Webhook in Gitlab setting. But when I click `Listen For Event` to test, it will can't active again.

I'm using N8N 0.213.0 and Gitlab 15.8.0-ee

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/121141484/215253353-b7bc590b-25c3-4e2e-a04b-f1ea47e9ee3f.png">

**Comment by Joffcom** [comment] 2023-01-30 09:13
Hey @SpyFax,

Perfect thanks, I will see if I can get this reproduced now.

**Comment by Joffcom** [comment] 2023-06-14 15:24
Hey @SpyFax,

I was not able to reproduce this in the end, Is it still causing issues for you?

**Comment by Joffcom** [comment] 2023-07-25 14:45
Closing for now as I suspect this has been resolved. If this is not the case let me know and we can open it again.

**Closed by Joffcom** 2023-07-25 14:45 UTC
