### ISSUE TITLE
Posting via LinkedIn node cuts off content when using "(" character

### ISSUE THREAD

**Issue by jonmunson** [n8n-io/n8n#10179] opened 2024-07-24 20:58 UTC
### Bug Description

When posting the following:

`This is a test. (This is also a test.)`

The output on LinkedIn is:

`This is a test. `

### To Reproduce

1. Add content to be posted to LinkedIn node
2. Execute
3. If content contains "(" it will be cut off

### Expected behavior

Use of special characters such as "(" should be handled, same way that line breaks are.

### Operating System

Docker on Unraid

### n8n Version

1.51.1

### Node.js Version

?

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-07-24 22:49
Hey @jonmunson 

This looks like a duplicate of a post that I spotted on the forum earlier today and started to look into which can be found here: https://community.n8n.io/t/linkedin-node-not-posting-full-output/47477/3

To save on duplicate issue reports I am going to close this one and we can pick this up over there. If you have any questions on this let me know.

**Closed by Joffcom** 2024-07-24 22:49 UTC
