### ISSUE TITLE
NocoDB hard-coded query limit

### ISSUE THREAD

**Issue by fishnux** [n8n-io/n8n#3022] opened 2022-03-22 05:45 UTC
https://github.com/n8n-io/n8n/blob/fa7b12c3a3e81b86c76b6490b0d6e4f81115ded8/packages/nodes-base/nodes/NocoDB/GenericFunctions.ts#L91

This query limit is hardcoded instead of being exposed in the UI/options - is this the right place to ask for such to be corrected?

Initial pull request:
https://github.com/n8n-io/n8n/pull/1969

Pinging @MedAliMarz

Edit: Or maybe implement pagination

**Comment by Joffcom** [comment] 2022-03-22 08:11
Hey @fishnux,

This looks to be a duplicate of #2866, The best approach would be to implement pagination to loop over the results. For now I am going to mark this one as closed so we don't have multiple issues for the same problem 👍🏻

**Closed by Joffcom** 2022-03-22 08:11 UTC
