### ISSUE TITLE
 Invoice Ninja Trigger: The given data was invalid.

### ISSUE THREAD

**Issue by o-psi** [n8n-io/n8n#5343] opened 2023-02-02 18:07 UTC
**Describe the bug**
Invoice Ninja Triggers not working. When running the workflow, i get the following error.
```
Problem running workflow

UNKNOWN ERROR - check the detailed error for more information

Show Details

Invoice Ninja Trigger: The given data was invalid.
```

 Nothing is logged at debug log level>

**To Reproduce**
Create an invoice ninja Trigger, Attach an account, and run execution. See error.

**Expected behavior**
Expected to receive webhooks

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 in a linux CT
- n8n Version [0.213.0]
- Node.js Version [v18]
- Database system [SQLite]
- Operation mode [own]

**Comment by Joffcom** [comment] 2023-02-03 16:35
Hey @o-psi,

I have had a quick look and managed to reproduce the same issue, I am not sure if something has changed and it is a shame that we don't get a more useful response back.

Anyway I have created an internal ticket which we will be tracking as `NODE-247`, We should be able to get this fixed fairly soon. Out of interest what version of invoice ninja are you using?

**Comment by o-psi** [comment] 2023-02-03 19:09
v5.5.65-M105

**Comment by o-psi** [comment] 2023-02-08 19:52
Issue present on v5.5.68-M105

**Comment by Joffcom** [comment] 2023-02-08 21:57
Hey @o-psi 

It will likely be an issue until we update the node.

**Comment by turbo124** [comment] 2023-02-08 23:22
@Joffcom 

One of the devs here from IN, I believe the above response is a 422, so there should be additional payload in that message that would describe a potential field which has failed validation. If you need anything from our size, please tag me.

**Comment by o-psi** [comment] 2023-02-10 20:57
@Joffcom Im no longer getting that error. Now invoice ninja reports back "Server encountered a problem when connecting to https://n8n.twe.tech/webhook/xxxxxxx/ => Status code 503 no retry attempted.

**Comment by Joffcom** [comment] 2023-02-13 16:03
Hey @o-psi,

That is promising, I don't think we changed anything in the node so it might have been a core change that was made that has resolved it.

If you manually check that URL does it work?

**Comment by o-psi** [comment] 2023-02-13 19:46
I get a 
"{
    "message": "Workflow was started"
}"
when hitting it with a post on postman.

**Comment by Joffcom** [comment] 2023-02-14 09:11
Hey @o-psi,

That is good news, It would suggest n8n is listening and accepting requests. When you see the 503 is that in Invoice Ninja for the webhook?

**Comment by o-psi** [comment] 2023-02-14 22:48
Hey @Joffcom, 

I'm very exited to say it is working in most recent version.

**Comment by paulwer** [comment] 2023-02-16 22:58
https://github.com/invoiceninja/invoiceninja/issues/8260

this should be caused by the topic above and will be resolved, when updating your IN5 instance.

**Comment by Joffcom** [comment] 2023-06-14 16:10
Marking this as solved as it seems to be resolved.

**Closed by Joffcom** 2023-06-14 16:10 UTC
Labels: in linear
