### ISSUE TITLE
Getting 404 Not Found - GET https://registry.npmjs.org/colors/-/colors-1.4.1.tgz - Not found

### ISSUE THREAD

**Issue by RachaelSMathew** [n8n-io/n8n#2685] opened 2022-01-16 17:32 UTC
Hi, I'm currently using NextJS to create a web application. I have done `npm install n8n` in my project directory and then ran `npm install` and I am still getting this error 

1. Create a NextJS application: https://nextjs.org/learn/basics/create-nextjs-app?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=next-website
2. run `npm install n8n` in terminal 
3. run `npm install` in terminal 

<img width="774" alt="Screen Shot 2022-01-16 at 12 31 31 PM" src="https://user-images.githubusercontent.com/30049533/149671016-1f836d79-c664-4740-88fc-11a42e9c778e.png">

**Comment by Joffcom** [comment] 2022-01-16 17:36
Hey @RachaelSMathew,

If you install n8n outside of that directory do you get the same issue?

**Comment by RachaelSMathew** [comment] 2022-01-16 17:40
> Hey @RachaelSMathew,
> 
> If you install n8n outside of that directory do you get the same issue?
Yes.
<img width="763" alt="Screen Shot 2022-01-16 at 12 39 57 PM" src="https://user-images.githubusercontent.com/30049533/149671340-b2386c63-9cff-44ac-95f6-308f2dca6e79.png">

**Comment by janober** [comment] 2022-01-16 18:08
Please do not simply delete the questions that are asked by default, rather answer them. Thanks!

Here again:

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.119.0]
 - Node.js Version [e.g. 14.16.0]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**
Add any other context about the problem here.

**Comment by Joffcom** [comment] 2022-01-16 20:01
In a different directory without involving a

**Comment by Joffcom** [comment] 2022-01-16 20:05
In a different directory without involving Nuxt or any npm package file what happens if you just run npm install n8n?

If you wanted something you can copy and paste...

mkdir ~/n8n-test && cd ~/n8n-test && npm install n8n

I suspect this issue is because of the recent problem with the color.js library but what I want to see is if this is an issue with n8n or something in your nuxt project.

If you can run through this and complete the information Jan has requested we will be able to dig into this further.

**Comment by RachaelSMathew** [comment] 2022-01-16 22:58
> mkdir ~/n8n-test && cd ~/n8n-test && npm install n8n
Yes it is able to work successfully. 
<img width="747" alt="Screen Shot 2022-01-16 at 5 58 11 PM" src="https://user-images.githubusercontent.com/30049533/149681635-7b42ee38-8dc9-4a74-8098-291da89c6239.png">

**Comment by RachaelSMathew** [comment] 2022-01-16 23:08
> Please do not simply delete the questions that are asked by default, rather answer them. Thanks!
> 
> Here again:
> 
> **Environment (please complete the following information):**
> 
> * OS: [e.g. Ubuntu Linux 18.04]
> * n8n Version [e.g. 0.119.0]
> * Node.js Version [e.g. 14.16.0]
> * Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
> * Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]
> 
> **Additional context** Add any other context about the problem here.

OS: MacOS BigSur 11.3.1
n8n: 0.158.0
node: v14.17.6
Operation mode: `own`

**Comment by Joffcom** [comment] 2022-01-17 09:56
Hey @RachaelSMathew,

That is promising, Can you try again now? I have just ran the commands below and was not able to reproduce the issue, It could be that one of the other packages was using the pulled version of colors.js and it has been fixed now.
```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
cd nextjs-blog/
npm install n8n
npm install
```

**Comment by Joffcom** [comment] 2022-02-02 09:37
Hey @RachaelSMathew,

How are you getting on with this one?

**Comment by janober** [comment] 2022-10-01 15:20
As we did not get an answer for 8 months do I close this issue now.

**Closed by janober** 2022-10-01 15:20 UTC
