### ISSUE TITLE
XML-Node eventual consistent after finishing in terms of output

### ISSUE THREAD

**Issue by ixidion** [n8n-io/n8n#6043] opened 2023-04-21 06:33 UTC
**Describe the bug**
I have a XML-Tranform-Node in my flow to transform a XML-File to Json. The XML is around 40KB, but also 100KB are possible. The Node is followed by a Set-Node, which uses a few variables from the Json-Structure produced by the XML-Node. Around 15.04.2023 the whole workflow stopped working with the following error on the SET-Node:

`ERROR: Cannot read properties of undefined (reading 'name')`

After some investigation, I found out, that a Function-Node in between with a few seconds Wait-Time was a suitable workaround, but also reveals the problem. The data-structure of the XML-Node is not available, when it should be finished. Maybe there are some async processes running, which have not been properly finished, when reaching the SET-Node.

The actual behavior is eventual consistent after this node has been finished, which is not acceptable.

**To Reproduce**

See above

**Expected behavior**
When a node/the XML-Node is finished, the produced data has to be available for the next nodes before continuing the workflow.

**Environment (please complete the following information):**

- OS: Debian
- n8n Version 0.224.1 (but started with 0.222.3)
- Node.js Version from official Docker Container
- Database system PostgreSQL
- Operation mode own

**Additional context**
The Reproducability is influence by Hard-/Software-Environment, Size of XML-File, Async-Behavior

**Overview whole workflow**
![image](https://user-images.githubusercontent.com/5589359/233774479-1c0e865e-18a3-4be3-b379-324d66e2100b.png)

**Comment by Joffcom** [comment] 2023-04-21 06:41
Hey @ixidion 

Thanks for the report, can you share an xml file and a workflow that reproduces this?

**Comment by ixidion** [comment] 2023-04-21 07:05
> Hey @ixidion
> 
> Thanks for the report, can you share an xml file and a workflow that reproduces this?

Yes, I can share an anonymized version of the XML, but don't want to upload it to public Github. Is hello@n8n.io okay?

**Comment by Joffcom** [comment] 2023-04-21 08:25
You can try sending it there but I may not get it as quickly as a gist or similar

**Comment by Joffcom** [comment] 2023-04-21 09:32
Hey @ixidion,

I have just generated a 127kb XML file on Mockaroo which has 1000 records in it, Read the file in n8n, moved from binary to json then xml to json then used item lists to split out the data and popped in a set node and this seems to be working as expected.

I am wondering if maybe there is something else going on, The dataset and workflow I used can be found here: https://gist.github.com/Joffcom/f527fff84a0bdfc5404e8aa68104b97c can you give that a go and see if you have the same issue?

**Comment by ixidion** [comment] 2023-04-22 09:52
Hi @Joffcom,
I have tried with the workflow provided and it works with the sample file, but causes the same issue with the my sample, I have provided you via email. The problem is also somehow related to the data.

**Comment by ixidion** [comment] 2023-04-22 10:13
Additional investigation showed: Copying the whole XML-Tree to a Set-Variable causes the error in the end and that also happens with your testdata.
Here is the workflow to reproduce: https://gist.github.com/ixidion/bb7f353d117863e0bd3d43198e083a5c

**Comment by Joffcom** [comment] 2023-06-16 08:27
@ixidion just catching up on this one, It seems to be ok if the individual node is ran as well just not as a complete workflow. I have created `N8N-6518` as the internal ticket to look into this in more detail and hopefully get it resolved.

**Comment by janober** [comment] 2023-07-05 13:30
Fix got released with [`n8n@0.234.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.234.1)

**Comment by Joffcom** [comment] 2023-07-05 13:46
Hey @ixidion, 

I am going to get this one marked as closed, If you are still having issues with it after updating let me know and we can open it again.

**Closed by Joffcom** 2023-07-05 13:46 UTC
Labels: in linear, Released
