### ISSUE TITLE
Google Calendar Node: Unable to Add Conference Data (Error Fetching Options)

### ISSUE THREAD

**Issue by jimleuk** [n8n-io/n8n#11240] opened 2024-10-13 21:00 UTC
### Bug Description

Finding a strange issue with trying to add the "conference data" option when creating an event using the Google Calendar node (and by extension the Google Calendar Tool). The error I'm seeing is under "Conference Data" > "Type Name or ID", the message "Error Fetching Options from Google Calendar" - even though I've confirm by Google OAuth is working fine.

I've inspected using developer tools and found the following error which makes me think this is not a Google error.
```
POST https://<REDACTED>.app.n8n.cloud/rest/dynamic-node-parameters/options 500 (Internal Server Error)
{
    "code": 0,
    "message": "The resource you are requesting could not be found",
    "level": "warning",
    "tags": {},
    "context": {},
    "functionality": "regular",
    "name": "NodeApiError",
    "timestamp": 1728852317657,
    "node": {
        "parameters": {
            "notice": "",
            "descriptionType": "auto",
            "resource": "event",
            "operation": "create",
            "calendar": {
                "__rl": true,
                "value": "<REDACTED>@group.calendar.google.com",
                "mode": "list",
                "cachedResultName": "n8n-events"
            },
            "start": "",
            "end": "",
            "useDefaultReminders": true,
            "additionalFields": {
                "conferenceDataUi": {
                    "conferenceDataValues": {
                        "conferenceSolution": ""
                    }
                }
            },
            "useN8nTimeZone": ""
        },
        "id": "uuid-1234",
        "name": "Temp-Node",
        "type": "n8n-nodes-base.googleCalendar",
        "typeVersion": 1.1,
        "position": [
            0,
            0
        ],
        "credentials": {
            "googleCalendarOAuth2Api": {
                "id": "<REDACTED>",
                "name": "Google Calendar account"
            }
        }
    },
    "messages": [
        "404 - {\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"notFound\",\"message\":\"Not Found\"}],\"code\":404,\"message\":\"Not Found\"}}"
    ],
    "httpCode": "404",
    "description": "Not Found"
}
```

### To Reproduce

1. Add Google Calendar node and ensure credentials are set
2. Set "Resource" to "Event", "Operation" to "Create"
3. In Additional Fields section, add "Conference Data"
4. Click the "Add Conference" button
5. I'm unable to select a value under the "Type Name or ID" field and see the Error message "Error Fetching Options from Google Calendar"

I'm also seeing the same issue on Community Edition 1.62.1

### Expected behavior

I'm able to select a value under the Conference Data > Type Name or ID field.
And perhaps the endpoint `POST https://<REDACTED>.app.n8n.cloud/rest/dynamic-node-parameters/options` should not throw a 500 (if error is related to main issue)

### Operating System

Cloud & Community Editions

### n8n Version

1.62.4

### Node.js Version

???

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-10-13 21:01
Hey @jimleuk,

We have created an internal ticket to look into this which we will be tracking as "GHC-313"

**Comment by Joffcom** [comment] 2024-10-13 21:15
@jimleuk this looks to be a duplicate of #11183 which has a fix merged and will be available in a future release.

For now I am going to mark this as closed, let me know if this issue is different to the one already reported and fixed.

**Closed** 2024-10-13 21:15 UTC
Labels: in linear
