### ISSUE TITLE
0.215.1 Switch and IF node got mixed up in outputs / operations

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#5471] opened 2023-02-14 03:39 UTC
sadly the switch node output got messed up in version 0.215.1. 

Lucky I found that before more damage happened....

Very bad error with production workflows - when are you doing a stable and development version for docker containers finally?

**Comment by Joffcom** [comment] 2023-02-14 05:44
Hey @prononext 

Which version of n8n did you upgrade from?

When you say the output got messed  up what do you mean? Did the connections change place or did the expression / rule output change?

Do you happen to have a workflow that shows the issue in action?

A stable and development version isn't a bad idea but even if we were to mark something as stable there could be issues that we are not aware of like this. The best option would be to also run a test environment where you can do your workflow building and test new versions before upgrading your main instance.

**Comment by prononext** [comment] 2023-02-14 05:55
Hi @Joffcom, 

I upgraded from 0.215.0. 

I had a switch node with the operation to output on output 1, depending a field equals a entered value. 
After the update 2 switch nodes changed and the operation I entered was 2 instead of 1. 
So the switch-node made the output on 2. 

This workflows (2 are affected) I cannot share as its about 50 nodes, but it was running for about 3 month now, without any problems, and I was keeping an eye on it. 

After this update 215.1 I suddenly got a notification on one workflow where something went wrong because of the false output and luckily also checked the other one, which just got a success as the wrong output had no further nodes behind it. 

I wish I could replicate it for you, but thats all I have.

**Comment by Joffcom** [comment] 2023-02-14 06:50
I would be surprised if any of the changes between 215 and 215.1 caused an issue but I will do some digging.

So it sounds like the output number changed, I might be able to reproduce that.

**Comment by prononext** [comment] 2023-02-14 06:56
Similar thing happened on a IF node  where the output has changed. 

![image](https://user-images.githubusercontent.com/24569958/218660817-5648412e-6773-4e45-9047-99db4e771141.png)

![image](https://user-images.githubusercontent.com/24569958/218661045-b29a076d-2cdf-4058-aca4-0ff6f4ccb689.png)

I used this inside a workflow for about 5 month now with multiple daily executions. 

The workflow was creating product categories and then assigning them in a batch by 1 to a couple houndret of products. 
I wondered why today only one category was assigned to one product - then I noticed that.

**Comment by Joffcom** [comment] 2023-02-14 07:01
So with the if node did the output line from false to true?

**Comment by prononext** [comment] 2023-02-14 07:31
correct. thats the if node that is used to determine if a batch is completed.

**Comment by Joffcom** [comment] 2023-02-14 08:16
Hey @prononext,

I have checked a bunch of workflows on my local instance and tried to reproduce this by going between different versions and making new test workflows with no luck.

Do you happen to have a backup of your older workflows that you could put on a test instance and try upgrading again to see if it happens again? Or if you take the current workflow and put it on a 215 or earlier then upgrade does it swap again?

Without being able to reproduce it or a workflow that caused it I am not sure what else I can actually do with this one.

@netroy do you have any thoughts?

**Comment by ShawNexT** [comment] 2023-02-16 22:30
This was also in the update from 0.214.2 to 0.214.3

**Comment by prononext** [comment] 2023-02-16 22:48
Hi @Joffcom , sorry I was debugging the affected workflows for a week now and got everything running again.
In the next 2-3 weeks I won't have time to do a test deployment for the issue. Hopefully it will be solved till then, if not I will get to it.

**Comment by Joffcom** [comment] 2023-02-17 07:46
Hey @prononext

It is going through be a tricky one. I have still not managed to reproduce it on any of the instances I have which is really odd, the second report though is interesting I am surprised there has not been a lot more though.

**Comment by markusobi0** [comment] 2023-02-17 09:18
Here a Sidenote: Sadly there is not only the if node affected. I updated from 0.210.2 to 0.216.0 and on my instance the Compare Datasets Node and Item Lists Node got also messed up with fields that got reset or the handling switched places!

**Comment by Joffcom** [comment] 2023-02-22 11:23
Morning,

It looks like this has been reproduced internally now and we have created an internal ticket which we are tracking as `NODE-323`

**Comment by janober** [comment] 2023-03-05 19:13
Very sorry it seems like we somehow did not close this issue.

Please upgrade your n8n instance to the latest version `0.218.0` and use the following workflow to find all workflows which were potentially affected by that issue and reconnect the nodes accordingly:
https://n8n.io/workflows/1892-get-workflows-affected-by-02143-migration/

**Closed by janober** 2023-03-05 19:13 UTC
Labels: in linear
