### ISSUE TITLE
odoo node login issue

### ISSUE THREAD

**Issue by lucalamo** [n8n-io/n8n#9884] opened 2024-06-27 16:04 UTC
### Bug Description

i've upgraded n8n from 1.45.1 to 1.47.1 then the odoo node can't login anymore
![image](https://github.com/n8n-io/n8n/assets/115069159/82c02e15-ca39-44f9-a6ca-41d2cb2616ec)

### To Reproduce

use and configure one odoo node and can't login

### Expected behavior

odoo node can login

### Operating System

ubuntu 22.04

### n8n Version

1.47.1

### Node.js Version

18.17.1

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by netroy** [comment] 2024-06-27 16:07
This is a duplicate of #9873 .
Can you please try upgrading node.js to the latest 18, or 20 release 🙏🏽

**Comment by Joffcom** [comment] 2024-06-27 16:14
I would also recommend using the Docker image which will reduce issues like this.

**Closed** 2024-06-27 16:13 UTC

**Comment by janober** [comment] 2024-07-01 11:26
Fix got released with [`n8n@1.47.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.2)
