### ISSUE TITLE
Wekan node - "Cannot read properties of 'null'

### ISSUE THREAD

**Issue by DimDz** [n8n-io/n8n#7639] opened 2023-11-07 14:23 UTC
**Describe the bug**
We cannot see the Board Name, List Name, Swimlane Name and Author Name when there is additional field with expression in Wekan nodes that create or update .

**To Reproduce**

1. Create a Card wekan node
2. Add Description to be included in the additional fields
3. In the Description add an Expression that comes from previous node, for example {{ $('Schedule Trigger').timestamp }}

**Expected behavior**
From v1.8.2 and earlier, it was working correctly.

**Environment:**
- n8n Version 1.15.1
- Node.js Version 18.18.2
- Database system: SQLite
- Operation mode: Default

**Additional context**

![Screenshot 2023-11-07 162205](https://github.com/n8n-io/n8n/assets/70445835/74061984-3fd9-498c-a9d8-2f563ec57dc1)

`{
  "meta": {
    "instanceId": "4256b2b29d3f2efe0e8a2b89200494475c59768e9f2d65faf67c0758c3745421"
  },
  "nodes": [
    {
      "parameters": {
        "boardId": "mTYybPXXqNv8kWX5T",
        "listId": "BvM5REyuuPp3oGusY",
        "title": "My Card",
        "swimlaneId": "yuvDTdhjQMX6TvddB",
        "authorId": "TPqeaTcp5F3LqghdX",
        "additionalFields": {
          "description": "={{ $('Schedule Trigger').timestamp }}"
        }
      },
      "id": "67576072-880f-47d2-a49c-25263abfcadf",
      "name": "Wekan",
      "type": "n8n-nodes-base.wekan",
      "typeVersion": 1,
      "position": [
        2940,
        1180
      ],
      "credentials": {
        "wekanApi": {
          "id": "RRG5SxUTGRfnVp34",
          "name": "Wekan Credentials"
        }
      }
    },
    {
      "parameters": {
        "rule": {
          "interval": [
            {}
          ]
        }
      },
      "id": "37eab515-31f9-45e5-aec5-db052c99cfd5",
      "name": "Schedule Trigger",
      "type": "n8n-nodes-base.scheduleTrigger",
      "typeVersion": 1.1,
      "position": [
        2800,
        1180
      ]
    }
  ],
  "connections": {
    "Schedule Trigger": {
      "main": [
        [
          {
            "node": "Wekan",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

**Comment by Joffcom** [comment] 2023-11-07 14:56
Hey @DimDz,

I don't think we have touched the Wekan node properly for a while, Are your credentials still correct and have you also updated Wekan recently as well?

**Comment by DimDz** [comment] 2023-11-07 16:45
> Hey @DimDz,
> 
> I don't think we have touched the Wekan node properly for a while, Are your credentials still correct and have you also updated Wekan recently as well?

Credentials are correct, I use n8n 1.8.2 and it works fine, but when I upgrade, these errors occur.

**Comment by Joffcom** [comment] 2023-11-08 09:49
Hey @DimDz,

I have just given this a go on `1.15.1` with Wekan `7.12.0` and it appears to be working for me.

![image](https://github.com/n8n-io/n8n/assets/4688521/36a8b950-c6f4-4210-a2db-0f0a3b3b5503)

If you add a Wekan node to the editor and select your credential does it work? Is the credential test also showing a success?

As a test could you run the workflow below and let me know if it throws any errors it should do the same think the node does to get the list of boards, First it gets the current user id then uses that to get the list of boards the user has access to.

You will need to update the "Config" node and update the `wekanUrl` value then hit Execute Workflow and we can see where it fails.

```
{
  "meta": {
    "instanceId": "8c8c5237b8e37b006a7adce87f4369350c58e41f3ca9de16196d3197f69eabcd"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "63392733-1d7c-42bb-879d-b8dc98b8b2a9",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        580,
        340
      ]
    },
    {
      "parameters": {
        "fields": {
          "values": [
            {
              "name": "wekanUrl",
              "stringValue": "https://wekan.your-domain.com"
            }
          ]
        },
        "options": {}
      },
      "id": "96e861c0-0646-4a14-bc83-148583b4df68",
      "name": "Config",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.2,
      "position": [
        800,
        340
      ]
    },
    {
      "parameters": {
        "url": "={{ $('Config').first().json.wekanUrl }}/api/user",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "wekanApi",
        "options": {}
      },
      "id": "b3a59940-4fca-4e22-a9d2-4d70fbd8a6a1",
      "name": "Get User",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1000,
        340
      ],
      "credentials": {
        "wekanApi": {
          "id": "jzkCAd2tc2LY9Wv1",
          "name": "Wekan account"
        }
      }
    },
    {
      "parameters": {
        "url": "={{ $('Config').first().json.wekanUrl }}/api/users/{{ $json._id }}/boards",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "wekanApi",
        "options": {}
      },
      "id": "f624cb95-5c27-4b8a-a905-2b97a8644749",
      "name": "Get Boards",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1180,
        340
      ],
      "credentials": {
        "wekanApi": {
          "id": "jzkCAd2tc2LY9Wv1",
          "name": "Wekan account"
        }
      }
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Config",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Config": {
      "main": [
        [
          {
            "node": "Get User",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Get User": {
      "main": [
        [
          {
            "node": "Get Boards",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by DimDz** [comment] 2023-11-08 10:19
@Joffcom the test workflow works correctly and I can connect correctly.
Please have a look at the workflow I posted on my first post, it's only a trigger schedule node and a create a card wekan node. It works okay until I want to add an additional field that has an expression instead of a fixed value.

**Comment by Joffcom** [comment] 2023-11-08 10:57
Hey @DimDz,

🤔 That is interesting so it looks like the issue is not actually with the node itself as even in your example it is still able to load my settings.

![image](https://github.com/n8n-io/n8n/assets/4688521/508180a5-8445-4f39-87e1-ce6344c9abde)

If we ignore that the expression is invalid at the bottom the issue seems to only occur if the previous node has not ran so I suspect this could be linked to an issue we had a while back where dynamic options would not load if an expression was invalid.

As another example this also happens on our n8n node and you can't use the workflow selector because the previous node has not executed yet.

![image](https://github.com/n8n-io/n8n/assets/4688521/86ae16e1-0495-4632-bb26-801e830aea6e)

I will get a dev ticket written up for the general issue here.

**Comment by Joffcom** [comment] 2023-11-08 11:14
I have created `N8N-7040` as the dev ticket for this one, The good news is while it will get in the way of building a workflow if you have not ran the previous node it won't stop the worklfows from running.

**Comment by tomi** [comment] 2024-04-05 12:59
Hey @DimDz,

I could not reproduce this anymore with neither Wekan node nor n8nApi node using the latest n8n version (1.35.0). 

![image](https://github.com/n8n-io/n8n/assets/10324676/eb043cb1-eeb0-44ea-9bf5-6a5405267a46)

![image](https://github.com/n8n-io/n8n/assets/10324676/4cb019ea-6591-4e36-aaea-31d62d2e5a1a)

Could you verify that the issue has been resolved?

**Comment by tomi** [comment] 2024-04-29 11:34
I'll close this bug, as I couldn't reproduce it anymore. Feel free to reopen it if you still encounter the issue with the latest version.

**Closed by tomi** 2024-04-29 11:34 UTC
Labels: in linear
