### ISSUE TITLE
Can't build because of pdfjs-dist

### ISSUE THREAD

**Issue by KazeroG** [n8n-io/n8n#8400] opened 2024-01-19 21:57 UTC
**Describe the bug**
 It appears that there is an issue with the "pdfjs-dist" package that is causing the build to fail.

**To Reproduce**
Run pnpm build

Nixpacks config :

╔═════════ Nixpacks v1.20.0 ═════════════════════════╗

║ setup      │ nodejs_21, pnpm-8_x, libnss3, libatk1.0-0, libatk-bridge2.0-0,  ║

║            │ libcups2, libgbm1, libasound2, libpangocairo-1.0-0, libxss1,    ║

║            │ libgtk-3-0, libxshmfence1, libglu1                       ║

║───────────────────────────────────║

║ install    │ npm install -g corepack && corepack enable  ║

║            │ pnpm i --frozen-lockfile                                   ║

║──────────────────────────────────║

║ build      │ npx turbo run build                                       ║

║──────────────────────────────────║

║ start      │ pnpm run start                                               ║

╚══════════════════════════════════╝

**Expected behavior**

**Environment (please complete the following information):**

- OS: Ubuntu
- n8n Version :1.24.1
- "node": ">=18.10",
- "pnpm": ">=8.9"
- Node.js Version [e.g. 18.16.0]
- Database system : POSTGRES
- Operation mode = `queue`

**Additional context**
```
#14 61.59 n8n-nodes-base:build:     at get platform [as platform] (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:4222:23)

 

#14 61.59 n8n-nodes-base:build:     at new KeyboardManager (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:4202:35)

#14 61.59 n8n-nodes-base:build:     at <static_initializer> (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:4369:29)

#14 61.59 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:4342:22)

#14 61.59 n8n-nodes-base:build:     at __w_pdfjs_require__ (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:19477:41)

#14 61.59 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:3737:14)

#14 61.59 n8n-nodes-base:build:     at __w_pdfjs_require__ (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:19477:41)

#14 61.59 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:3562:15)

#14 61.59 n8n-nodes-base:build:     at __w_pdfjs_require__ (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:19477:41)

#14 61.59 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:1119:27)

#14 61.59 n8n-nodes-base:build:

#14 61.59 n8n-nodes-base:build: Node.js v21.1.0

#14 61.61 n8n-nodes-base:build:  ELIFECYCLE  Command failed with exit code 1.

 

#14 61.66 n8n-nodes-base:build:  ELIFECYCLE  Command failed with exit code 1.

#14 61.68 n8n-nodes-base:build: ERROR: command finished with error: command (/app/packages/nodes-base) pnpm run build exited (1)

#14 61.68 n8n-nodes-base#build: command (/app/packages/nodes-base) pnpm run build exited (1)

#14 61.68

#14 61.68  Tasks:    7 successful, 8 total

 

#14 61.68 Cached:    0 cached, 8 total

#14 61.68   Time:    1m0.746s

#14 61.68 Failed:    n8n-nodes-base#build

#14 61.68

#14 61.68  ERROR  run failed: command  exited (1)

 

#14 ERROR: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1

-----

> [stage-0 10/12] RUN --mount=type=cache,id=s/0605669e-0f2c-48fa-b10b-ac9408e2b40e-node_modules/cache,target=/app/node_modules/.cache npx turbo run build:

61.66 n8n-nodes-base:build:  ELIFECYCLE  Command failed with exit code 1.

61.68 n8n-nodes-base:build: ERROR: command finished with error: command (/app/packages/nodes-base) pnpm run build exited (1)

61.68 n8n-nodes-base#build: command (/app/packages/nodes-base) pnpm run build exited (1)

61.68

61.68  Tasks:    7 successful, 8 total

61.68 Cached:    0 cached, 8 total

61.68   Time:    1m0.746s

61.68 Failed:    n8n-nodes-base#build

61.68

61.68  ERROR  run failed: command  exited (1)

-----

 

Dockerfile:25

-------------------

23 |     # build phase

24 |     COPY . /app/.

25 | >>> RUN --mount=type=cache,id=s/0605669e-0f2c-48fa-b10b-ac9408e2b40e-node_modules/cache,target=/app/node_modules/.cache npx turbo run build

26 |

27 |

-------------------

ERROR: failed to solve: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1

 

Error: Docker build failed

 
```

**Comment by Joffcom** [comment] 2024-01-20 03:12
Hey @KazeroG,

I did a build from master a few hours ago and it appeared to be ok on my machine at the time 🤔

Can you try using Node 18 and see if that works, the output looks like you are using 21 which we don't officially support yet.

The error at the bottom mentions that the docker build failed, are you doing more than just pnpm install / pnpm build on the master branch and maybe building a docker image?

**Comment by KazeroG** [comment] 2024-01-20 03:23
@Joffcom Thank you for your review

I'll do some new tests and then get back to you on this.

**Comment by Joffcom** [comment] 2024-01-23 17:08
Hey @KazeroG,

How did you get on?

I have done a few builds locally on my machine over the last 2 days and we put out a release yesterday that didn't have the issue so I am curious to know if it was just the node version in the end.

**Comment by KazeroG** [comment] 2024-01-24 07:41
Hey @Joffcom the problem is in the Node version I was using, the node >=18.10 or pnpm >=8.9, but I don't know why that happened can't reproduce the same issue, sorry !

Maybe that node >=18.10 is incompatible with pnpm >=8.9, is it ?

But found that : 
![image](https://github.com/n8n-io/n8n/assets/17680194/8cab8b03-fb75-477d-8fde-1362ce1eb592)

I noticed this too, when will we move to node 20.x ? 
![image](https://github.com/n8n-io/n8n/assets/17680194/6249acf3-b848-4370-a804-a1c8c51c66d1)

To be followed ...

**Comment by Joffcom** [comment] 2024-01-24 08:42
Hey @KazeroG,

Could be, I have been using Node 18.18.2 with pnpm 8.9.0 though. We do have partial support for node 20 though and will probably be moving to that soon although we have until April 2025. I did just do a quick test on 20.11.0 with pnpm 8.9.0 and I didn't run into any issue running the build command for a bit of fun I just tried with 21.6.1 as well and I was able to install and build with no issues.

Can you share your build command as I suspect there is more to it than just `pnpm build` and that may help us work out what is going on.

**Comment by Joffcom** [comment] 2024-02-08 08:19
Hey @KazeroG,

Are you still seeing an issue with this?

**Comment by KazeroG** [comment] 2024-02-14 06:08
Hi @Joffcom Always same error even after reinstalling everything in a new instance 

this is the log 
```
#14 78.90 n8n-nodes-base:build:     at <static_initializer> (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:4369:29)

#14 78.90 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:4342:22)

#14 78.90 n8n-nodes-base:build:     at __w_pdfjs_require__ (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:19477:41)

#14 78.90 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:3737:14)

#14 78.90 n8n-nodes-base:build:     at __w_pdfjs_require__ (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:19477:41)

#14 78.90 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:3562:15)

#14 78.90 n8n-nodes-base:build:     at __w_pdfjs_require__ (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:19477:41)

 

#14 78.90 n8n-nodes-base:build:     at Object.defineProperty.value (/app/node_modules/.pnpm/pdfjs-dist@2.16.105/node_modules/pdfjs-dist/build/pdf.js:1119:27)

#14 78.90 n8n-nodes-base:build:

#14 78.90 n8n-nodes-base:build: Node.js v21.1.0

#14 78.94 n8n-nodes-base:build:  ELIFECYCLE  Command failed with exit code 1.

#14 78.99 n8n-nodes-base:build:  ELIFECYCLE  Command failed with exit code 1.

#14 79.02 n8n-nodes-base:build: ERROR: command finished with error: command (/app/packages/nodes-base) pnpm run build exited (1)

#14 79.02 n8n-nodes-base#build: command (/app/packages/nodes-base) pnpm run build exited (1)

 

#14 79.02

#14 79.02  Tasks:    7 successful, 8 total

#14 79.02 Cached:    0 cached, 8 total

#14 79.02   Time:    1m17.818s

#14 79.02 Failed:    n8n-nodes-base#build

#14 79.02

#14 79.02  ERROR  run failed: command  exited (1)

#14 ERROR: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1

 

-----

> [stage-0 10/12] RUN --mount=type=cache,id=s/87ab9c7a-dde0-455a-a0d2-65d55eb5c847-node_modules/cache,target=/app/node_modules/.cache npx turbo run build:

78.99 n8n-nodes-base:build:  ELIFECYCLE  Command failed with exit code 1.

79.02 n8n-nodes-base:build: ERROR: command finished with error: command (/app/packages/nodes-base) pnpm run build exited (1)

79.02 n8n-nodes-base#build: command (/app/packages/nodes-base) pnpm run build exited (1)

79.02

79.02  Tasks:    7 successful, 8 total

 

79.02 Cached:    0 cached, 8 total

79.02   Time:    1m17.818s

79.02 Failed:    n8n-nodes-base#build

79.02

79.02  ERROR  run failed: command  exited (1)

-----

 

Dockerfile:25

-------------------

23 |     # build phase

24 |     COPY . /app/.

25 | >>> RUN --mount=type=cache,id=s/87ab9c7a-dde0-455a-a0d2-65d55eb5c847-node_modules/cache,target=/app/node_modules/.cache npx turbo run build

ERROR: failed to solve: process "/bin/bash -ol pipefail -c npx turbo run build" did not complete successfully: exit code: 1

 

Error: Docker build failed
```

**Comment by Joffcom** [comment] 2024-02-14 16:14
Hey @KazeroG,

That is really odd, You are still not using Node 18 either...

Can you share the full error from the build it looks like the first part may be missing, I wonder if the issue is hardware related and it can't work out what CPU to build for or something. I know we don't support some ARM CPUs so could be the same here.

**Comment by mcnaveen** [comment] 2024-03-06 11:23
Can't reproduce this on `node v18.17.0` `pnpm v8.15.4`

**Comment by Joffcom** [comment] 2024-05-15 18:58
Moving to closed as this does't appear to be a bug with n8n and is likely to be environmental, Let me know if there are any questions on this.

**Closed by Joffcom** 2024-05-15 18:58 UTC
