### ISSUE TITLE
Use N8N_EDITOR_BASE_URL (if defined) to generate webook url

### ISSUE THREAD

**Issue by maximepvrt** [n8n-io/n8n#3069] opened 2022-03-29 16:16 UTC
**Describe the bug**
Currently the generated webhooks' unique url uses N8N_HOST with N8N_PORT and it doesn't use N8N_EDITOR_BASE_URL if it is defined.
For me, the generated webooks url is wrong, the port 8080 is added but my public n8n host is with default https port.

**Environment (please complete the following information):**
 - n8n Version 0.168.2

**Comment by Joffcom** [comment] 2022-03-30 06:10
Hey @maximepvrt,

The webhook url is set using `WEBHOOK_URL`, The `N8N_EDITOR_BASE_URL` key is used for the UI of n8n and for email notifications at the moment from the user management feature.

I feel like this is more of a feature request than an issue as it is currently working as intended.

Give the `WEBHOOK_URL` key a go and let me know how you get on.

**Comment by maximepvrt** [comment] 2022-03-30 09:08
```
export N8N_EDITOR_BASE_URL=$N8N_PROTOCOL://$N8N_HOST
export WEBHOOK_URL=$N8N_EDITOR_BASE_URL
```

It works with this config, thanks!
`WEBHOOK_URL` should not be defined by `N8N_HOST` or if defined by `N8N_EDITOR_BASE_URL` or a custom value with `WEBHOOK_URL` ?

**Comment by Joffcom** [comment] 2022-03-30 10:49
It defaults to `N8N_PROTOCOL`, `N8N_HOST` and `N8N_PORT` which is ok unless you are using a reverse proxy which is when `WEBHOOK_URL` normally comes out. We did talk internally when we released the user management feature about just using the `WEBHOOK_URL` option for the email notifications but that then has another issue where if you are using n8n in queue mode you would have different webhook and editor URLs so what in theory should be simple to do has some complexity to it.

**Comment by Joffcom** [comment] 2023-01-17 17:15
Hey @maximepvrt,

I think for now I am going to close this one as it more of a config issue than a bug to fix, Let me know if you feel differently about this and we can open it again and work out what to do next.

**Closed by Joffcom** 2023-01-17 17:15 UTC
