### ISSUE TITLE
Spotify Get Tracks error

### ISSUE THREAD

**Issue by larsassink** [n8n-io/n8n#12241] opened 2024-12-16 08:46 UTC
### Bug Description

After running my workflow it hits the following error: No execution data available. 

`{
  "errorMessage": "No execution data available",
  "errorDetails": {},
  "n8nDetails": {
    "itemIndex": 0,
    "runIndex": 0,
    "parameter": "id",
    "time": "12/16/2024, 9:26:03 AM",
    "n8nVersion": "1.71.3 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "ExpressionError: No execution data available",
      "    at Object.get (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/WorkflowDataProxy.js:310:31)",
      "    at Proxy.eval (eval at getFunction (/usr/local/lib/node_modules/n8n/node_modules/@n8n/tournament/dist/FunctionEvaluator.js:14:22), <anonymous>:6:76)",
      "    at FunctionEvaluator.evaluate (/usr/local/lib/node_modules/n8n/node_modules/@n8n/tournament/dist/FunctionEvaluator.js:20:19)",
      "    at Tournament.execute (/usr/local/lib/node_modules/n8n/node_modules/@n8n/tournament/dist/index.js:43:31)",
      "    at evaluateExpression (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/ExpressionEvaluatorProxy.js:123:16)",
      "    at Expression.renderExpression (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Expression.js:238:70)",
      "    at Expression.resolveSimpleParameterValue (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Expression.js:217:34)",
      "    at Expression.getParameterValue (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Expression.js:300:25)",
      "    at ExecuteContext._getNodeParameter (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/node-execution-context/node-execution-context.js:160:46)",
      "    at ExecuteContext.getNodeParameter (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/node-execution-context/execute-context.js:29:93)"
    ]
  }
}`

### To Reproduce

1. Add the Spotify node
2. Put resource to "playlist"
3. Put operation to "Get Tracks"
4. Enter playlist ID
5. run and get an error

### Expected behavior

The expected behavior should be that it outputs all my songs in the playlist

### Operating System

Ubuntu linux 22.04

### n8n Version

1.71.3

### Node.js Version

18.17.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-12-16 08:46
Hey @larsassink,

We have created an internal ticket to look into this which we will be tracking as "N8N-7975"

**Comment by Joffcom** [comment] 2024-12-16 09:20
Hey @larsassink,

This will be fixed as part of this PR: https://github.com/n8n-io/n8n/pull/12080

**Comment by Joffcom** [comment] 2024-12-17 15:54
Should add... I am going to close this as it is a duplicate of #12026

**Closed by Joffcom** 2024-12-17 15:54 UTC
Labels: in linear

**Comment by janober** [comment] 2025-01-15 14:33
Fix got released with [`n8n@1.75.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.75.0)
