### ISSUE TITLE
Unable to send/upload files greater than 2GB in size

### ISSUE THREAD

**Issue by arladmin** [n8n-io/n8n#7759] opened 2023-11-20 13:07 UTC
**Describe the bug**
I'm unable to send/upload any file, greater than 2GB in size, from my filesystem, anywhere using n8n, whether it's via S3, HTTP node, Code node (raw Axios request) etc.

Example:

![image](https://github.com/n8n-io/n8n/assets/64059154/6f818ebf-78aa-48e1-9471-6de9a1c074b2)

**Expected behavior**
Some sort of a workaround should be there to circumvent this issue.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04] Windows as well as Linux
- n8n Version [e.g. 1.0.1] 1.17.1
- Node.js Version [e.g. 18.16.0] 18.18.2
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed] Postgres
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`] main

**Additional context**
  - NODE_OPTIONS="--max-old-space-size=20500"
  - N8N_PAYLOAD_SIZE_MAX=10240
  - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
  - resources:
          cpus: '10'
          memory: 20g

**Comment by netroy** [comment] 2023-11-20 13:22
This particular error comes from the generic S3 node [still reading the files into memory](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/S3/S3.node.ts#L838) for the `upload` operation. 
A quick fix would be to switch to streaming.
The proper long-term solution would be to enable multi-part uploads, [like we do for the AWS S3 node](https://github.com/n8n-io/n8n/pull/6017).

Are you uploading to AWS S3, or some other S3 compatible service?

**Comment by netroy** [comment] 2023-11-20 13:32
The latest version of the HTTP node [already](https://github.com/n8n-io/n8n/pull/5610) supports streaming binary data since 8 months.

I suspect either your workflow is using an older version of the http node, or the env variable `N8N_DEFAULT_BINARY_DATA_MODE=filesystem` is somehow not getting passed in to n8n.

Can you please share a test workflow where you can reproduce this?

**Comment by arladmin** [comment] 2023-11-21 07:45
@netroy 
I'll try to share a sanitised version of my workflow.

Meanwhile, i tried the HTTP node again.

Here's the exact error:
![image](https://github.com/n8n-io/n8n/assets/64059154/e285085c-ce0e-48ad-aaac-717d72d6514b)


Note: 
`Ignore SSL Issues` = `true`

**Comment by netroy** [comment] 2023-11-21 10:22
`socket hang up` sounds like a completely different error though. That sounds like the server you are trying to talk to failed to respond in a timely manner.

**Comment by Joffcom** [comment] 2024-05-15 19:09
Moving to closed for now, if this is still an issue let me know and we can open it again.

**Closed by Joffcom** 2024-05-15 19:09 UTC
