### ISSUE TITLE
SplitInBatches: connection order influences 'noItemsLeft' flag

### ISSUE THREAD

**Issue by ebunders** [n8n-io/n8n#2951] opened 2022-03-09 07:21 UTC
**Describe the bug**
You have a splitInBatches node with two connections:
- the first connection loops back to input
- the second connection goes to a function node that reads 'noItemsLeft' on the splitInBatches node
The result is that 'noItemsLeft' will be true wile processing the last item but one as well as the last. 

**To Reproduce**
This simple workflow demonstrates the problem:
```
{
  "name": "debug_split_batches_fail",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        240,
        300
      ]
    },
    {
      "parameters": {
        "functionCode": "return [1,2,3,4,5].map(i=>({json: {number: i}}))"
      },
      "name": "Function1",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        460,
        320
      ]
    },
    {
      "parameters": {
        "batchSize": 1,
        "options": {
          "reset": false
        }
      },
      "name": "SplitInBatches",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 1,
      "position": [
        680,
        320
      ],
      "executeOnce": false
    },
    {
      "parameters": {
        "functionCode": "var lastItem = $evaluateExpression('{{$node[\"SplitInBatches\"].context[\"noItemsLeft\"]}}');\nconsole.log(\"lastItem:\",lastItem);\nconsole.log(\"current index:\", $evaluateExpression('{{$node[\"SplitInBatches\"].context[\"currentRunIndex\"]}}'));\n// currentRunIndex\n\nreturn items;"
      },
      "name": "Function",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [960, 320]
    }
    
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Function1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Function1": {
      "main": [
        [
          {
            "node": "SplitInBatches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "SplitInBatches": {
      "main": [
        [
          {
            "node": "SplitInBatches",
            "type": "main",
            "index": 0
          },
          {
            "node": "Function",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "id": 9
}
```
And this workflow fixes the problem by changing the order of the connections on the splitInBatches node:
```
{
  "name": "debug_split_batches_fail",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        240,
        300
      ]
    },
    {
      "parameters": {
        "functionCode": "return [1,2,3,4,5].map(i=>({json: {number: i}}))"
      },
      "name": "Function1",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        460,
        320
      ]
    },
    {
      "parameters": {
        "batchSize": 1,
        "options": {
          "reset": false
        }
      },
      "name": "SplitInBatches",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 1,
      "position": [
        680,
        320
      ],
      "executeOnce": false
    },
    {
      "parameters": {
        "functionCode": "var lastItem = $evaluateExpression('{{$node[\"SplitInBatches\"].context[\"noItemsLeft\"]}}');\nconsole.log(\"lastItem:\",lastItem);\nconsole.log(\"current index:\", $evaluateExpression('{{$node[\"SplitInBatches\"].context[\"currentRunIndex\"]}}'));\n// currentRunIndex\n\nreturn items;"
      },
      "name": "Function",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [960, 320]
    }
    
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Function1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Function1": {
      "main": [
        [
          {
            "node": "SplitInBatches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "SplitInBatches": {
      "main": [
        [
          {
            "node": "Function",
            "type": "main",
            "index": 0
          },
          {
            "node": "SplitInBatches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "id": 9
}
```

**Expected behavior**
The order of connections should not matter (ever, i suppose, since the behavior is not described as a feature)

**Environment (please complete the following information):**
 - OS: Ubuntu 21.10
 - n8n Version: 0.165.1
 - Node.js Version: v14.15.5
 - Database system: Postgres
 - Operation mode: main

**Comment by Joffcom** [comment] 2023-06-14 11:21
Hey @ebunders,

I am just catching up on some older issues, It looks like I didn't get much further than applying the issue label on this one. The connection order of the nodes is something that has mattered for a while but it depends on what you are doing as to if it causes an issue.

I suspect this is going to be an execution order issue which is going to change a bit in v1.0 but for the actual issue in this the new version of the split in batches node may help here.

**Comment by ebunders** [comment] 2023-06-18 06:40
Hey Joffcom
It seems to me that the whole point of low-code environments is to allow developers to express functionality on a higher level and declarative. Implementation details are abstracted over and should be unimportant to the developer. Having to know that the order of connection has an effect implies that you have to know about the implementation details. This is a case of leaky abstraction.
I just don't think you want that in a low-code environment like n8n

**Comment by Joffcom** [comment] 2023-06-18 07:20
Hey @ebunders,

I suspect that is part of why it is being changed a bit in 1.0 as it can cause confusion.

There is also a v2 of the split in batches node that also makes the process easier as it provides a done branch to make things easier for most users.

The change in 1.0 that might change this is here: https://docs.n8n.io/1-0-preview/#change-node-execution-order I will give it a test tomorrow when I start to see if it is fixed or needs to be looked at again.

**Comment by Joffcom** [comment] 2024-01-04 10:30
Hey @ebunders,

Testing this in the latest n8n results in the output of both workflows being the same depending on the execution mode being set for the workflow (legacy / v1) although even in legacy the output is still the same now so I suspect this has changed from v1 as expected.

For now I am going to close this and if you are still able to reproduce this from v1 with the newer nodes let me know and we can open it again.

**Closed by Joffcom** 2024-01-04 10:30 UTC
Labels: node/issue
