### ISSUE TITLE
Simple Sort doesn't work for numbers

### ISSUE THREAD

**Issue by Chinoman10** [n8n-io/n8n#3744] opened 2022-07-20 15:46 UTC
_Found a bug? Please fill out the sections below. 👍_

### Issue Summary

Using the **ItemsList** node, the **Operation** "Sort" and choosing the **Type** "Simple", and giving it a number field, it's not properly sorted.

### Steps to Reproduce

1. Provide any input to the ItemsList node with numbers mixed randomly (with different numbers of digits);
2. Check output;

_Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?_
I expect it to sort the numbers Ascending or Descending as the UI suggests that it does.

### Technical details

- Running version: **0.186.1**

**Comment by Chinoman10** [comment] 2022-07-20 15:46
Here's a screenshot:
![image](https://user-images.githubusercontent.com/8300763/180026151-1c593475-b553-4c9b-b8eb-77f21d0cc681.png)

**Comment by Joffcom** [comment] 2023-01-18 16:03
Hey @Chinoman10,

I have just been looking at this one and I can see the issue you are having and was able to reproduce it but I wouldn't classify it as a bug, Looking at the data you have in the node the amounts are strings not numbers so the data is being sorted as a string. If you were to take the same values and run them through a set node or code first to convert them to numbers it works as expected.

This of course is not great but hopefully shows a bit of insight as to what is happening, What I have done is added this to our internal product ideas list as it would be a great feature to automatically convert the data type or at least provide an option so you can decide if we convert it or not.

For now I am going to mark this one as closed as while it is annoying for the reasons above it isn't really a bug, If you have any questions let me know.

**Closed by Joffcom** 2023-01-18 16:03 UTC
Labels: node/issue
