### ISSUE TITLE
n8n import with fixed ID

### ISSUE THREAD

**Issue by rfehling-mittwald** [n8n-io/n8n#2527] opened 2021-12-06 13:56 UTC
**Describe the bug**
We have a PROD and a DEV context. We have a lot of different gitlab repositories which import a whole folder via gitlab ci:
`n8n import:workflow --separate --input=./assets/processes`

This works fine in our dev, because we are creating the workflows in our dev n8n site and export them into our gitlab repository.
But we have a problem in our prod context. If there is a gap between the ids (dev latest id: 62, prod latest id: 20) and we want to import workflow 60, prod will import the workflow with the id 21 (instead of 60). And if you want deploy it again, id 60 still does not exists in prod, so he creating the workflow again with id 22 and then get an duplicate key error, because name already exists :D

It seems that import only overwrite existing ids, else autoincrement. 
I guess it's because you don't want to mess up the autoincrement value of the database engine.

**To Reproduce**
- Export latest workflow (example ID: 10)
- Change ID to 20 and change name
- import workflow and get ID 11 :(

**Expected behavior**
The imported workflow should keep the id, not an autoincremended value.

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- n8n 0.151.0
- PostgreSQL

**Comment by krynble** [comment] 2021-12-08 12:47
Hey @rfehling-mittwald

Thank you for reporting that. Oddly enough, the intended behavior is exactly as you expected - it seems like postgres is forcing the ID back to auto increment number.

I just tested this using Postgresql and actually we have internal tools that use this import and they work just fine (with holes in between IDs) when using default database (sqlite).

I'll investigate this real quickly and reply back to you.

**Comment by krynble** [comment] 2021-12-08 14:02
Hum well actually it turns out this is not exactly a problem on n8n.

The way Postgres handles auto increment columns is very strict, unlike MySQL.

For both MySQL and SQLite you can insert a row with a higher auto increment ID and it will update the internal counter accordingly, but this doesn't happen for postgres, causing a future insertion to eventually fail due to collision.

So we have a few problems that cannot be changed now without creating big breaking changes. Possibilities:
- Change Postgres' implementation to not use auto increment and use something else instead
- Tons of hacks to actually change the table schema, deactivate auto increment, insert row, update auto increment value and reactivate it

This is a reported issue present in the tool we use for database connection TypeORM. You can see more about this issue here: https://github.com/typeorm/typeorm/issues/2215

Unfortunately this is not something we can change anytime soon, therefore I'd suggest you using MySQL if that's possible for this scenario.

I'll be closing this issue for now but please feel free to reopen and/or add more context if needed.

**Closed by krynble** 2021-12-08 14:02 UTC

**Comment by Korayem** [comment] 2022-10-02 09:22
After importing in database, run a similar function depending on the table:

`SELECT setval('credentials_entity_id_seq', (SELECT MAX(id) from "credentials_entity"));`

Source: https://stackoverflow.com/a/9108929/80434

**Comment by janober** [comment] 2023-01-27 16:20
Fix got released with `n8n@0.213.0`

**Comment by createreadupdate** [comment] 2024-07-19 17:44
I have solved it like this

INSERT INTO profession (id, name)
VALUES ((SELECT COALESCE(MAX(id), 0) + 1 FROM profession), $1);

$1:  {{ $json.name }}
