### ISSUE TITLE
Strange behavior of self-hosted version

### ISSUE THREAD

**Issue by amorev** [n8n-io/n8n#595] opened 2020-05-26 08:08 UTC
**Describe the bug**
* I can open n8n interface only in Google Chrome anonymous mode
* I cannot make REST request to my workflow because of CORS

**To Reproduce**
I used docker for initialize application
1. Try to open http://s3.obvu.ru:5678/ in non anonymous mode and it will not work
2. Now try to open it in anonymous mode - it will open
3. I created simple workflow - http://s3.obvu.ru:5678/webhook/5/webhook/test. It works if open it as a page
4. Trying to make fetch (`fetch('http://s3.obvu.ru:5678/webhook/5/webhook/test')`) causing me error
![image](https://user-images.githubusercontent.com/8593411/82876113-f2e46880-9f40-11ea-85e8-1f50ec3edbd0.png)

**Expected behavior**
I expected that I'll be able to use it in simple google chrome tab and use it as rest api for simple frontend

**Environment (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - n8n Version - 0.67.3
 - Node.js Version 12.16.3

**Comment by janober** [comment] 2020-05-26 21:51
Thanks a lot @amorev for reporting this issues.

**I can open n8n interface only in Google Chrome anonymous mode**
Did you try to delete all cookies and cache? Because I did never hear of that problem and can currently not think of a reason why it would do that. 

**I cannot make REST request to my workflow because of CORS**
Here it seems more like regular browser behavior is the issue. If you make the request "normally" by opening it in a new tab it works. Also if you try via curl:
```bash
curl http://s3.obvu.ru:5678/webhook/5/webhook/test
```
It would also work if you are on the same domain. So if you visit `http://s3.obvu.ru:5678/webhook/5/webhook/test` and then run 
`fetch('http://s3.obvu.ru:5678/webhook/5/webhook/test')` in the console it will also work. 

If you want to call it in the browser from a different domain (and or port) you should be able to do that by adding a response header like `Access-Control-Allow-Origin: *` to make it work from everywhere if you need that for some reason. Similar to what it does when developing n8n:
https://github.com/n8n-io/n8n/blob/master/packages/cli/src/Server.ts#L286

Hope that helps!

**Comment by amorev** [comment] 2020-05-28 10:23
Server of n8n always returns access-control-allow-origin: http://localhost:8080 inspite of what I wrote in webhook configuration

![image](https://user-images.githubusercontent.com/8593411/83130040-5cea4280-a0e6-11ea-883e-0b664e4e1374.png)


![image](https://user-images.githubusercontent.com/8593411/83130054-62478d00-a0e6-11ea-9a7e-919300b736f9.png)

**Comment by amorev** [comment] 2020-05-28 10:29
![image](https://user-images.githubusercontent.com/8593411/83130526-1e08bc80-a0e7-11ea-882a-7f04cabf8514.png)
Even in production mode I see such a problem.

And thank you for your replies:) Problem with anonymous mode solve by turninf off fri-gate extenstion

**Comment by janober** [comment] 2020-05-28 23:34
Very strange. I just tested it and it works totally fine for me.

So if I use this node:
```json
{
  "nodes": [
    {
      "parameters": {
        "path": "webhook",
        "responseMode": "lastNode",
        "options": {
          "responseHeaders": {
            "entries": [
              {
                "name": "Access-Control-Allow-Origin",
                "value": "http://example.com:1234"
              }
            ]
          }
        }
      },
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 1,
      "position": [
        507,
        295
      ]
    }
  ],
  "connections": {}
}
```

It displays this to me in Chrome:
![Screenshot from 2020-05-29 01-31-16](https://user-images.githubusercontent.com/6249596/83204526-5abacf00-a14c-11ea-885c-088b9d910250.png)

**Comment by amorev** [comment] 2020-05-29 11:33
There is no problem with POST request. It shows * as allow origin.

But if I make OPTIONS request I'll receive this:
![image](https://user-images.githubusercontent.com/8593411/83255527-482aaf00-a1b9-11ea-80f5-ceae0a858634.png)

Google Chrome makes Options request before making post and if origin is not allowed, post will not be made(

**Comment by janober** [comment] 2020-05-30 22:12
Ah sorry totally overlooked that you make an OPTIONS request. Yes, this one is currently not supported by n8n. That is why you also get the "404 Not Found". If you define a Webhook for POST it will only listen to POST requests and not for anything else like GET, OPTIONS, ...

Honestly not sure right now what a good fix for this could be... Probably have to think about that a little bit.

**Comment by amorev** [comment] 2020-05-31 04:54
Thanks for your reply!

**Comment by amorev** [comment] 2020-05-31 04:55
I think I now how to fix it. I'll try to upgrade Webhook module locally and make PR if I success)

**Comment by janober** [comment] 2020-05-31 08:43
Great, thanks a lot!

The problem is, however, less of a technical one more of a design one and to think about if it makes sense in the long term and future use cases. Looking forward to your solution!

**Comment by Rupenieks** [comment] 2020-07-21 13:59
Hi @amorev ,

Could you try setting your NODE_ENV environment variable to production? 
Reference on n8n environment variables: https://docs.n8n.io/reference/configuration.html#publish

The "localhost:8080" value is hardcoded to the Access-Control-Allow-Origin header when n8n is not in production in order to deal with a CORS issue between the backend and frontend.

**Comment by iranika** [comment] 2020-08-12 14:07
Hi guys,
I used Nginx for this problem. I share the config for you :)

```/etc/nginx/conf.d/example.com.conf
server {
    listen 80;
    server_name example.com;
    proxy_set_header    Host    $host;
    proxy_set_header    X-Real-IP   $remote_addr;
    proxy_set_header    X-Forwarded-Host    $host;
    proxy_set_header    X-Forwarded-Server  $host;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "POST, GET, OPTIONS";
        add_header Access-Control-Allow-Headers "Origin, Authorization, Accept";
        add_header Access-Control-Allow-Credentials true;
        proxy_pass http://localhost:5678;
    }
}
```

thanks!

**Comment by RicardoE105** [comment] 2020-08-26 00:38
Thanks for sharing @iranika. @amorev could you figure it out?

**Comment by SantoshSrinivas79** [comment] 2020-09-06 01:59
A combination of nginx config and NODE_ENV setting (both as mentioned above) worked for me on a self-hosted server!

**Comment by krynble** [comment] 2021-02-05 11:55
Closing this issue for now as a solution was posted. Feel free to reopen or make a new issue if you encounter any other problems.

**Closed by krynble** 2021-02-05 11:55 UTC

**Comment by rohanrajpal** [comment] 2022-05-10 17:20
Hey, I'm using railway.app to self host n8n. Is there no way to fix this without a nginx config change? Since I cant do that in railway.app

**Comment by dobromyslov** [comment] 2023-02-26 15:43
> ```
> server {
>     ...
>     location / {
>         add_header Access-Control-Allow-Origin *;
>         add_header Access-Control-Allow-Methods "POST, GET, OPTIONS";
>         add_header Access-Control-Allow-Headers "Origin, Authorization, Accept";
>         add_header Access-Control-Allow-Credentials true;
>         proxy_pass http://localhost:5678;
>     }
> }
> ```

This no longer works because n8n already sends `Access-Control-Allow-Origin *;`.
https://github.com/n8n-io/n8n/blob/40a934bbb4f6eed80aa5c1de6814c0e0eea65ebd/packages/cli/src/AbstractServer.ts#L271

You need to remove that line from the config and add extra headers to `Access-Control-Allow-Headers`:
```
location / {
  add_header Access-Control-Allow-Methods "POST, GET, OPTIONS";
  add_header Access-Control-Allow-Headers "Origin, Authorization, Accept, Content-Type, X-Requested-With";
  add_header Access-Control-Allow-Credentials true;
  proxy_pass http://localhost:5678;
}
```

At the same time, n8n provides full CORS support using middleware. [Cors middleware](https://github.com/n8n-io/n8n/blob/a115baa1ac2af84c462be48cbc575d7905f74f64/packages/cli/src/middlewares/cors.ts) is loaded only when your webhook runs in the development mode:
https://github.com/n8n-io/n8n/blob/40a934bbb4f6eed80aa5c1de6814c0e0eea65ebd/packages/cli/src/AbstractServer.ts#L154

@netroy It looks like thorough refactoring and implementing custom CORS options in the WebHook trigger are still needed.
