### ISSUE TITLE
Telegram Message Send Parse Error

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#5675] opened 2023-03-11 14:34 UTC
**Describe the bug**
When having a Telegram Node to send a Message and having Parse Mode Markdown activated I get the following error:
```
ERROR: Bad request - please check your parameters
Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 176
```
My input is very different every time, so it cannot be generalized.

**To Reproduce**

Make a workflow with a Telegram node so send various messages formatted in Markdown

**Expected behavior**
Ramdomly the Telegram node throughs the mentioned error.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.218.0
- Database system postgres
- Operation mode queue

**It would be really nice if the Telegeram node, would ignore potential bugs like this and just send the message**

**Comment by Joffcom** [comment] 2023-03-11 15:15
Hey @prononext 

It would be very handy if you had an example workflow that sends a message that fails every time.

It could be that there is something in the data being sent, Telegram is doing something odd or content we might not be expecting.

**Comment by prononext** [comment] 2023-03-11 18:19
Hi @Joffcom, 

here a workflow that throws the error and one that works. 
The problem is on the Telegram node side, as it is requesting 100% markdown to execute which not always can be true.

<details>
 <summary>Sample with Error</summary>
 
```

{
  },
  "nodes": [
    {
      "parameters": {
        "jsCode": "return[\n  {\n    \"message\": \"This is a test with error: \\n\\n```testcode```\\n\\n `STOP\"\n  }\n]"
      },
      "id": "6bb1db4e-77b4-489a-b813-0fc5437894f0",
      "name": "Input Error",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        -1540,
        440
      ]
    },
    {
      "parameters": {
        "text": "={{ $json.message }}",
        "additionalFields": {
          "parse_mode": "Markdown"
        }
      },
      "id": "679fcea7-28ec-4a1c-bf38-7d185fc3ae91",
      "name": "Send Message Fails",
      "type": "n8n-nodes-base.telegram",
      "typeVersion": 1,
      "position": [
        -1360,
        440
      ]
    }
  ],
  "connections": {
    "Input Error": {
      "main": [
        [
          {
            "node": "Send Message Fails",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

</details>

<details>
 <summary>Sample Working</summary>

```
{
  "nodes": [
    {
      "parameters": {
        "jsCode": "return[\n  {\n    \"message\": \"This is a test with error: \\n\\n```testcode```\\n\\n `STOP`\"\n  }\n]"
      },
      "id": "96b2dfc4-21c3-4678-9f7d-0b0bb618081e",
      "name": "Input Working",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        -1540,
        640
      ]
    },
    {
      "parameters": {
        "text": "={{ $json.message }}",
        "additionalFields": {
          "parse_mode": "Markdown"
        }
      },
      "id": "3036a1b5-12c7-47d8-aff7-a4675f48af63",
      "name": "Send message Success",
      "type": "n8n-nodes-base.telegram",
      "typeVersion": 1,
      "position": [
        -1360,
        640
      ]
    }
  ],
  "connections": {
    "Input Working": {
      "main": [
        [
          {
            "node": "Send message Success",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```
</details>

Also setting continue on fail, does not solve the problem.

**Comment by Joffcom** [comment] 2023-03-11 19:09
Hey @prononext 

Perfect I will check this out on Monday, from what I remember setting the Markdown parse mode doesn't have a partial option we just fire off the request to Telegram and include the option the api asks for.

I will let you know what I find.

**Comment by Joffcom** [comment] 2023-03-13 13:56
Hey @prononext,

So I have taken a proper look at this and it is Telegram returning the error message, I have done a quick update to include the newer `MarkdownV2` option but that doesn't change anything.

I don't believe this to be a bug with n8n or with Telegram as I would expect an invalid input to fail. Let me know what your thoughts are on this one and what you would like to do.

**Comment by ps428** [comment] 2023-04-30 13:58
Hi,

I am a newbie here and want to help around.

I faced a similar problem in one of my other project where I was trying to send a custom encrypted string to FastAPI back-end but that string could not be parsed properly and was throwing errors.

## My solution
I used array of integers encoding the string in ASCII instead of passing a raw string. 

### Example
Code (Markdown):

----
x# Header 1
x'x'x
int a = 42;
cout<<a;
x'x'x'
----


**PS: I have used 'x' to escape out the markdown for this particular example, you must replace the 'x' in the above example with '' and see the exact values.**

This whole string was passed in an array of ASCII coded integers like this:
```
ASCII encoded array: [35, 32, 72, 101, 97, 100, 101, 114, 32, 49, 10, 39, 39, 39, 10, 105, 110, 116, 32, 97, 32, 61, 32, 52, 50, 59, 10, 99, 111, 117, 116, 60, 60, 97, 59, 10, 96, 96, 96, 10, 35, 35, 32, 84, 104, 105, 115, 32, 105, 115, 32, 104, 111, 119, 32, 121, 111, 117, 32, 99, 97, 110, 32, 112, 114, 105, 110, 116, 32, 97, 110, 32, 105, 110, 116, 101, 103, 101, 114, 32, 105, 110, 32, 67, 43, 43, 46 ]
```
Now one can simply send in this array and perform basic ASCII decoding for the desired results. You just have to traverse over this array and convert each integer to the corresponding ASCII value. 

## Concluding point
I hope this workaround would be able to sort out this issue. Also I would be very happy to be make the changes in code and contribute.

Cheers!

**Comment by Joffcom** [comment] 2023-04-30 16:59
Hey @ps428 

That is an interesting thought but the problem is the markdown being used is invalid which I would expect to cause an error.

**Comment by ps428** [comment] 2023-04-30 17:07
Hi @Joffcom 

Thank you very much for your kind response. I'm glad to hear that there isn't much change needed for this issue. I will continue to work on resolving more issues.

Let's work together to solve some problems...

Best Regards,
Pranav

**Comment by Joffcom** [comment] 2023-06-15 11:54
Hey @prononext,

I am going to mark this as solved for now as the error is coming back from Telegram as the markdown is invalid so this is kind of expected at the moment.

**Closed by Joffcom** 2023-06-15 11:54 UTC
