### ISSUE TITLE
I have If node take action both of true and false branch

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#948] opened 2020-09-12 11:41 UTC
Hi,

I meet a case of If node take both of true and false branch

![n8n-⚠️-Cmd-contact-Message-receive](https://user-images.githubusercontent.com/1112881/92994783-7b563b80-f527-11ea-8110-9b97f3da6fb8.png)

**Comment by cmdntd** [comment] 2020-09-12 14:22
Perhaps "Always Output Data" option of next node from if node cause this...

**Comment by janober** [comment] 2020-09-12 14:37
Ah yes exactly that is sadly a known bug that still has to get fixed. A temporary workaround is to add another node in-between (like a NoOp) one.

**Comment by janober** [comment] 2020-09-12 19:42
Had a look and just pushed a fix. Will be released with the next version.

**Closed by janober** 2020-09-12 19:42 UTC

**Comment by janober** [comment] 2020-09-14 13:33
Got released with n8n@0.82.0

**Comment by enisozgen** [comment] 2021-04-25 13:18
![image](https://user-images.githubusercontent.com/5619924/115994897-358f4480-a5d9-11eb-9580-5e6f7ae59668.png)

Using Version: 0.117.0 this issue exist in this version

**Comment by harrycheng1** [comment] 2021-08-17 07:54
same issue on 0.111.0. add a dummy IF block after the "true" path as workaround

**Comment by janober** [comment] 2021-08-17 08:18
Can you please share an example workflow @harrycheng1 we can then have a look.

**Comment by harrycheng1** [comment] 2021-08-17 08:53
About n8n
n8n Version:0.111.0
It's hosted on a k8s cluster with image "n8nio/n8n"

IF block will check webhook query parameter, and it goes to both path.

![image](https://user-images.githubusercontent.com/40796623/129694372-9289f3f8-4b62-4fd3-976c-92c24725b08f.png)

with workaround, it goes to "false" path

![image](https://user-images.githubusercontent.com/40796623/129694655-d130457b-8199-4581-afcb-ab8b70f34fce.png)

**Comment by janober** [comment] 2021-08-17 10:01
Thanks. Can you upgrade to the latest version `0.134.0` there it should work fine.

**Comment by harrycheng1** [comment] 2021-08-17 11:16
0.134.0 works fine now!
thank you

![image](https://user-images.githubusercontent.com/40796623/129716761-4f857a41-29d9-4a50-967f-c8f240ffdcf8.png)

**Comment by vincentwinkel** [comment] 2021-11-19 13:18
Hi, version 0.136.0 here and same issue...
Here are several scenarii:
<img width="368" alt="Screenshot 2021-11-19 at 14 11 16" src="https://user-images.githubusercontent.com/1402505/142628714-9f287b15-f5c0-4512-87ad-10fd415233b6.png">
<img width="399" alt="Screenshot 2021-11-19 at 14 10 36" src="https://user-images.githubusercontent.com/1402505/142628702-f84ac586-5571-4fb0-8e4b-10b78aeeda5b.png">

This scenario sometimes works, sometimes doesnt:
<img width="387" alt="Screenshot 2021-11-19 at 14 12 50" src="https://user-images.githubusercontent.com/1402505/142628707-ee3c3651-a716-4bcd-8331-6b07909dca8d.png">
<img width="376" alt="Screenshot 2021-11-19 at 14 11 35" src="https://user-images.githubusercontent.com/1402505/142628708-70b45536-15d6-456e-93c4-acf2e865644d.png">
I feel it depends how I start the flow (I wanna choose between the webhook of my mock for tests, changing the merge as PassThrough or mergeByIndex seems having an impact on the following if):
<img width="781" alt="Screenshot 2021-11-19 at 14 16 09" src="https://user-images.githubusercontent.com/1402505/142629139-af9debec-7885-4229-ad04-cc9e0038a817.png">

I unfortunately cannot send the whole workflow for copyright purpose.

**Comment by janober** [comment] 2021-11-19 13:51
Generally looks all as expected to me.

For example:
- if a node fails (unless "continue on error" is set) does the workflow stop executing
- if a Merge-Node does not have any data on the first input, then it does not execute

Unless I overlooked something (as I obviously do not have the data or know what data does get send to which output) does it seem to cover all your above workflows.

**Comment by vincentwinkel** [comment] 2021-11-20 08:20
@janober I agree for the Merge, that's why I replaced by a Function `returns items;` (I use this node only for a propre naming that I can use later in some expressions). But I don't understand why the same(?) flow works in another workflow, as you can see (I compared the node settings etc, and everything is strictly the same, the only difference is that the working workflow start only with a webhook, I start with a Merge between the webhook and a Mock as you can see in my previous message):
<img width="839" alt="Screenshot 2021-11-20 at 09 18 26" src="https://user-images.githubusercontent.com/1402505/142719619-ea7411c3-120d-435b-a0e5-0a29ee3ddb10.png">

I'm not sure to understand your other answers. You consider it's normal to pass through `true` and `false` at the same time? Did I miss something?

**Comment by vincentwinkel** [comment] 2021-11-22 09:20
@janober I unfortunately need to fix it before tomorrow. Do you have any idea..?

**Comment by janober** [comment] 2021-11-22 09:25
Please create a simple workflow that displays exactly the same problem you are facing and post it here. We can then have a look.

**Comment by vincentwinkel** [comment] 2021-11-22 10:07
I'm sorry, my deadline being tomorrow, I need to rush and because I use an internal n8n platform I cannot share it.
I'm comparing the workflow that doesn't with the working one, replacing nodes one by one, as follow (top: doesn't work as shown on my previous posts, bottom: working nodes):
<img width="382" alt="Screenshot 2021-11-22 at 10 51 14" src="https://user-images.githubusercontent.com/1402505/142840138-a483f75f-9590-4b32-ad04-5fceaa246b08.png">

After exporting the json config, I notice 2 differences between the 2 nodes Eloqua (left: working, right: not working) as follow:
<img width="1331" alt="Screenshot 2021-11-22 at 10 56 17" src="https://user-images.githubusercontent.com/1402505/142840590-ba3f2241-d26b-4c5f-8f7e-3255bcf38168.png">
1. different naming from `$node.name` and `4node["name"]` (I really hope it's not a problem)
2. the non-working node has a `customFields` property set, which is not visible on the interface:
![Screenshot 2021-11-22 at 10 58 47](https://user-images.githubusercontent.com/1402505/142841100-b6f5eac8-aaa7-4e81-bf6e-043e7f6626a3.png)
I tried to replace by new nodes without config, but same problem...

@janober may I share my internal n8n url with you if you wanna have aa look?

**Comment by vincentwinkel** [comment] 2021-11-22 10:38
My bad... I just notice the working workflow actually sends the 2 Eloqua nodes in the input1 of the Merge node...

**Comment by janober** [comment] 2021-11-22 11:08
Sorry, can you simply build a very minimal workflow that demonstrates the issue (by mocking the data with Set or Function-Nodes) and then post it here (so the JSON of that workflow).

**Comment by vincentwinkel** [comment] 2021-11-22 11:44
@janober I tried but I cant, because we use an overridden private Eloqua node using internal credentials. But I can give you the url of my workflow in private and you can have a look. I just need your email address (or whatever to contact you in private).
But after more investigation, I think the issue comes from a loop using `array[0]` for every iteration instead of the current node value. If so, I will remove my comments not to pollute the thread.

**Comment by vincentwinkel** [comment] 2021-11-26 12:22
Actually, the issue is still here on v0.150.
Here, the CObject doesn't exist, so it goes to the `false` branch, which is correct. So why is it running then the `if` branch?
<img width="661" alt="Screenshot 2021-11-26 at 13 20 12" src="https://user-images.githubusercontent.com/1402505/143580268-6e89726c-0f42-40da-9afe-12ddd11ba3e4.png">

**Comment by vincentwinkel** [comment] 2021-11-26 12:33
Actually, the issue is still here on v0.150.
Here, the CObject doesn't exist, so it goes to the false branch, which is correct. So why is it running then the if branch?
<img width="661" alt="Screenshot 2021-11-26 at 13 20 12" src="https://user-images.githubusercontent.com/1402505/143581666-26892ef6-1aed-4534-8c1b-4407159be1d1.png">

The opposite case works well, tho.
<img width="646" alt="Screenshot 2021-11-26 at 13 23 32" src="https://user-images.githubusercontent.com/1402505/143581685-307ff5fe-07fa-411a-a563-cf0f8aebde7d.png">

Error that I cannot reproduce on a minimalistic workflow.
<img width="810" alt="Screenshot 2021-11-26 at 13 30 05" src="https://user-images.githubusercontent.com/1402505/143581713-6e7538d0-2f58-4c54-8606-7e6733e54cc2.png">

**Comment by janober** [comment] 2021-11-26 22:43
Very sorry is simply impossible to debug like this. We need a workflow we can run and where we can see that problem. But generally is it very strange that nobody else seems to have that problem esp. considering that the part of the n8n code which could cause such behaviour did not get touched for a very long time. Meaning the problem would then already exist for a very long time.

So please provide us a workflow we can run, we will then have a look and fix asap.

**Comment by quansenB** [comment] 2021-11-29 15:31
Hi @vincentwinkel,

I'm the developer, who developed the Eloqua node. 

From first sight it seems that the workflow is executed multiple times, so it would be possible that the true and false routes are both executed. 

As far as I know a node can also not execute itself and can only be started from the outside.

Of course there is a chance that there is an edge case in the node. I cannot reproduce it myself, so unfortunately you'd need to share a workflow before I could start looking at it.
