### ISSUE TITLE
GMail Trigger occasionally misses emails

### ISSUE THREAD

**Issue by mark-monteiro** [n8n-io/n8n#4272] opened 2022-10-05 13:17 UTC
**Describe the bug**
The new GMail trigger is not guaranteed to fire for all matching emails

**To Reproduce**

1. Set up the GMail trigger in a workflow
2. Receive multiple emails at the same time that match the trigger filters
3. Occasionally some of the emails received will not be included in the trigger

I'm not sure if there is actually a requirements for multiple  emails to arrive at the same time for this bug to occur. It might just be an edge case that can occur even for a single email, but my use case is that I receive batches of emails at the same time.

**Expected behavior**
The trigger should fire for every matching email received

**Environment (please complete the following information):**

- OS: Docker Image (Ubuntu host)
- n8n Version: 0.195.5
- Node.js Version: Docker image version
- Database system: PostgreSQL
- Operation mode: own

**Additional context**
Here is an example of some messages that were missed that I received this morning:
- I received 14 emails in total within a few seconds of each other
- The workflow was triggered twice
  - once at `2022-10-05 05:01:40` that processed 3 emails
  - and again at `2022-10-05 05:02:41` that processed 6 emails
- 5 emails were not processed

The email messages returned from the GMail API include an [`internal_date`](https://developers.google.com/gmail/api/reference/rest/v1/users.messages#Message.FIELDS.internal_date) field. I collected that timestamp for each of the emails in this batch and have included them below. You'll notice that the emails that were not processed were received in a small window of time between the two batches that were processed.

```jsonc
// First execution: 2022-10-05T05:01:40.763Z / 1664946100763
"internalDate": "1664946090000",
"internalDate": "1664946091000",
"internalDate": "1664946093000",

// Unmatched emails
"internalDate": "1664946095000"
"internalDate": "1664946095000"
"internalDate": "1664946095000"
"internalDate": "1664946095000"
"internalDate": "1664946096000"

// Second execution: 2022-10-05T05:02:41.127Z / 1664946161127
"internalDate": "1664946098000",
"internalDate": "1664946099000",
"internalDate": "1664946101000",
"internalDate": "1664946102000",
"internalDate": "1664946109000",
"internalDate": "1664946135000",
```

**Comment by Joffcom** [comment] 2022-10-07 13:45
Hi @mark-monteiro,

Thanks for reporting this one, Looking at the node we set the end date to the time the workflow starts then we pull the emails 🤔 

I will have a play with this one and see if I can reproduce the issue and get a fix put in place for it. I have created an internal ticket for this one which we will be tracking as N8N-4919

**Comment by Joffcom** [comment] 2023-01-19 12:04
Hey @mark-monteiro,

It looks like the notification was missed for this one, The fix for this was released with n8n@0.206.1. For now I am going to mark this one as closed and if you run into the issue again let me know and we can re-open this.

**Closed by Joffcom** 2023-01-19 12:04 UTC
Labels: node/issue

**Comment by mark-monteiro** [comment] 2023-02-06 20:48
@Joffcom This was never fixed for me, I still occasionally get missed emails from the GMail trigger. I can confirm this did just happen to me last weekend (was running 0.211.2 at the time). I do think the frequency of this occurring has been reduced though. 

I don't have any additional information I can provide at the moment, but the next time this happens I will try to collect some logs and provide some more details on what happened.

**Comment by Joffcom** [comment] 2023-02-06 21:19
Hey @mark-monteiro 

No worries, we thought it was resolved but if you can grab some log times we can open it again and look to see what we might have missed.

**Comment by paulwer** [comment] 2023-02-14 12:02
@Joffcom 
in my case the node fires the workflow every poll with the same email. 
So I disabled the workflow for now.
Is there an option to prevent this behavior? Can you reproduce this?

**Comment by mark-monteiro** [comment] 2023-03-21 15:25
@Joffcom The frequency of this happening seems to have definitely decreased, but this did happen again in my workflow today

Here are the [internal_date](https://developers.google.com/gmail/api/reference/rest/v1/users.messages#Message.FIELDS.internal_date) timestamps of the relevant messages again. There were three workflow executions in quick succession that processed a handful of email, but one email was missed and not processed.

```js
// First workflow execution
1679375811000
1679375811000
1679375813000
1679375814000 // <-- This timestamp matches the message that was not processed
1679375814000
1679375818000
1679375818000
1679375821000
1679375823000

// Second workflow execution
1679375825000
1679375826000
1679375837000

// Third workflow execution
1679375890000
1679375931000

// This is the timestamp of the message that was not processed
1679375814000
```

**Comment by mark-monteiro** [comment] 2023-03-21 20:11
@Joffcom Yes, I am using the default polling option (every minute).

I'm not super familiar with exactly how the GMail node is implemented in n8n, but I have an idea of why this might happen. If I am assuming correctly, I would guess that n8n queries the GMail API for messages, then records the latest timestamp of any messages retrieved. Then on the next query, that timestamp can be used to only fetch emails newer than the saved timestamp. 

This approach, if used, assumes that all emails older than the saved timestamp have already been retrieved. I would guess that this is not guaranteed by the GMail API, which is why this is happening.

Take for example, the 15 emails received at nearly the same time in my example above. The first workflow execution fetches 9 of them, but misses one email with a timestamp in the middle of that range. I don't know why the GMail API would do this, but perhaps when receiving multiple emails all at the same time, it takes a few moments for the emails to all be processed internally on GMail's end before they can be returned in the API call (and messages aren't necessarily processed in-order). If this is the case it would explain why this issue is so intermittent; multiple emails need to be received at the same time in GMail, and n8n also has to query the API at nearly the same time when not all of them have been processed yet.

I'm not sure what the best way to handle this would be. One solution would to add some arbitrary overlap of the timestamp filter between queries (say 30 seconds?) and then filter out any duplicates.
