### ISSUE TITLE
oauth2-credentials unauthorized

### ISSUE THREAD

**Issue by enoksaju** [n8n-io/n8n#9151] opened 2024-04-17 07:54 UTC
### Bug Description

i try to connect to with google apis, but when i confirm the callback return this json

{"status":"error", "message": "Unauthorized"}

the url is:

/rest/oauth2-credential/callback?

### To Reproduce

1. Add new Google Api Credential
2. try to connect
3. when confirm auth, this json is showed

### Expected behavior

a valid update on credentials

### Operating System

Ubuntu 20.04

### n8n Version

next

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-04-17 07:56
Hey @enoksaju,

Do you have the correct url set in the Google application?

Can you also confirm the exact version of n8n you are using as next is a tag and changes.

**Comment by enoksaju** [comment] 2024-04-17 07:59
_Do you have the correct url set in the Google application?_

**yes, this worked before latest update**

**the version is 1.37.1**

![image](https://github.com/n8n-io/n8n/assets/27732523/cae82eca-ae4a-4d1b-8501-b816a878f401)

**Comment by netroy** [comment] 2024-04-17 08:02
@enoksaju can you also please share the version this was earlier working on? That might help narrow down the change that might be causing this issue.

**Comment by enoksaju** [comment] 2024-04-17 08:06
> @enoksaju can you also please share the version this was earlier working on? That might help narrow down the change that might be causing this issue.

working version 1.34.2

i try to pull docker compose to that version, but when access to credentials endpoint this not load nothing and on console show a errors

**Comment by enoksaju** [comment] 2024-04-17 08:07
also, important thing, after json error is showed, all page not workign and when i reload page this show login page and i need to login again

**Comment by enoksaju** [comment] 2024-04-17 08:10
i read abouth this:  https://github.com/n8n-io/n8n/issues/9031#issuecomment-2034450689, maybe this cause the issue

#9031

**Comment by netroy** [comment] 2024-04-17 08:19
> when i reload page this show login page and i need to login again

This is likely being caused by https://github.com/n8n-io/n8n/pull/9057
Are you by any chance using Firefox with the multi-account containers extension?

The login screen is showing because somewhere in the auth flow a rest-api call is being made from a context that does not have the correct permission to make this api call, so the cookie is getting invalidated.

Unfortunately I'm unable to reproduce this locally, or on n8n cloud, with Firefox or Chrome.

**Comment by enoksaju** [comment] 2024-04-17 08:52
> > when i reload page this show login page and i need to login again
> 
> This is likely being caused by #9057 Are you by any chance using Firefox with the multi-account containers extension?
> 
> The login screen is showing because somewhere in the auth flow a rest-api call is being made from a context that does not have the correct permission to make this api call, so the cookie is getting invalidated.
> 
> Unfortunately I'm unable to reproduce this locally, or on n8n cloud, with Firefox or Chrome.




Maybe, i think issue is with browserid and nodesAccess property, was removed on new versions

**Comment by hermanekt** [comment] 2024-04-17 15:34
Same problem on version 1.37.1 with Linkedin and Microsoft Outlook OAuth2 API. After hiting "Connect my account" , my session is disconnected. Same acting is for direct visiting /rest/oauth2-credential/callback.

**Comment by enoksaju** [comment] 2024-04-17 17:45
> We'll release patch release for 1.37 and 1.38 tomorrow morning (CET).

i add the change manually on the docker files at this path: /usr/local/lib/node_modules/n8n/dist/auth/auth.service.js

then i restart docker and still the issue

**Comment by enoksaju** [comment] 2024-04-17 18:03
![image](https://github.com/n8n-io/n8n/assets/27732523/ff64a0d6-fc41-4ea5-91b6-ba4fb5c1bdc7)


mybe issue is with browserid validation, i comment this lines to exclude browser id validation and now is working

**Comment by enoksaju** [comment] 2024-04-17 18:52
i see, req.baseUrl return **_/rest/oauth2-credential_** instead of **_/rest/oauth2-credential/callback_**

**Comment by enoksaju** [comment] 2024-04-17 18:56
fixed with this:

```
const skipBrowserIdCheckEndpoints = [
        `/${restEndpoint}/push`,
        `/${restEndpoint}/binary-data`,
        `/${restEndpoint}/oauth2-credential`,
        `/${restEndpoint}/oauth1-credential`,
];
```

**Comment by netroy** [comment] 2024-04-18 15:29
Fix released in 1.37.3 and 1.38.1.

**Closed by netroy** 2024-04-18 15:29 UTC

**Comment by MorrisLu-Taipei** [comment] 2024-05-18 17:10
similar issue here, version 1.40,
when linked to  LINE Notify 
always shown same messgae w/ OAuth Redirect URL (rest/oauth2-credential/callback)
{"status":"error","message":"Unauthorized"}

**Comment by netroy** [comment] 2024-06-12 12:47
@danielpsf-grover I've been trying to reproduce this with no luck so far.
Is it possible that maybe you have a reverse-proxy in the front that is modifying urls or requests?
