### ISSUE TITLE
Tutorial Steps 2 & 3 appear briefly, then vanish

### ISSUE THREAD

**Issue by nvlgzr** [n8n-io/n8n#2072] opened 2021-08-11 08:09 UTC
**Describe the bug**
The tutorial feature doesn't seem to work past the first mini-tutorial

**To Reproduce**
1. Go through the first mini-tutorial, clicking Finish at the end
2. Click the Tutorial lozenge
3. Click on "Map data between nodes" (or Handle multiple items)
  →  Browser dialog asks "Cancel" or "Leave"
4. Click "Leave" ("Cancel" is a no-op)
  → 🐞 Tutorial overlay appears briefly, but disappears before it can be read or interacted with

**Expected behavior**
  → Tutorial overlay appears, guiding user through 

**Environment (please complete the following information):**
 - OS: macOS 11.5.1
 - n8n Version 0.131.0 (cloud)
 - Operation mode : I don't know what this is, but I'm working from a new account, unmodified

**Additional context**
Easiest way to see the problem: scrub manually to 9s in [this video](https://navelgazer.notion.site/n8n-Tutorial-Bug-8acb03f7d13347e49b10474d3f890d63)

**Comment by sirdavidoff** [comment] 2021-08-11 08:43
Thanks for reporting this, @nvlgzr. It turns out this is an issue in how our tutorial vendor (Appcues) deals with redirects. We're in touch with them about ways of solving it.

**Comment by janober** [comment] 2021-08-11 19:42
@nvlgzr I am closing this issue as it is not a problem in the n8n code, rather a bug in a third-party service we only use on n8n.cloud.

Obviously, does that not mean we will not work on fixing the problem That is wip as @sirdavidoff mentioned.

**Closed by janober** 2021-08-11 19:42 UTC

**Comment by sirdavidoff** [comment] 2021-08-13 13:46
@nvlgzr, we've pushed some changes that our vendor tell us will fix the problem. However, we could do with your help validating this since the problem is intermittent.

Would you mind checking whether you still have that problem? Let me know if you need help getting the tutorial to show.

**Comment by nvlgzr** [comment] 2021-08-17 06:32
Good call on helping me get the view to show again. I can't figure it out. 😁
