### ISSUE TITLE
OpenAI Assistant creating new thread everytime

### ISSUE THREAD

**Issue by yuri12344** [n8n-io/n8n#9399] opened 2024-05-14 16:19 UTC
### Bug Description

When I chat open ai assistant, with chat + send message to assistant, it works fine, but when I try to use it without chat, even if I pass same variables as chat, he keep creating new threads, and never keep to the same thread.

### To Reproduce

1. Create send message to assistant, try use it with chat, it should works fine
2. Create a set, and input the messages and variable, as it chat return, sessionId, action: sendMessage, and chatInput
3. He will create a new thread every time you execute it manually, instead of keep in the same thread

### Expected behavior

It should continue in same thread and keep conversation

### Operating System

Ubuntu

### n8n Version

Latest

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-05-15 06:35
Hey @yuri12344,

I am not fully following what the issue is here, Are you able to provide an example workflow? I would kind of expect any thread history to only be available when using the chat option or memory which it sounds like is working as expected.

It would be interesting to see what you are actually doing so we can work out if it should use an existing thread or not.

**Comment by yuri12344** [comment] 2024-05-15 14:39
@Joffcom I have made a video about it, I think it shows better, just 3 mins videos, check it out please
https://youtu.be/VayYhBoWWDM

**Comment by yuri12344** [comment] 2024-05-15 14:40
Just simple workflow
[My_workflow.json](https://github.com/n8n-io/n8n/files/15323147/My_workflow.json)

**Comment by gvargas9** [comment] 2024-05-16 14:43
Agree. This is an issue.  Same Chat should not create a new Thread in OpenAI. 
By using the same thread we do not need to resend all conversation again.  This is already stored in the thread.
https://platform.openai.com/docs/api-reference/threads/object

**Comment by Joffcom** [comment] 2024-05-17 09:15
I have taken a quick look and I can see the issue, When using chat the node takes the inputs in a different way as we expect the session / thread to be stored / used but on manual messages we don't currently support passing in that input. 

Technically this is a feature request not a bug as it is working as intended but I have created `NODE-1357` as the internal dev ticket to have this added as it could be a fairly quick change when we next look to touch that node.

**Comment by gvargas9** [comment] 2024-05-17 09:20
But this also happens when using the chat model.
There is a new thread created on each reply (2 messages).
The logic should be:
New chat   -->  create thread 
New message (On the Same chat)  --> update Thread 

This model removes the memory element because history is stored in the thread *openai*

**Comment by Joffcom** [comment] 2024-05-17 09:52
Hey @gvargas9,

Is that when using the chat model with the AI Assistant? Looking at the video when using the chat input with the assistant it appeared to remember the name.

**Comment by Joffcom** [comment] 2024-05-17 10:21
I have just reaslised that this is actually a duplicate of an existing feature request which can be found here: https://community.n8n.io/t/memory-functionality-missing-from-openai-assistant-node/34747/17

As this exists on the forum and to save on duplication I am acutally going to close this issue and I will link the feature request to the internal ticket.

**Closed by Joffcom** 2024-05-17 10:21 UTC
Labels: in linear
