### ISSUE TITLE
Workflow execution fails and no details are available / persisted 

### ISSUE THREAD

**Issue by JimHume** [n8n-io/n8n#1112] opened 2020-10-29 21:53 UTC
**Describe the bug**
Large workflows fail and do not log error or success details.

**To Reproduce**
1. Create a large, looping workflow. Our workflow appeared to consume up to 1.2GB of memory during its peak.
2. Run said workflow via webhook (inconsequential--can be run manually)
3. Watch the workflow execute in the execution workflow window
4. Note how the workflow execution fails after a certain period of time

**Expected behavior**
The error details are available to diagnose the issue, and/or any error workflows are executed as a result of the failure.

**Actual behaviour**
No workflow execution information is available (anywhere)--it's unfortunately missing from the system so I don't know how to debug the issue further. The desired error workflow is not executed either--please note the error workflow in the original executed workflow list...this is the one that should have been executed but wasn't.

**Environment (please complete the following information):**
 - OS: [docker image]
 - n8n Version [image: n8nio/n8n:0.87.0]
 - Node.js Version [docker image]

**Additional context**
Please see the attached video that shows an example of the issue. 
Are there additional properties that can be enabled for debug/trace-level logging? I didn't see any in the documentation.

![2020-10-29_14h51_09](https://user-images.githubusercontent.com/17392609/97636382-4712dd80-19f6-11eb-9020-416f9a41f18d.gif)

**Comment by JimHume** [comment] 2020-10-29 22:15
As a follow-up: I can reproduce this 100%. 

For the attached execution we turned off all error/success logging and error workflows. 
![2020-10-29_15h11_11](https://user-images.githubusercontent.com/17392609/97638338-927abb00-19f9-11eb-9da9-a14500aec76b.gif)

**Comment by JimHume** [comment] 2020-10-30 23:17
FYI: a work-around has been to have a workflow that starts with a webhook, and at the end of the workflow it launches another iteration of the workflow through said workflow via a web request.

This lets the individual workflow instances remain small but lets it loop through as many times as desired.

**Comment by janober** [comment] 2020-12-23 13:00
@JimHume just to give you an update on this. We are currently working on a solution.

In the future will n8n always save the initial workflow data (in this case the data of the Webhook). So at least that will not be lost anymore. Depending on a workflow setting will it then additionally be possible to save the progress of the execution after every node that got executed.

Is currently wip under #1245

**Comment by JimHume** [comment] 2020-12-23 16:41
Hi @janober , thanks for the update.

The work-around has performed admirably in the interim: having the workflow kicked off via webhook, and then chaining the end of the workflow with a call to itself via said webhook will allow the resource consumption to stay low, and allow the processing to continue on as desired.

It's remarkable how easy it is to work around the issue, and a testament to the capabilities of n8n that it's so trivial to do so--I'm incredibly impressed with the platform. Keep up the great work!

**Comment by janober** [comment] 2020-12-23 17:07
Thanks a lot @JimHume that is really great to hear and very appreciated! Still hope we have a proper fix soon!

**Comment by pinkizpunk** [comment] 2021-01-05 05:07
C[![Uploading 103608736...]]()

**Comment by krynble** [comment] 2021-05-17 11:48
Hello @JimHume 

We released a few updates recently that might assist you in further debugging.

I will leave some information here for reference as the problem is partly solved already.

- On the workflow settings (with your workflow open, click Settings in the left menu) you can now set `Save Execution Progress`. What this does is save progress for each step the workflow does so you can track progress even if it fails
- n8n already saves initial execution data, so you never lose data (from webhook payload, for example)
- You can also run n8n with separate workers using queue mode; more details here: https://docs.n8n.io/reference/scaling-n8n.html
- You mentioned that your workflow was consuming a lot of memory; what might happen in such cases is that n8n's forked process (the one doing the heavy work) may crash. Still strange that the error workflow did not kick in.
- We added logging to n8n on recent versions. Please check the documentation here: https://docs.n8n.io/reference/logging.html#adding-logs

I hope all this information helps you in debugging further issues. For now, I will be closing this one.

**Closed by krynble** 2021-05-17 11:48 UTC

**Comment by JimHume** [comment] 2021-05-17 18:43
Cheers, thank you for the update @krynble
