### ISSUE TITLE
Issue with AWS SES node in version 0.163.1.

### ISSUE THREAD

**Issue by Yaccobv2** [n8n-io/n8n#2870] opened 2022-02-22 15:32 UTC
Hello, I have found a bug in AWS SES node in version 0.163.1.

When I try to send an email with a white space character in the subject line and a html in the body, the server responds as follows:

```
{"message":"403 - \"<ErrorResponse xmlns=\\\"http://ses.amazonaws.com/doc/2010-12-01/\\\">\\n  <Error>\\n    <Type>Sender</Type>\\n    <Code>SignatureDoesNotMatch</Code>\\n    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\\n  </Error>\\n  <RequestId>c7a82ac1-d9c2-49f8-b3ac-35b4a571c516</RequestId>\\n</ErrorResponse>\\n\"","name":"Error","stack":"Error: Request failed with status code 403\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}
```

Configuration:

 {
  "nodes": [
    {
      "parameters": {
        "isBodyHtml": true,
        "subject": "=Liczba wygasajacych ofert na JustJoinIT:{{$json.expiringOffers}}",
        "body": "={{$json.message}}",
        "fromEmail": "notifications@[...].com,
        "toAddresses": [
          "jakub@[...].com",
          "tom@[...].com",
          "recruitment@[...].com"
        ],
        "additionalFields": {
          "ccAddresses": [
            "paulina@[...].com"
          ]
        }
      },
      "name": "AWS SES",
      "type": "n8n-nodes-base.awsSes",
      "typeVersion": 1,
      "position": [
        720,
        600
      ],
      "credentials": {
        "aws": {
          "id": "29",
          "name": "AWS account"
        }
      }
    }
  ],
  "connections": {}
}

Hope you are able to solve this issue or guide me how should I resolve it in my workflow :) (CC @dolohow)

**Comment by timoha** [comment] 2022-04-02 02:56
Having the same issue. It's a bit weird, first time it works, the second time it doesn't as if there's some caching issue. I've seen this come up multiple time in issues, has anyone ever found a root cause?

**Comment by dolohow** [comment] 2022-04-19 08:50
Perhaps problem is with calculating signature
```

{
"message": "403 - "<ErrorResponse xmlns=\"http://ses.amazonaws.com/doc/2010-12-01/\">\n <Error>\n <Type>Sender</Type>\n <Code>SignatureDoesNotMatch</Code>\n <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\n </Error>\n <RequestId>be88bc76-6ab0-49a9-8224-8b9e6c7ae6d6</RequestId>\n</ErrorResponse>\n"",
"name": "Error",
"stack": "Error: Request failed with status code 403 at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (node:events:538:35) at endReadableNT (node:internal/streams/readable:1345:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)"
} 
```

**Comment by mallegrini** [comment] 2022-08-10 08:57
+1

**Comment by Joffcom** [comment] 2023-01-17 14:59
@mallegrini @dolohow @timoha @Yaccobv2 are any of you seeing this issue on the latest release? I have just done a test and it appears to be working.

![image](https://user-images.githubusercontent.com/4688521/212932687-f5f41878-be55-4424-826d-828fffa13ae9.png)

**Comment by Joffcom** [comment] 2023-05-19 09:23
Hi There,

I am going to mark this one as closed as I have not been able to reproduce it is possible that it was fixed last year and we just missed the notification.

If you are still having the issue let me know and we can open this again.

**Closed by Joffcom** 2023-05-19 09:23 UTC
Labels: node/issue
