### ISSUE TITLE
Visual validation for multi-select fields on Notion (Beta) node throws error for valid input

### ISSUE THREAD

**Issue by bkroggel** [n8n-io/n8n#2957] opened 2022-03-09 13:52 UTC
**Describe the bug**
The visual validator (warning symbol) appears for comma-separated lists next to the entry fields for a multi-select list on the Notion (Beta) node although the entry is entirely valid.

<img width="398" alt="Bildschirmfoto 2022-03-09 um 14 51 51" src="https://user-images.githubusercontent.com/11707221/157455000-50434c95-600b-45c7-a965-6785313582ea.png">

  
<img width="414" alt="Bildschirmfoto 2022-03-09 um 14 51 07" src="https://user-images.githubusercontent.com/11707221/157454876-b2088344-1704-479f-aa4a-de47cf970df5.png">

  
**To Reproduce**
1. Create a workflow including a Notion (Beta) node
2. Create a DB in Notion which includes a multi-select field and create multiple values that can be selected
3. Connect n8n with the just created Notion page (Resources: Database Page, Operation: Create) and select the multi-select field as one of the Key values under "Properties"
4. In order to select the values dynamically choose "Create Expression" for the value field — as an example enter at least two of the earlier created values separated by a comma.
5. Back on the Notion (Beta) node overview the value field is now marked red — the node however runs without any issues and selects the values on the Notion side.
  
  
**Expected behavior**
The visual warning should not appear.
  
  
   
**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]: **Ubuntu 20.04**
 - n8n Version [e.g. 0.119.0]: **0.166.0**
 - Database system [e.g. SQLite; n8n uses
 - SQLite as default otherwise changed] **SQLite**

**Comment by Joffcom** [comment] 2023-06-14 11:22
Going to mark this as closed for now as while it is annoying it is not a bug, This will be fixed in the future still.

**Closed by Joffcom** 2023-06-14 11:22 UTC
