### ISSUE TITLE
When http request body content type is 'raw' return these kind of stream as json 

### ISSUE THREAD

**Issue by rctphone** [n8n-io/n8n#8552] opened 2024-02-05 15:31 UTC
https://github.com/n8n-io/n8n/blob/b62c1d7c414f8e23420b5a0309461e7a4740fd58/packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts#L932

When body content type is 'raw' return these kind of stream as json 

```json
[
  {
    "_writeState": {
      "0": 16303,
      "1": 0
    },
    "_readableState": {
      "state": 6162,
      "highWaterMark": 16384,
      "buffer": {
        "head": {
          "data": {
            "type": "Buffer",
            "data": [
              123,
              34,
              79,
              
              125
            ]
          },
          "next": null
        },
        "tail": {
          "data": {
            "type": "Buffer",
            "data": [
              123,
              34,
              
              125
            ]
          },
          "next": null
        },
        "length": 1
      },
      "length": 81,
      "pipes": [],
      "flowing": null,
      "errored": null,
      "defaultEncoding": "utf8",
      "awaitDrainWriters": null,
      "decoder": null,
      "encoding": null
    },
    "_events": {
      "close": [
        null,
        null,
        null
      ]
    },
    "_eventsCount": 5,
    "_writableState": {
      "objectMode": false,
      "highWaterMark": 16384,
      "finalCalled": true,
      "needDrain": false,
      "ending": true,
      "ended": true,
      "finished": true,
      "destroyed": false,
      "decodeStrings": true,
      "defaultEncoding": "utf8",
      "length": 0,
      "writing": false,
      "corked": 0,
      "sync": false,
      "bufferProcessing": false,
      "writecb": null,
      "writelen": 0,
      "afterWriteTickInfo": null,
      "buffered": [],
      "bufferedIndex": 0,
      "allBuffers": true,
      "allNoop": true,
      "pendingcb": 0,
      "constructed": true,
      "prefinished": true,
      "errorEmitted": false,
      "emitClose": true,
      "autoDestroy": true,
      "errored": null,
      "closed": false,
      "closeEmitted": false
    },
    "allowHalfOpen": true,
    "bytesWritten": 106,
    "_handle": {
      "buffer": null,
      "availOutBefore": 16303,
      "availInBefore": 0,
      "inOff": 0,
      "flushFlag": 2
    },
    "_outBuffer": {
      "type": "Buffer",
      "data": [
        123,
        34,
        79,
        1
        1,
        
        0,
        0,
        0,
        0,
        0
      ]
    },
    "_outOffset": 81,
    "_chunkSize": 16384,
    "_defaultFlushFlag": 2,
    "_finishFlushFlag": 2,
    "_defaultFullFlushFlag": 3,
    "_maxOutputLength": 4294967296,
    "_level": -1,
    "_strategy": 0,
    "_closed": false,
    "bytesRead": 106,
    "_writev": null
  }
]

**Comment by Joffcom** [comment] 2024-02-05 15:58
Hey @rctphone,

Can you clarify what the bug is here and provide a way to reproduce it? It looks like for some reason you decided not to follow our provided template which helps us.

**Comment by Joffcom** [comment] 2024-05-15 19:01
Closing for now until we get more information.

**Closed by Joffcom** 2024-05-15 19:01 UTC

**Comment by 1320800521** [comment] 2026-08-18 04:42
This older report appears to be the same response-shape failure class that is now tracked in #36402, and I was able to add the reproduction detail that was missing when this issue was closed.

I ran four HTTP Request branches against the same JSON echo endpoint on n8n 1.112.4, changing only the outgoing body type and response-format setting:

| Body | Response format | Result |
| --- | --- | --- |
| Raw | JSON | **stream internals returned** (`_readableState`, `_writableState`, `bytesWritten`, `_outBuffer`, …) |
| JSON | JSON | parsed JSON |
| Raw | Auto-detect | parsed JSON |
| Raw | Text | text |

The important part is that the Raw + explicit JSON case can still report execution `success`; the failure is the output value shape.

I also checked the tagged `n8n@2.34.5` HTTP Request V3 source. Raw Body can still set `useStream = true`, while the JSON/text stream-consumption path is tied to `autoDetectResponseFormat`. I am keeping the evidence boundary explicit: **1.112.4 runtime reproduction + 2.34.5 source confirmation + the 2.34.5 runtime report in #36402**. I did not run 2.34.5 locally.

Dedicated reproduction and compact result log:
https://github.com/xbstack/n8n-http-request-raw-body-stream-repro

Current issue with the newer runtime report:
https://github.com/n8n-io/n8n/issues/36402

Longer write-up with the control matrix and production retry implications:
https://www.xbstack.com/en/ai/n8n-http-request-raw-body-response-stream/?utm_source=github&utm_medium=referral&utm_campaign=n8n_http_raw_response_stream&utm_content=historical_issue_comment

The two containment paths that passed the control were JSON Body + JSON Response for ordinary JSON payloads, and Raw Body + Auto-detect when Raw must remain. I would not build a durable parser around `_readableState` / `_outBuffer`; those are useful diagnostic clues, not a stable output contract.
