### ISSUE TITLE
Possible regression in Monaco intellisense

### ISSUE THREAD

**Issue by arpadgabor** [n8n-io/n8n#2949] opened 2022-03-08 22:13 UTC
**Describe the bug**
Intellisense no longer works with the data coming in from previous nodes.

Getting this error in console:
```
Uncaught Error: Expression is not valid: No data found for item-index: "0"
    resolveSimpleParameterValue https://domainjs/chunk-vendors.1baa380e.js:3
    getParameterValue https://domain/js/chunk-vendors.1baa380e.js:3
    get https://domain/js/chunk-vendors.1baa380e.js:829
    createSimpleRepresentation https://domain/js/app.36f9ab47.js:1
    createSimpleRepresentation https://domain/js/app.36f9ab47.js:1
    loadAutocompleteData https://domain/js/app.36f9ab47.js:1
    loadEditor https://domain/js/app.36f9ab47.js:1
```

**To Reproduce**
Open a function node in edit mode

**Expected behavior**
Should provide intellisense for, e.g. `items[0].json`

**Environment (please complete the following information):**
 - OS: Centos 7
 - n8n Version: 0.165.1
 - Node.js Version: whatever's in the docker compose
 - Database system: postgres
 - Operation mode: own

Will take a closer look in the weeked and see if I can make a PR for this.

**Comment by Joffcom** [comment] 2022-03-09 13:00
Hey @arpadgabor,

I have just taken a look and I am not able to reproduce the error.

![image](https://user-images.githubusercontent.com/4688521/157446476-adb37941-ce5e-4b3e-96b9-54bfb0bd7549.png)

Does the node before your function node contain any output data?

**Comment by janober** [comment] 2022-03-09 13:03
@arpadgabor Considering that in your "Steps to Reproduce" you only mention "Open a function node in edit mode" I assume you did not execute the nodes before the Function-Node in question first?

**Comment by Joffcom** [comment] 2022-03-09 13:20
That would do it, Are we ok to close this one for now if it is working?

**Comment by arpadgabor** [comment] 2022-03-09 13:22
From my point of view the problem was between the monitor and chair, so yep.

**Closed** 2022-03-09 15:00 UTC
