### ISSUE TITLE
Anthropic credentials - API key connection problems

### ISSUE THREAD

**Issue by Tsumibito** [n8n-io/n8n#11783] opened 2024-11-19 08:55 UTC
### Bug Description

for a few days now, the API keys for Anthropic account are not connecting to the n8n.
Re-engineering the api key or deleting  Anthropic credentials and creating a new one does not help.
The error changes:
Yesterday it was
Internal Server Error

Today after key regeneration
Received HTTP status code: 529

But it still doesn't work.

### To Reproduce

Go to Anthropic Chat Model Node
Click Credential to connect with
Add Credential api key from console.anthropic.com
![Screenshot 2024-11-17 at 10 48 37](https://github.com/user-attachments/assets/7403fec8-17b8-485a-851c-3df630d77b04)
![Screenshot 2024-11-19 at 09 51 50](https://github.com/user-attachments/assets/5031e03d-ef3b-46f4-abc1-b55bb4512ca4)

### Expected behavior

It have accept the key
I chacked it in make - key as working, so this is n8n problem

### Operating System

Ubuntu 22.04

### n8n Version

 Version 1.67.1

### Node.js Version

do not now how to check

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-19 08:55
Hey @Tsumibito,

We have created an internal ticket to look into this which we will be tracking as "GHC-460"

**Comment by Joffcom** [comment] 2024-11-19 09:58
Hey @Tsumibito,

Thanks for the report, This looks to be a duplicate of #11734 so for now I am going to close this. This issue should be resolved soon though.

**Closed by Joffcom** 2024-11-19 09:58 UTC
Labels: in linear
