### ISSUE TITLE
Telegram Trigger Node does not work in Manual Queued Mode

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#5777] opened 2023-03-24 12:55 UTC
**Describe the bug**

The Node Telegram Trigger does not receive information when in Queue.

- If in Regular mode, Receive in Production and in Test mode
- If it is in Queue mode, it receives it in the Production Webhook but does not receive it in Test mode

When we press the execute button to set the workflow to run in manual mode, the production address of the webhook (/webhook) is registered in Telegram, whereas the correct one would be to register the test address (/webhook-test).

This only happens in queue mode and if the n8n is configured with 2 addresses, one on `N8N_EDITOR_BASE_URL` and one for the webhook on `WEBHOOK_URL`.

**To Reproduce**

1. Set up a New Bot in Telegram
2. Configure the Telegram Trigger
3. Send a message to Bot
4. Message is not received

**Expected behavior**

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 0.221.1
- Node.js Version [e.g. 16.17.0]
- Database system Postgres
- Operation mode queue

**Additional context**

**Comment by Joffcom** [comment] 2023-03-24 13:02
Hey @luizeof,

Have you checked in Telegram to see which URL is set and manually tried sending to the webhook test url for Telegram just to make sure it isn't a routing issue? 

Can you also complete the environment section of the template, It would be handy to know which version of n8n you are on and as this is related to queue mode I assume you are not using SQLite.

**Comment by luizeof** [comment] 2023-03-24 13:21
@Joffcom found the issue.

I use 2 addresses, one for the N8N_EDITOR_BASE_URL and one for the WEBHOOK_URL.

When the node is activated in test mode, the WEBHOOK_URL (for production) is used and telegram registers a 404.


```
{
    "ok": true,
    "result": {
        "url": "https://webhooks.domain.com/webhook-test/id39jdds-12fe-4071-8b5d-d80efbaba6cb/webhook",
        "has_custom_certificate": false,
        "pending_update_count": 3,
        "last_error_date": 1679663559,
        "last_error_message": "Wrong response from the webhook: 404 Not Found",
        "max_connections": 40,
        "ip_address": "",
        "allowed_updates": [
            "message"
        ]
    }
}
```

**Comment by luizeof** [comment] 2023-03-24 13:22
I've updated my description ;)

**Comment by luizeof** [comment] 2023-03-24 13:24
You can verify the addresses using this endpoint, where the wrong address is displayed.

```
https://api.telegram.org/bot{token}/getWebhookInfo
```

**Comment by luizeof** [comment] 2023-03-24 22:03
@Joffcom #5783 seems to be a relationship.

**Comment by Joffcom** [comment] 2023-03-24 22:30
Is this a new issue or has it always been this way? As I far as I remember the editor base url was for notifications to direct to the main instance not for webhooks.

**Comment by luizeof** [comment] 2023-03-26 22:31
> <img alt="@luizeof" width="40" height="40" src="https://avatars.githubusercontent.com/u/257004?s=80&amp;v=4">

Exactly, if I'm going to test the workflow using the execute button, it registers the production webhook. the ideal would be to register the test webhook address for me to receive in the editor. Ideally, the production webhook should only be used when the workflow is activated.

**Comment by luizeof** [comment] 2023-03-26 22:31
Exactly, if I'm going to test the workflow using the execute button, it registers the production webhook. the ideal would be to register the test webhook address for me to receive in the editor. Ideally, the production webhook should only be used when the workflow is activated.

**Comment by luizeof** [comment] 2023-04-04 11:05
I did some use case testing again and updated the issue description.

**Comment by Joffcom** [comment] 2023-08-07 10:19
Hey @luizeof,

I have just done some testing on an older n8n version (0.231.3) and if I set the Editor url and the webhook url to different values I seem to be seeing the correct behaviour in queue mode.

For me If I do a test execution the value of test url is sent (editor url) and if I activate the workflow the production url (webhook_url) is sent.

Are you still seeing this issue?

**Comment by Joffcom** [comment] 2023-09-05 13:33
Closing for now as not able to reproduce.

**Closed by Joffcom** 2023-09-05 13:33 UTC
