### ISSUE TITLE
Error: Invalid continuation byte - probably on node_modules/imap-simple

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#5179] opened 2023-01-17 14:26 UTC
Hi I have the following error on my n8n main instance after I started using the "E-Mail Trigger IMAP" node in some workflows. 
Every couple of Minutes the n8n main instance crashes and restarts, even if there is no incoming email, which was triggering the nodes. When I deactivated the IMAP nodes, that error is not happening anymore. 

```
Editor is now accessible via:
http://localhost:5678/
/usr/local/lib/node_modules/n8n/node_modules/utf8/utf8.js:131
		throw Error('Invalid continuation byte');

^
Error: Invalid continuation byte
    at readContinuationByte (/usr/local/lib/node_modules/n8n/node_modules/utf8/utf8.js:131:9)
    at decodeSymbol (/usr/local/lib/node_modules/n8n/node_modules/utf8/utf8.js:184:12)
    at Object.utf8decode [as decode] (/usr/local/lib/node_modules/n8n/node_modules/utf8/utf8.js:206:17)
    at /usr/local/lib/node_modules/n8n/node_modules/imap-simple/lib/imapSimple.js:222:50
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

n8n Version: 0.211.1

**Comment by Joffcom** [comment] 2023-01-18 09:27
Hey @prononext,

Thanks for reporting this one, I have had a workflow running for a little bit now that uses the Email Trigger node but I have not yet ran into this. How many different mailboxes are you currently monitoring and is this happening on all of them or maybe just one?

As a test could you enable the debug log option and delete the node then add it again which will make sure you are using the v2 node that we released a while back. The debug logging might show us a bit more information and assuming it is not a new workflow adding the node again will just make sure we are on the lastest email node.

Is this also a new error since updating and if so what version were you previously running?

**Comment by prononext** [comment] 2023-01-18 14:32
Hi @Joffcom  
I tested it with 1-5 email trigger nodes in different combinations, whith all the same result. I choose the 1 only node that is available in version 0.211.1 so should be the latest. 
I currently cannot enable debug log to provide more info on the instance.

**Comment by Joffcom** [comment] 2023-01-19 10:34
Hey @prononext,

Out of interest what mail provider are you using? Are you able to set up a quick test with say a gmail account to see if that has the same issue? That would then at least give us a starting point to work out what is going on.

**Comment by prononext** [comment] 2023-01-24 14:20
I changed the provider and same issue happened. But now the problem is clear. 
I had 4 different IMAP Trigger nodes in one workflow. 
Just without triggering the main instance crashes every 1-3 minutes. 
When only activating 1 Trigger it does not crash anymore. 
I guess that is not how its supposed to behave?

**Comment by Joffcom** [comment] 2023-01-24 15:04
Hey @prononext,

4 in one workflow is not something I have ever thought about doing before, Typically we recommend having one trigger in a workflow depending on the type as the static data that is stored with poll based triggers could cause an issue. Something like a schedule or webhook trigger likely wouldn't have the same issue but this is of course just theory.

I will see if I can reproduce this now we know there are 4 triggers in the one workflow.

**Comment by prononext** [comment] 2023-01-24 18:56
Hi @Joffcom,
I just splitted the workflows into 4 different ones, so that they all activate one additional workflow when the triggers are fired. 
The same error happened also when the IMAP Trigger Nodes, are seperated each in one workflow. 
Means, at my end, when more than 1 IMAP Trigger Node is active, in one or in seperate workflows this crash happenes. 
```
Modules/n8n/node_modules/utf8/utf8.js:131
		throw Error('Invalid continuation byte');

^
Error: Invalid continuation byte
    at readContinuationByte (/usr/local/lib/node_modules/n8n/node_modules/utf8/utf8.js:131:9)
    at decodeSymbol (/usr/local/lib/node_modules/n8n/node_modules/utf8/utf8.js:184:12)
    at Object.utf8decode [as decode] (/usr/local/lib/node_modules/n8n/node_modules/utf8/utf8.js:206:17)
    at /usr/local/lib/node_modules/n8n/node_modules/imap-simple/lib/imapSimple.js:222:50
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections `(node:internal/process/task_queues:96:5)```

**Comment by Joffcom** [comment] 2023-01-25 12:00
Hey @Joffcom,

So I guess that means it is not related to multiple triggers, Have you managed to enable debug logging yet?

**Comment by Joffcom** [comment] 2024-01-04 12:49
Closing as waiting for feedback still, Will re-open once we have more info.

**Closed by Joffcom** 2024-01-04 12:49 UTC
