### ISSUE TITLE
Undocumented how to import

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1410] opened 2021-02-05 12:41 UTC
**Describe the bug**
Right now the docs https://docs.n8n.io/reference/start-workflows-via-cli.html#import-workflows-and-credentials only show that you *can* run import and export. This works well when you have a local sqlite file, but the main use-case for me is importing from dev into the production instance, which runs on pgsql in a k8s cluster.

As such, perhaps the CLI should be talking to an API rather than a SQLite DB? Can I tell import/export to use a specific endpoint (like I can with Hasura), and if so, how?

**To Reproduce**
1. Read the docs
2. Miss the info about endpoints

**Expected behavior**
I would have expected it to be documented and possible to import to a remote endpoint.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.26.0] 0.104.2
 - Node.js Version [e.g. 10.16.0]

**Comment by janober** [comment] 2021-02-05 13:06
Do not understand. It communicates with whatever database you use. If your n8n is setup to use SQLite then it import/exports to SQLite, if it is set up for Postgres (wherever it is located on the same server or somewhere in the cloud) then Postgres.

**Comment by haf** [comment] 2021-02-05 16:21
But n8n is in a container, in a container, in istio, in a kubernetes cluster, in a vpc, behind firewalls; is the expectation that I execute into the docker container and run n8n there then, so that the CLI can read the n8n configuration?

**Comment by janober** [comment] 2021-02-06 15:35
Exactly it is a CLI option so running it in the docker container is one option.

The other option is to configure your local n8n to access the same database as the one you want to export/import data off. That works however only if the database is also accessible from where you are running it. If the Postgres database is web-accessible, it is simple, if not you probably have to use something like a SSH tunnel or similar.

Anyway, GitHub issues are only for bugs. As it is not a bug will I close it.

If you require additional functionality please post it in https://community.n8n.io/ as "Feature Request". Thanks!

**Closed by janober** 2021-02-06 15:35 UTC
