### ISSUE TITLE
Missing Document Loaders in n8n Web App Compared to Source Code

### ISSUE THREAD

**Issue by slavakurilyak** [n8n-io/n8n#8215] opened 2024-01-03 17:13 UTC
**Describe the bug**
I'm encountering a discrepancy in the document loaders available in the n8n web app compared to what's available in the source code. Specifically, only two document loaders are visible in the web app, whereas four are expected based on the source code.

**To Reproduce**

1. Launch the n8n web app via `docker run -it --rm --name n8n -p 5678:5678 -v ~/.n8n:/home/node/.n8n docker.n8n.io/n8nio/n8n:ai-beta`
2. Navigate to the LangChain nodes.
3. Attempt to select a document loader.
4. Notice that only "Default Data Loader" and "Github Document Loader" are available.

**Expected behavior**
When I access the LangChain nodes in n8n, I expect to see four document loaders as per the source code, but only two are available. The expected loaders are:

- DocumentBinaryInputLoader
- DocumentDefaultDataLoader
- DocumentGithubLoader
- DocumentJSONInputLoader

These are located in the source code here: [packages/@n8n/nodes-langchain/nodes/document_loaders](https://github.com/n8n-io/n8n/tree/master/packages/%40n8n/nodes-langchain/nodes/document_loaders)

Here's a screenshot showing only two document loaders in the n8n web app:

<img width="319" alt="Screen Shot 2024-01-03 at 9 56 25 AM" src="https://github.com/n8n-io/n8n/assets/6625584/311b340a-5318-47be-9ffd-384d2b5bb510">

And here's a screenshot of the four document loaders as seen in the n8n source code:

<img width="686" alt="Screen Shot 2024-01-03 at 9 58 03 AM" src="https://github.com/n8n-io/n8n/assets/6625584/2bfb923a-d7c3-49f6-a342-44b34d2c85df">

**Environment (please complete the following information):**

- OS: macOS 12.7.2
- n8n Version: 1.21.1
- Node.js Version: v20.10.0
- Database system: SQLite 3.37.0
- Operation mode: own server

**Additional context**
Please let me know if there are any additional configurations or steps needed to enable the missing loaders in the web app interface.

**Comment by Joffcom** [comment] 2024-01-03 17:17
Hey @slavakurilyak,

The JSON Input and the Document Binary loaders you have found in the code are not in the UI and will be removed in the future. We merged both of these into the Default Data loader which also appears to be mentioned in a comment in the code.

```
// This node is deprecated and will be removed in the future.
// The functionality was merged with the `DocumentJSONInputLoader` to `DocumentDefaultDataLoader`
```

I understand this may cause confusion if you are checking the folders and not the code so I will get an internal ticket raised to delete these soon. For now though as there is not a bug here I am going to mark this as closed, Let me know if you have any questions about this.

**Closed by Joffcom** 2024-01-03 17:17 UTC

**Comment by Joffcom** [comment] 2024-01-05 12:06
Hey @slavakurilyak,

Quick update on this one, We will be keeping those nodes where they are and hiding them in the UI so that it doesn't break anything for anyone that happens to have been using them before we merged them. We have done similar things in the past with the Function and Function Items nodes which can still be used in existing workflows and the code is still there but the only version you can add is the Code node.

Let me know if you have any questions or concerns about this.
