### ISSUE TITLE
crash when webhook receive a Zero Width Space

### ISSUE THREAD

**Issue by FormindAPE** [n8n-io/n8n#4447] opened 2022-10-26 07:53 UTC
**Describe the bug**

n8n crash when receiving a post webhook containing a Zero Width Space (U+200B) in the data part

**To Reproduce**

1. activate the workflow
2. create a webhook
3. activate the workflow
4. get the webhook url
5. create a python script to test it:
```python3
import requests
payload = {'data': 'a\u200bb'}
url = # the webhook url
r = requests.post(url,data=payload)
print(r)
```
6. the script return error 500 and the n8n has crash

**Expected behavior**

the workflow must return a http code 200 and the server continue to run.

**Environment (please complete the following information):**

- OS:  Ubuntu Linux 20.04.5 LTS
- n8n Version:  0.199.0 (docker: n8nio/n8n image ID : f9102731fa53)
- Node.js : 
- Database system: Mariadb
- Operation mode: main

**Additional context**

the crash also append when using thehive trigger node

**Comment by Joffcom** [comment] 2022-10-28 12:08
Hey @FormindAPE,

Thanks for reporting this one, I suspect it will impact all trigger nodes so may need to be a core change. I will get a dev ticket created so that we can work on fixing this one.

**Comment by Joffcom** [comment] 2023-01-19 13:17
Hey @FormindAPE,

I have just tried to reproduce this one on the latest release and it appears to be working as expected now, Are you still able to reproduce this on the latest release?

**Comment by FormindAPE** [comment] 2023-01-24 10:23
Hey @Joffcom,

I have update my n8n today (docker image id : b9ce0fd9015a) but sadly I can reprodius the error.

my test workflow is a simple webhook triger node configure in POST mode link to a respond to webhook node and I got the same error with a thehive triger node

my test file
```python3
#!/usr/bin/env python3
import requests

url = 'https://n8n.url/webhook/00000000-0000-0000-0000-000000000000'
data=u"hello\u200bworld"
print(data)
myobj = {'data': data}

tart = requests.post(url, json = myobj)
print(tart.text)
```
the output is : `{"code":0,"message":"There was a problem executing the workflow"}`


in the logs of n8n I can see :
```
soc-docker-th5-n8n-1  | Editor is now accessible via:
soc-docker-th5-n8n-1  | http://localhost:5678/
soc-docker-th5-n8n-1  | /usr/local/lib/node_modules/n8n/dist/ErrorReporting.js:59
soc-docker-th5-n8n-1  |             throw error;
soc-docker-th5-n8n-1  |             ^
soc-docker-th5-n8n-1  |
soc-docker-th5-n8n-1  | InternalServerError [ResponseError]: Incorrect string value: '\xE2\x80\x8Btit...' for column `n8nmariadb`.`execution_entity`.`data` at row 1
soc-docker-th5-n8n-1  |     at Object.executeWebhook (/usr/local/lib/node_modules/n8n/dist/WebhookHelpers.js:422:15)
soc-docker-th5-n8n-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
soc-docker-th5-n8n-1  | Emitted 'error' event on Domain instance at:
soc-docker-th5-n8n-1  |     at emit (node:internal/process/promises:138:33)
soc-docker-th5-n8n-1  |     at processPromiseRejections (node:internal/process/promises:274:27)
soc-docker-th5-n8n-1  |     at processTicksAndRejections (node:internal/process/task_queues:97:32) {
soc-docker-th5-n8n-1  |   httpStatusCode: 500,
soc-docker-th5-n8n-1  |   errorCode: 500,
soc-docker-th5-n8n-1  |   hint: undefined
soc-docker-th5-n8n-1  | }
```

**Comment by Joffcom** [comment] 2023-01-27 10:14
Hey @FormindAPE 

That log is useful, It looks like the issue is happening when trying to insert the character into the database. The good news here is if n8n is crashing and restarting there is a fix in the next release that will prevent this.

Now I know you are potentially using MariaDB I might be able to reproduce this one.

**Comment by Joffcom** [comment] 2024-01-04 12:11
Hey @FormindAPE,

Quick question on this one, As this is an issue only with MariaDB / MySQL and likely to be around the charcter set (maybe latin1 instead of utf-8) and we are planning to remove support for MariaDB / MySQL in the future and have already dropped the documentation examples for it do you still see this as something that should be addressed?

**Comment by Joffcom** [comment] 2024-10-07 15:36
Moving to closed as related to database configuration. Can open again in the future if this continues to be an issue.

**Closed by Joffcom** 2024-10-07 15:36 UTC
