### ISSUE TITLE
HTTP requests not working on MacBook Pro M2

### ISSUE THREAD

**Issue by rotadsr** [n8n-io/n8n#5824] opened 2023-03-30 07:34 UTC
**Describe the bug**
Seems that Axios is not working properly on M2 MacBook Pro. Same workflow tested on M1 and Intel based MacBook Pro and working as expected. The shown error on MacBook M2 is:

```
{"status":"rejected","reason":{"message":"400 - \"<html>\\r\\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\\r\\n<body>\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<center>The plain HTTP request was sent to HTTPS port</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","name":"Error","stack":"Error: 400 - \"<html>\\r\\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\\r\\n<body>\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<center>The plain HTTP request was sent to HTTPS port</center>\\r\\n</body>\\r\\n</html>\\r\\n\"\n    at createError (/Applications/n8n.app/Contents/Resources/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Applications/n8n.app/Contents/Resources/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Applications/n8n.app/Contents/Resources/app/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:406:35)\n    at IncomingMessage.emit (node:domain:532:15)\n    at endReadableNT (node:internal/streams/readable:1331:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}}
```
**To Reproduce**
1. Create an authenticated HTTP request
2. Paste curl from Postman (used bearer token auth in headers)
3. See error

**Expected behavior**
HTTP request successful.

- OS: MacOS Ventura 13.3
- n8n Version: 1.10.0
- Node.js Version: 19.8.1
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**
None

**Comment by Joffcom** [comment] 2023-03-30 07:38
Hey @rotadsr,

Can you confirm what you are sending? The error coming back seems to suggest HTTP is being used rather than HTTPS.

**Comment by rotadsr** [comment] 2023-03-30 12:10
It doesn't work with this curl:

`curl -X GET 'https://URL_REDACTED.com/option' --header 'Authorization: Bearer REDACTED'`

**Comment by rotadsr** [comment] 2023-03-30 12:10
Both requests are working from iTerm2 using zsh.

**Comment by Joffcom** [comment] 2023-03-30 12:15
Hey @rotadsr,

I can't think of a technical reason as to why it would fail on an M2 so I am wondering if there is something else that is missing. Can you add an HTTP request node to your workflow and try calling `https://webhook.site/03a3020e-ef60-4b7f-a647-7f0463719ebe` to see if that works, No auth or anything is needed.

**Comment by rotadsr** [comment] 2023-03-30 12:32
Hey @Joffcom !

I did the same test yesterday and it worked with non auth requests to webhook.site. 

I was just checking and saw that n8n is changing from https to http:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/9199876/228836929-94d8d3f6-743b-4750-88b9-7b211170e21f.png">

**Comment by rotadsr** [comment] 2023-03-30 12:34
Using the intercept in Burp and changing again the URL from http:// to https:// it works fine. So n8n is removing the "s" in https and that's why it doesn't work.

**Comment by rotadsr** [comment] 2023-03-30 12:46
Unfortunately I cannot share the json as it contains sensible data. I don't know why is this happening and I also have tested this using M2, M1 and i7 MacBook Pro, and I only had issues while using the M2 device.

**Comment by Joffcom** [comment] 2023-03-30 12:52
@rotadsr I suspect there would be nothing sensitive if you share the one node pointing to the webhook.site address, We don't need the full workflow just that one part.

I am currently looking to see if I can find someone who has an M2 device but at the moment, When you did the tests did they all use the same version of n8n desktop and had the same applications running? Have you tested on another M2 device as well. Would be nice to know if it is for some reason an odd issue with all M2 devices or an issue that is local to the one you are using.

**Comment by rotadsr** [comment] 2023-03-30 14:17
I don't have access to the M1 right now neither another M2 device, but the i7:
n8n 1.9.0 > HTTP request working as expected 
n8n 1.10.0 > HTTP request working as expected 

Oh sorry I understood the json content that was coming from the HTTP request. Here you can find the json file of the workflow. 

```
{
  "name": "n8n tests",
  "nodes": [
    {
      "parameters": {},
      "id": "346d56ac-b390-4e52-a2d7-66d3e810ee1c",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        460,
        320
      ]
    },
    {
      "parameters": {
        "url": "https://webhook.site/03a3020e-ef60-4b7f-a647-7f0463719ebe",
        "sendQuery": true,
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Authorization",
              "value": "Bearer th1sIs4T3sT"
            }
          ]
        },
        "options": {}
      },
      "id": "7c532e4e-02f5-4132-9c45-958dac9f993e",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        680,
        320
      ],
      "alwaysOutputData": true
    }
  ],
  "pinData": {},
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "versionId": "39208086-8407-46f9-b360-c75ab72978ed",
  "id": "4",
  "meta": {
    "instanceId": "9930633a9b09cff76d8d54b1aad682e3804a9f6fe5d1132d56985e90e43d8c5d"
  },
  "tags": []
}
```

**Comment by Joffcom** [comment] 2023-03-30 14:52
Hey @rotadsr,

There is nothing unusual there, At the moment we still can't think of any technical reason as to why this would be happening it is the same code in the same app so it is a bit of a surprise.

I am still on the hunt for someone with an M2 Mac that can test, I know a lot of people with M1 and i5 / i7. I have put out a little message in our Discord community to see if anyone has an M2 that can spend 10 minutes testing.

**Comment by rotadsr** [comment] 2023-03-31 06:22
Just tested n8n 1.10.0 from macOS M1 and the curl worked.

**Comment by joanbono** [comment] 2023-03-31 06:28
Found similar issue on `n8n 1.10.0` running on a MacBook with Intel:

Curl command:

```shell
$ curl https://ipinfo.io -x http://127.0.0.1:8080 -k
```

When importing it to WebHook on n8n and executing the node:

![image](https://user-images.githubusercontent.com/7288621/229040500-298ca722-d5ec-4300-917d-772261d6d19e.png)

#### Cause

```json
{
    "status": "rejected",
    "reason": {
        "code": "ERR_INVALID_PROTOCOL",
        "cause": {
            "code": "ERR_INVALID_PROTOCOL"
        },
        "error": {
            "code": "ERR_INVALID_PROTOCOL"
        },
        "options": {}
    }
}
```

#### Stack

```
NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.execute (/private/var/folders/1t/kk7j4v8x635169bkbjd15hj00000gn/T/AppTranslocation/C9F49067-B6E1-4ACE-95DF-226523186DD2/d/n8n.app/Contents/Resources/app/node_modules/n8n-nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts:1312:12)
    at Workflow.runNode (/private/var/folders/1t/kk7j4v8x635169bkbjd15hj00000gn/T/AppTranslocation/C9F49067-B6E1-4ACE-95DF-226523186DD2/d/n8n.app/Contents/Resources/app/node_modules/n8n-workflow/src/Workflow.ts:1270:19)
    at /private/var/folders/1t/kk7j4v8x635169bkbjd15hj00000gn/T/AppTranslocation/C9F49067-B6E1-4ACE-95DF-226523186DD2/d/n8n.app/Contents/Resources/app/node_modules/n8n-core/src/WorkflowExecute.ts:938:29
```

#### Expected Behaviour

The request should go through the HTTP proxy

**Comment by Joffcom** [comment] 2023-03-31 08:23
Hey @joanbono,

Have you always been using the proxy? It could be that we have an issue with the proxy not with the M2 mac.

**Comment by joanbono** [comment] 2023-03-31 08:49
@Joffcom the proxy is set as transparent, is completely invisible. I've been always using the proxy. With the `curl` command posted, it works just as expected, the request goes from `curl` to the `proxy`, and from the `proxy` to the API endpoint.

N8N should work the same way, just send the request to the proxy, and the proxy handles that to the endpoint.

Besides that, n8n on M2, is changing the protocol:
+ The API endpoint is using HTTPS
+ The request sent from N8N, even if configured with https, is being downgraded to HTTP, and that causes the endpoint to refuse the call.

**Comment by Joffcom** [comment] 2023-03-31 09:03
Hey @joanbono 

The thing I really want to know though is if you don't use the proxy setting does that make any difference?

Still yet to track down another M2 user to try desktop, did you try from npm yet as well?

Just out of curiosity as well do you have any thoughts on why it would be changed to http only on an M2?

**Comment by joanbono** [comment] 2023-03-31 09:24
> The thing I really want to know though is if you don't use the proxy setting does that make any difference?

On Intel, without the proxy, works as expected.

> Still yet to track down another M2 user to try desktop, did you try from npm yet as well?

Problem is that I have Node 19, and only up top 18 is supported, and I really need Node 19, is not an option right now for me

```
        Your Node.js version (19.8.1) is currently not supported by n8n.
	Please use Node.js v14, v16 (recommended), or v18 instead!
```

I have tried the `docker` version, and same issue, the Proxy is not working, but everything works without proxy:

![image](https://user-images.githubusercontent.com/7288621/229081277-935ce7e3-ea24-44ef-b7e7-39c9e9397cca.png)


> Just out of curiosity as well do you have any thoughts on why it would be changed to http only on an M2?

I am not sure but maybe the Axios library is acting wonky for some reason

**Comment by rotadsr** [comment] 2023-03-31 10:19
Working without proxy on Docker in macOS M2 Ventura 13.3. The workflow was exactly the same that was not working on the desktop app, which I exported and imported into the docker instance.

**Comment by Joffcom** [comment] 2023-03-31 10:24
@joanbono so just to confirm as this is getting confusing now...

On M2 with no proxy does it work? If that is also failing then we have 2 different things to look at and it would be better to not mix 2 things into one issue.

I didn't want to test docker because it wouldn't be the same thing, The only way to really test would be through npm.

**Comment by Joffcom** [comment] 2023-04-06 09:04
Quick update... We have now tested on a new M2 mac using Desktop and I can confirm on a clean install of both MacOS and n8n Desktop calls to HTTPS sites are not changed to HTTP.

To move forward with that part we will need more information about the setup of the Mac, This is of course assuming that all the connections are not using a proxy.

The issue with the proxy sounds like it is a different issue and it would be best to open something on our [Community Support Forum](https://community.n8n.io) for that so we can get more eyes looking at it.

**Comment by Joffcom** [comment] 2023-06-15 12:15
As we have not been able to reproduce this and with Desktop being removed I am going to close this for now. If you also find this when using npm or docker let me know and we can look at opening it again.

**Closed by Joffcom** 2023-06-15 12:15 UTC
