### ISSUE TITLE
Variable Selector doesn't work in Edit Expression window

### ISSUE THREAD

**Issue by rafitamolin** [n8n-io/n8n#5769] opened 2023-03-24 03:45 UTC
**Describe the bug**
Variable Selector doesn't work in Edit Expression window.

**To Reproduce**

1. For example, create a "Send a text message" Telegram node and connect it. 
2. Open the created node, and you'll see "No input data yet - Execute previous nodes". Click that button.
3. In the "text" field of the message to be sent to Telegram, click on "Expression" instead of Fixed". Then, click ![](https://s.chollo.to/txFWxD.png)
5. Variable selector is empty even having executed previous nodes.
![](https://s.chollo.to/txFZfG.png)

**Expected behavior**
Variable selector should display all nodes and relevant info.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.221.0
- Node.js Version 18.15.0
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment] 2023-03-24 11:31
Hey @rafitamolin,

I have just taken a look and I am not able to reproduce this one, If you go to open an expression before running the previous node do you see anything? You should in theory always see the Current Node and any parameters and the names of previous nodes.

![image](https://user-images.githubusercontent.com/4688521/227510192-d72ed978-3a91-4b56-ac6b-7ed8a0af78e7.png)

Do you see any errors in the browser dev console or the n8n log?

**Comment by rafitamolin** [comment] 2023-03-24 19:08
@Joffcom I've just tried and before running previous nodes, I can properly see the variable selectors without any problem. But when executing the workflow/previous nodes I can't.

I believe it's because my Telegram send-message trigger is behind a if node, and the normal situation is for the if to return "false", as you can see here:

![](https://s.chollo.to/txkHlw.png)

But I think even though returning false, the variable selector should display all nodes in the workflow, could you check if you can reproduce it via a IF node like me?

**Comment by Joffcom** [comment] 2023-03-24 20:26
Hey @rafitamolin 

Can you share your workflow? Coming off an if node shouldn't make a difference as you would still be able to access the current nodes parameters but it is always possible there is some odd bug.

If we can get the full workflow we can try the same think you are in the same way to see what happens.

**Comment by rafitamolin** [comment] 2023-03-25 01:44
@Joffcom Here's the workflow URL so you can import it, I had to edit sensitive info from it but I still can reproduce the issue from this edited version: 

```https://raw.githubusercontent.com/rafitamolin/chatgpt-telegram/main/testeee.json````
If by any reason you can't still reproduce it, here's a video file I recorded:

https://user-images.githubusercontent.com/8208578/227679121-df8303eb-b4a5-4025-bb18-847fd7796ed0.mp4

**Comment by janober** [comment] 2023-04-19 08:49
Fix got released with [`n8n@0.223.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.223.0)

**Comment by Joffcom** [comment] 2023-04-19 09:10
Hey @rafitamolin,

This should now be resolved, I am going to mark this one as closed. If you still this issue let me know and we can open the issue again.

**Closed by Joffcom** 2023-04-19 09:10 UTC
Labels: Released
