### ISSUE TITLE
[UX] JSON expressions that are not true or false should warn/error

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1201] opened 2020-11-22 18:14 UTC
**Describe the bug**
Usability fix: warn if the expression evaluates to something other than true/false.

**To Reproduce**

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/193115/99911733-acf13d00-2cf6-11eb-8991-5b030bd7768a.png">
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/193115/99911740-b67aa500-2cf6-11eb-88e5-808692fea424.png">

These nodes actually have inputs, but for some reason the graphical editor resets their input visualisation once in a while, despite having the green one (1) above the predecessors.

**Expected behavior**
When a noob, like myself, writes an expression for the "JSON expression", the UI doesn't actually mean to write an expression for the JSON, but rather, an expression for whether the body is JSON.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04] latest
 - n8n Version [e.g. 0.26.0] latest
 - Node.js Version [e.g. 10.16.0] latest

**Comment by janober** [comment] 2020-11-22 18:22
It looks like you have for some reason an expression on "JSON/RAW Parameter". That would explain why it gets reset once in a while. Why do you have an expression on it?

**Comment by haf** [comment] 2020-11-22 19:00
Because I want to have an expression in the body: `{"paused": {{$json["body"]["paused"]}}}`

I can try the the key-value pair list, too, but why shouldn't I have a raw JSON value?

**Comment by haf** [comment] 2020-11-22 19:02
Ok, I understand; the expression should be either true/false.

**Comment by janober** [comment] 2020-11-22 19:42
The expression in the body is fine. I am talking about the expression on "JSON/RAW Parameter". I can not imagine that you need an expression on that parameter at all. I guess all you want is to simply set it to "true".

**Comment by krynble** [comment] 2021-02-10 16:25
Hey @haf I am not sure what you are trying to achieve and was unable because of the UX.

The expression editor allows you to insert anything (even gibberish useless data) and it will be evaluated during runtime and that may turn into something useful.

This is one of the reasons the editor does not forbid you from writing things that might not be true-y or false-y. In runtime, it may turn to something else, according to input data.

Would you mind adding the expected behavior?

Thanks!

**Comment by haf** [comment] 2021-02-10 18:16
I would have expected it to warn if it wasn't a `typeof x === 'boolean'` actually. I don't think it makes sense not to require the user to have explicitly boolean output, especially since you can just put a `!!` in front of your expression to get to the same end-result as truthy/falsy.

**Comment by krynble** [comment] 2021-08-05 07:37
Thank you for your input @haf 

This is really a great idea. Might require some deeper structural changes as the expression parser and the evaluator are separate parts of the system.

This was added to our roadmap but it's a medium~long term change.

I will be closing for now as it has been added to our backlog.

**Closed by krynble** 2021-08-05 07:37 UTC

**Comment by Fadiabukhadrah** [comment] 2021-08-05 08:37
Sur I'm trying so much never gon
