### ISSUE TITLE
Redis Node :  Set operation for sets-type doesn't work 

### ISSUE THREAD

**Issue by mbakgun** [n8n-io/n8n#6339] opened 2023-05-30 19:39 UTC
**Describe the bug**
When I try to set a value for the 'sets' type in my node, it simply doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a test workflow, 
2. Click on "add node", type "Redis" and  click "Set the value of a key in Redis"
3. Choose accordingly, operation = set, key type sets. 
4. Fill key and value areas. 
5. After an execution nothing happens 

<img width="1111" alt="Screenshot 2023-05-30 at 9 33 31 PM" src="https://github.com/n8n-io/n8n/assets/8726393/1ca347d4-edfd-432d-aa26-d04e1e71efc0">

**Expected behaviour**
I'd like to see the changes on Redis's side. 

**Environment **

- OS:  Ubuntu Server 22.04 x64
- n8n Version: 0.228.2
- Node.js Version: 16.19.1
- Database system: MySQL
- Operation mode: own
- Redis version: 6.0.16

**Additional context**
I've installed n8n using docker. Error repeats itself, whether the key exists or not under the Redis environment.

**Comment by Joffcom** [comment] 2023-05-31 13:18
Hey @mbakgun,

Just gave it a test and I managed to reproduce it, I suspect our check for the type is the cause of this but I have created `NODE-564` as our internal ticket to get this fixed in a future release.

**Comment by mbakgun** [comment] 2023-06-12 14:11
Hi @Joffcom, since it's been a while, I wanted to ask again about the fix and the team's plans regarding it. Will we have a fix with the next or near future versions? 🙏

**Comment by Joffcom** [comment] 2023-06-12 19:57
Hey @mbakgun,

The issue is in our internal tracker and will be fixed at some point. I don't have an exact date or version as the priority can change.

I would say this would likely be fixed in the next few versions.

**Comment by mbakgun** [comment] 2023-10-13 14:53
Hi @Joffcom, do we have any updates regarding this task? Since it's been a while, I wanted to ask again. 🙏

**Comment by mbakgun** [comment] 2023-10-15 11:25
Since some time has passed and it still hasn't been resolved, I wanted to fix it with determination. In the meantime, thank you for continuing to develop the n8n. 
Well, my fix is working locally, I hope we can get it quickly.

**Closed** 2023-10-23 15:33 UTC
Labels: in linear
