### ISSUE TITLE
Custom cron doesn't work when specific days and months are specified 

### ISSUE THREAD

**Issue by pvbhanuteja** [n8n-io/n8n#6350] opened 2023-06-01 08:41 UTC
**Describe the bug**
Custom cron doesn't work when specific days and months are specified 

**To Reproduce**

1. Scheduled Trigger

**Expected behavior**
1.  10 37 3 * * * (This works as expected runs on 3 : 37 AM 10 secs)

2.  10 37 3 1 6 * (Run on 01 June at 3 37 AM 10 Secs) This is not getting triggered but above in 1. is  

**Environment (please complete the following information):**

Latest docker

**Additional context**

**Comment by Joffcom** [comment] 2023-06-01 08:52
Hey @pvbhanuteja,

That is odd I would expect both to fail as our expected format is [Minute] [Hour] [Day of Month] [Month] [Day of Week] which is the standard cron format.

![image](https://github.com/n8n-io/n8n/assets/4688521/6a235676-70ca-46b2-a75b-ac8829ecd1ef)

If you do want support for non standard cron formats it would be better to open a feature request on our support forum, As this is mostly working as documented I am going to mark this one as closed.

Let me know if you have any questions on this.

**Comment by pvbhanuteja** [comment] 2023-06-01 09:03
Hey @Joffcom 
https://github.com/n8n-io/n8n-docs/blob/67935ad2528e2e30d7984ea917e4af2910a096ec/docs/integrations/builtin/core-nodes/n8n-nodes-base.cron.md

Look at this documentation seconds is an optional param. 

Even after removing the sec's parm, the behavior is the same. 

37 3 * * * (This works as expected and runs on 3: 37 AM 10 secs)

37 3 1 6 * (Run on 01 June at 3 37 AM 10 Secs) This is not getting triggered but above in 1. is

**Comment by Joffcom** [comment] 2023-06-01 09:15
Hey @pvbhanuteja,

That is a good spot and goes against the standard cron pattern and what we actually say in the node itself and what the site we link to references.

I will reopen this and check the package we use to confirm which option is correct.

**Comment by Joffcom** [comment] 2023-06-01 09:26
Just checked, Looks like the cron package we use does actually support the seconds option. I will do some testing shortly to see what is going on... Seems odd that without seconds it is also failing though so it sounds like there is more to this.

What version of n8n are you running? We update the `latest` tag fairly often so it would be handy to know the specific version and if it is queue mode and which database is in use.

**Comment by pvbhanuteja** [comment] 2023-06-01 09:38
I Tried on the `latest` and `0.231.0` versions behaviors are the same in both versions. I'm using the default SQLite DB.

**Comment by Joffcom** [comment] 2023-06-01 09:44
@pvbhanuteja perfect and when using the latest tag I assume that was 0.228.2... not that it matters now as I have been able to reproduce it. Out of interest if you set the month to be 5 does that work for you?

**Comment by Joffcom** [comment] 2023-06-01 13:51
I have created `NODE-571` as the internal ticket to look into this further.

**Comment by janober** [comment] 2023-06-14 15:05
Fix got released with [`n8n@0.233.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.233.0)

**Comment by Joffcom** [comment] 2023-06-15 10:40
Hey @pvbhanuteja,

This should now be all good, I am going to mark this as closed and if you are still seeing an issue let me know and we can open it again.

**Closed by Joffcom** 2023-06-15 10:40 UTC
Labels: in linear, Released
