### ISSUE TITLE
Reinstall missing packages with N8N_REINSTALL_MISSING_PACKAGES is messing up the node type and causing workflows to stop

### ISSUE THREAD

**Issue by simulieren** [n8n-io/n8n#5501] opened 2023-02-17 03:55 UTC
First, thank you for building this great tool, I'm having a lot of fun! 😇 

**Describe the bug**
Community nodes are not being reinstalled after a redeployment of a new docker instance.

My setup is using a modified version of this template: https://github.com/railwayapp-templates/n8n

**To Reproduce**

My `Dockerfile`:

```dockerfile
FROM n8nio/n8n:latest

ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER

ARG USERNAME
ARG PASSWORD

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=$USERNAME
ENV N8N_BASIC_AUTH_PASSWORD=$PASSWORD

# Reinstall missing packages: https://docs.n8n.io/integrations/community-nodes/troubleshooting/
ENV N8N_REINSTALL_MISSING_PACKAGES=true

CMD ["n8n", "start"]
```

1. Set up an instance of Railway using this template: https://github.com/railwayapp-templates/n8n
2. Install a community node. In my case: `n8n-nodes-discord` from here: https://www.npmjs.com/package/n8n-nodes-discord
3. Add node to a workflow
4. Redeploy
5. Reload the browser
6. Workflow is now deactivated, and old node is not found, but I can create new nodes.
    1. `Workflow could not be activated: Node not found: n8n-nodes-discord.discord` 
8. _Sometimes uninstalling and reinstalling works, but it might cause more problems_
    1. After a couple of times this stops working and the node is not found even after reinstalling.

The package shows up as installed, but the workflows can't find the nodes.

![Screenshot 2023-02-17 at 10 52 57](https://user-images.githubusercontent.com/8380383/219545262-ff93952d-ce51-43b1-ba1e-26c649146dea.png)

**Expected behavior**
Missing packages should reinstall and workflows should be running and detecting the nodes after a docker instance redeploy. I expect the env variable `N8N_REINSTALL_MISSING_PACKAGES` would reinstall all packages. 

**Environment (please complete the following information):**

- OS: Docker using `n8nio/n8n:latest`
- n8n Version: Version 0.216.0
- Database system: Postgres
- Operation mode: `own`

**Additional context**
Railway deploys do not allow me to persist the nodes directory mentioned here: https://docs.n8n.io/integrations/community-nodes/troubleshooting/

I will add more of my findings in this issue. Thank you! 😄

**Comment by simulieren** [comment] 2023-02-17 04:11
I've found another weird detail in the workflow. The `type` of the node seems to be messed up after I've reinstalled the community node. I have no idea if this is due to the community node or due to the n8n core.

Here is my initial node `type` data compared to the new node:

```diff
    {
      ...
      "name": "Discord Send",
-      "type": "n8n-nodes-discord.discord",
+     "type": "n8n-nodes-discord.n8n-nodes-discord.n8n-nodes-discord.n8n-nodes-discord.n8n-nodes-discord.discord",
      "typeVersion": 1,
      ...
    },
```

**Comment by Joffcom** [comment] 2023-02-20 10:06
Hey @simulieren,

I have just tried to reproduce doing what I think is similar to the Railway issue by installing 2 community nodes, Creating a workflow using them then stopping n8n and deleting the nodes folders. On startup I am getting the below which looks good and in the UI if I open my workflow the nodes are there and looking good.

```
> n8n start
Initializing n8n process
n8n detected that some packages are missing. For more information, visit https://docs.n8n.io/integrations/community-nodes/troubleshooting/
Attempting to reinstall missing packages
Packages reinstalled successfully. Resuming regular initialization.
n8n ready on 0.0.0.0, port 5678
Version: 0.216.0
```

When it fails on Railway do you see anything in the console output?

**Comment by simulieren** [comment] 2023-02-21 04:40
Thank you for looking into this, @Joffcom ! 😄 

The build on Railway is not showing any errors, but at the start of the deployment there are these logs that might be relevant here:

```md
UserSettings were generated and saved to: /home/node/.n8n/config
Initializing n8n process
n8n detected that some packages are missing. For more information, visit https://docs.n8n.io/integrations/community-nodes/troubleshooting/
Attempting to reinstall missing packages
♥
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.bot
starting server on  /tmp/app.bot
starting TLS server false
starting server as Unix || Windows Socket
ipc bot server started
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
QueryFailedError: duplicate key value violates unique constraint "PK_8ebd28194e4f792f96b5933423fc439df97d9689"
at PostgresQueryRunner.query (/usr/local/lib/node_modules/n8n/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at InsertQueryBuilder.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
at SubjectExecutor.executeInsertOperations (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
at SubjectExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
at EntityPersistExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
QueryFailedError: duplicate key value violates unique constraint "PK_8ebd28194e4f792f96b5933423fc439df97d9689"
at PostgresQueryRunner.query (/usr/local/lib/node_modules/n8n/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at InsertQueryBuilder.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
at SubjectExecutor.executeInsertOperations (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
at SubjectExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
at EntityPersistExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
QueryFailedError: duplicate key value violates unique constraint "PK_8ebd28194e4f792f96b5933423fc439df97d9689"
at PostgresQueryRunner.query (/usr/local/lib/node_modules/n8n/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at InsertQueryBuilder.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
at SubjectExecutor.executeInsertOperations (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
at SubjectExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
at EntityPersistExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
QueryFailedError: duplicate key value violates unique constraint "PK_8ebd28194e4f792f96b5933423fc439df97d9689"
at PostgresQueryRunner.query (/usr/local/lib/node_modules/n8n/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at InsertQueryBuilder.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
at SubjectExecutor.executeInsertOperations (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
at SubjectExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
at EntityPersistExecutor.execute (/usr/local/lib/node_modules/n8n/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
Packages reinstalled successfully. Resuming regular initialization.
n8n ready on 0.0.0.0, port 5678
Version: 0.216.0
================================
Start Active Workflows:
================================
...
```

**Comment by Joffcom** [comment] 2023-02-23 11:46
Hey @simulieren,

It looks like it thinks the packages are reinstalled which is strange, I will have to do a quick setup on railway to see if I can reproduce it unless @netroy has any thoughts.

**Comment by simulieren** [comment] 2023-03-13 06:32
@Joffcom I've found another weird thing in the PostgreSQL instance. The `installed_nodes` table seems to be messed up. Especially the `type` column has got weird values.

![image](https://user-images.githubusercontent.com/8380383/224623453-def6cc93-c6a7-47b8-97ab-1b08e6a9ce1e.png)

The type value is `n8n-nodes-discord.n8n-nodes-discord.n8n-nodes-discord.n8n-nodes-discord.n8n-nodes-discord.discord`. I think this seems to cause the main problem. I hope this might help with debugging.

**Comment by simulieren** [comment] 2023-03-13 07:06
@Joffcom I've found a fix.

I had to go to the PostgreSQL table `installed_nodes` and replace the `type` values with the correct ones.

Messed up values:
![image](https://user-images.githubusercontent.com/8380383/224630292-bb8904e5-93d2-4120-898d-16074f8f2c4e.png)

Correct values:
![image](https://user-images.githubusercontent.com/8380383/224630663-f533f3a9-be55-4341-b16d-47128af24f30.png)


Then restart the container instance. And the old workflow works again.

I am uncertain if this is related to this issue: https://github.com/edbrdi/n8n-nodes-discord/issues/23

**Comment by Joffcom** [comment] 2023-03-13 09:51
I don't think it is related to that issue but it could be, Normally editing the name of the node wouldn't matter. I still need to do a railway test to see if it is something related to that.

**Comment by Joffcom** [comment] 2024-01-04 12:57
I have done some testing today and I was not able to reproduce this so I assume this has been fixed in an update at some point over the last few months although I was also unable to reproduce this previously.

@simulieren are you still seeing this issue?

**Comment by radiumx3** [comment] 2024-09-23 09:52
Hello, I have the exact same issue with N8N in docker on Unraid, as soon as the container restart, I get the same exception in the debug logs :duplicate key value violates unique constraint "PK_8...3"   and the package reinstall fails.

The folder n8n is persisted and the priviledges has been set, the ENV N8N_REINSTALL_MISSING_PACKAGES=true   is set. I'm lost about what's going wrong here, any community package cause the same issue atm.

**Comment by Joffcom** [comment] 2024-10-07 15:59
Hey @radiumx3

That is interesting I am not able to reproduce this at all. What env options do you have set? If you do have the storage being persisted you shouldn't need to set that env option.

**Comment by Joffcom** [comment] 2024-11-05 16:54
Moving to closed as not able to reproduce, If we can get a method to reproduce we can look at opening it again.

**Comment by Joffcom** [comment] 2024-11-05 16:57
Opening again

**Closed** 2024-12-10 13:48 UTC
