### ISSUE TITLE
[BUG][Airtable search] Output 1 item with 2 input items

### ISSUE THREAD

**Issue by LucBerge** [n8n-io/n8n#8351] opened 2024-01-16 15:06 UTC
**Describe the bug**
I have 2 items as input of my "Search records" node (Airtable). The output always contains 1 item only.
It always make one search for the first input item.

As if the "Execute once" option in the node parameters was always `True`.

**To Reproduce**
1. On airtable, create a view with records
2. On n8n, add node to output two items
3. On n8n, add search airtable records node
4. Execute the workflow

**Expected behavior**
I should have 2 outputs if I have 2 inputs

**Environment (please complete the following information):**

- OS: Raspbian + Docker
- n8n Version 1.24.0
- Operation mode `main`

**Comment by Joffcom** [comment] 2024-01-16 20:15
Hey @LucBerge,

Thanks for reporting this, it looks like we didn't update the looping documentation but for Airtable List and Search only run once so you would need to use a loop items node if you want to run it once for each incoming item.

You can find the documentation I was referring to here: https://docs.n8n.io/flow-logic/looping/#node-exceptions

As this is known and expected I don't think there is anything to "fix" here but I think we should change this in the future as execute once could be used to run it just once.

I guess based on that this would be a feature request / enhancement which would be better suited to the [support forum](https://community.n8n.io) so we can prioritise changing this based on community need.

I will however bring this up during our nodes team meeting tomorrow to see if we want to handle this a bug or not, if we don't treat this as a bug this issue will be closed in favour of a forum request and if we do treat it a bug I will add an internal dev ticket reference to this.

Let me know if you have any questions on this.

**Comment by LucBerge** [comment] 2024-01-16 20:19
Hello @Joffcom, it is clear. I will create a thread on the forum if you close this issue. Thanks for the feedback.

**Comment by janober** [comment] 2024-01-17 13:15
Just fyi. This inconsistency we have with some nodes (was by design and on purpose originally mainly for "Get All" operations) annoys me for a long time and originally wanted to "get rid of"/"fix" before the first n8n release. Sadly, it never happened. That said, it is definitely something we should clean up at some point .Just do not know when we get to it as it is sadly for multiple reasons not super simple or clear how to do it (so not code-wise, more UX).

**Comment by Joffcom** [comment] 2024-01-17 16:29
Hey @LucBerge,

Just to add to this one, We are going to handle it like a bug and I have created `NODE-1062` as the internal ticket to get this sorted.

**Comment by LucBerge** [comment] 2024-01-17 16:48
Noted. Thanks

**Comment by Joffcom** [comment] 2024-09-09 10:41
Hey @LucBerge,

Good news it looks like this issue has been resolved for a couple of months, Can you update n8n and add an Airtable node to  a workflow and see if you run into the same issue.

**Closed by Joffcom** 2024-09-09 10:41 UTC
Labels: in linear
