### ISSUE TITLE
Cannot select custom field id when update issue in Jira node.

### ISSUE THREAD

**Issue by heroygt** [n8n-io/n8n#2008] opened 2021-07-20 03:43 UTC
Cannot select custom filed id when update issue in Jira node.

XHR Request URL:` http://localhost:5678/rest/node-parameter-options?nodeType=n8n-nodes-base.jira&path=parameters.updateFields.customFieldsUi.customFieldsValues[1].fieldId&methodName=getCustomFields&credentials={"jiraSoftwareServerApi":"my jira account"}&currentNodeParameters={"jiraVersion":"server","resource":"issue","operation":"update","issueKey":"ARC-714","updateFields":{"customFieldsUi":{"customFieldsValues":[{"fieldId":"","fieldValue":""},{"fieldId":"","fieldValue":""}]}}}`

 only return "name" k-v 
![image](https://user-images.githubusercontent.com/55772/126258032-a2bab980-6f07-4a7d-85e5-1d70c74d583e.png)

![image](https://user-images.githubusercontent.com/55772/126257749-7c37453c-3513-41c5-81f2-83c849084422.png)

![image](https://user-images.githubusercontent.com/55772/126257673-acadfba2-0e7e-4c6d-9798-d49145c1b7e0.png)

**Comment by ivov** [comment] 2021-07-29 10:45
Cannot reproduce. n8n@0.124.0 had [improvements to Jira custom fields](https://github.com/n8n-io/n8n/pull/1877), so you may be on an outdated version.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/44588767/127478640-d70ba805-d9b5-4bcd-94e4-8b3537dda9af.png">

**Comment by janober** [comment] 2021-08-08 09:54
As we did not hear back do I close this issue for now. If you still have that issue with the latest n8n version @heroygt simply comment here and I can open the issue again. Thanks!

**Closed by janober** 2021-08-08 09:54 UTC
