### ISSUE TITLE
Unable to Move Canvas View with CTRL + Left Mouse Button in New Canvas Mode

### ISSUE THREAD

**Issue by AlexanderHentzsch** [n8n-io/n8n#11940] opened 2024-11-28 07:54 UTC
### Bug Description

I like to move the view with CTRL and the left mouse button. Unfortunately, this is no longer possible in the new Canvas version. The mouse pointer changes the symbol, but the canvas does not move. Tested with Firefox & Chrome.

### To Reproduce

Try moving the canvas using CTRL and the left mouse button in the new canvas mode.

### Expected behavior

Move the canvas with CTRL and the left mouse button.

### Operating System

Docker

### n8n Version

1.69.2

### Node.js Version

Docker

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-28 07:54
Hey @AlexanderHentzsch,

We have created an internal ticket to look into this which we will be tracking as "GHC-518"

**Comment by tomi** [comment] 2024-11-29 09:49
Duplicate of #11755

**Closed by tomi** 2024-11-29 09:49 UTC
Labels: in linear
