### ISSUE TITLE
Can't activate a workflow (URL path of node already taken)

### ISSUE THREAD

**Issue by bastianfbr** [n8n-io/n8n#10967] opened 2024-09-25 12:15 UTC
### Bug Description

I was working on a startup workflow which activates all my necessary workflows when i boot n8n.
The workflow stops with the error in the activate workflow node : 
![image](https://github.com/user-attachments/assets/cb546794-991a-4e8c-a5c1-ac4113200957)

However, i just checked the url path in the node and there's no second node that use the same path.
I'm just blocked and can't activate all my workflows

### To Reproduce

1. Create some workflows
2. Create a startup workflow to activate all

### Expected behavior

There's shouldn't be an error as it's ok.

### Operating System

Windows 11

### n8n Version

1.57.0

### Node.js Version

18

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-09-25 12:15
Hey @bastianfbr,

We have created an internal ticket to look into this which we will be tracking as "GHC-254"

**Comment by Joffcom** [comment] 2024-09-25 12:19
Hey @bastianfbr 

It looks like you possibly have a workflow that uses the same url for a webhook, this can happen if a webhook / trigger node is duplicated in the UI.

It looks like the error will be with item 4 so I would check what that is doing and it should shed some more light on the issue.

**Comment by bastianfbr** [comment] 2024-09-25 12:23
I already checked the incriminated workflow and there's no duplicated trigger node...
Very weird

**Comment by Joffcom** [comment] 2024-09-25 13:05
Can you share the workflow and the data?

**Comment by bastianfbr** [comment] 2024-09-25 13:35
![image](https://github.com/user-attachments/assets/e6f1f68d-77aa-45df-b8a6-97de68440382)
Had to hide all data cause of being a work workflow only

**Comment by Joffcom** [comment] 2024-09-25 13:50
Hey @bastianfbr,

Sorry I should have been clearer, Can you share the workflow json and the data so we can dig into this more. Without this there is not going to be much we can do as it just looks like a case of duplicated URLs

**Comment by bastianfbr** [comment] 2024-09-27 08:46
I have other workflows that use webhook trigger but every trigger has his own path. There's no duplicated webhook with the same path. I verified by checking one by one workflow with the UI and again by downloading all and searching for the path. There's juste one webhook pointing to the path.

If i change the path to something else it works, yes, but it still doesn't solve the issue that my path is used by a single trigger node in my whole instance and i can't activate it.

**Comment by Joffcom** [comment] 2024-09-27 08:52
Hey @bastianfbr,

I would say if changing the path works it would suggest that the URL is saved somewhere or maybe cached 🤔 

Has this n8n install been used for a while (pre v1 then upgraded) or is it fairly recent? We had an issue a long time ago where  some nodes were duplicated in the json data which would explain this.

As another test if you delete the webhook node and add it again and set the path does that resolve the issue?

**Comment by bastianfbr** [comment] 2024-09-27 09:00
this n8n install has been used for a while but after v1

Hmmm really weird, i deleted the node and added it again with the same path and... no error ?
Really weird but yeah, it's ok now ?

**Comment by Joffcom** [comment] 2024-09-30 07:41
Hey @bastianfbr,

I suspect the workflow may have somehow got a bit mixed up but I am not sure why, for now as this is "fixed" we can close this and I will try and reproduce this without having a duplicate node somewhere.

**Closed by Joffcom** 2024-09-30 07:41 UTC
Labels: in linear
