### ISSUE TITLE
OpenAI models aren't listed

### ISSUE THREAD

**Issue by NoAArrr365** [n8n-io/n8n#7375] opened 2023-10-06 18:04 UTC
**Describe the bug**

OpenAI models are not listed and an error message appears next to it whenever I try to insert data in my prompt. It works fine before and afterwards they all disappear

<img width="884" alt="Capture d’écran 2023-10-06 à 19 59 17" src="https://github.com/n8n-io/n8n/assets/55239555/7b07de7c-f9d2-4bab-a44f-e34dc26f1638">

**To Reproduce**

Add OpenAI Credentials
Add an OpenAI node to Workflow
Choose your Credential
Try to insert data from previous node in the prompt
Models are not listes and an error message appears next to them
Expected behavior

**Environment** (please complete the following information):

n8n Version : Both 1.8.2 (last stable) and 1.9.1 (beta)

**Comment by Joffcom** [comment] 2023-10-06 19:58
Hey @NoAArrr365 

Are you using a paid OpenAI subscription or the trial still? I have seen that issue happen if the trial has expired.

As another test could you remove the expression from the content field and see if it loads then as it could be linked to another bug.

**Comment by NoAArrr365** [comment] 2023-10-06 23:27
Yes the issue is with the expression. If I just type text it works fine and if I do the same thing in another environment it works as well.

**Comment by Joffcom** [comment] 2023-10-09 08:37
Hey @NoAArrr365,

Oddly I am struggling to reproduce this one, Are you able to provide the value of `mydata` just incase it is an issue with the content length?

**Comment by NoAArrr365** [comment] 2023-10-09 20:57
If it's an issue with the content-length, it shouldn't be. With the turbo-16k I'm pushing the same content in a non n8n environment and it works fine. Also, if I just copy-paste it it works.

**Comment by Joffcom** [comment] 2023-10-09 21:17
Hey @NoAArrr365 

The content length would be an issue when we send the request to the n8n backend before the call to get the models from OpenAI.

The model itself doesn't matter if it is the content length so it would be handy to have the content, this will also give me the same data you are sending so I can see if something odd happens with the expression evaluating the value.

Previously issues when using expressions and the load options drop downs have been easy to reproduce but I just can't get this one to trigger so I will need more.

**Comment by Joffcom** [comment] 2023-10-23 14:57
Hey @NoAArrr365,

Can you try this on the latest release, We have now fixed the issue that stopped lists from loading when an expression was in place.

**Comment by Joffcom** [comment] 2024-01-25 17:47
Closing this issue for now as we are not able to reproduce and require more information. If we can get the value of `myData` to test with it may help.

**Closed by Joffcom** 2024-01-25 17:47 UTC
