### ISSUE TITLE
Crypto Node Signing Operation is Broken and Unusable (but I think I have the problem/solution identified)

### ISSUE THREAD

**Issue by carsonbird** [n8n-io/n8n#7611] opened 2023-11-03 21:58 UTC
**Describe the bug**
The Crypto node contains a "Signing" operation that (in theory) allows you to sign strings using PKI. However, there is no field to specify which incoming string to sign. Upon further investigation, I can see that the field does exist in n8n's source code [see here](https://github.com/n8n-io/n8n/blob/5790e251b8072679d7c061e2d2fa1f4229e03cf8/packages/nodes-base/nodes/Crypto/Crypto.node.ts#L305C10-L305C10), but it's not showing up in my UI.

My only guess is that maybe there's interference coming from another parameter of the same name, and it turns out, there is one [see here](https://github.com/n8n-io/n8n/blob/5790e251b8072679d7c061e2d2fa1f4229e03cf8/packages/nodes-base/nodes/Crypto/Crypto.node.ts#L151C11-L151C11).

Maybe these need to be combined into one "Value" parameter that shows up for both the "sign" and "hash" functions? However, I can see other parameters (like [this one](https://github.com/n8n-io/n8n/blob/5790e251b8072679d7c061e2d2fa1f4229e03cf8/packages/nodes-base/nodes/Crypto/Crypto.node.ts#L382C5-L382C5)) that also have duplicated names across operation/action types which are showing up just fine.

Anyways, this makes the Crypto/Sign function useless because I think it's just always signing the empty string `''`.

**To Reproduce**

1. Go to the Crypto Node.
2. Click on the "Sign" action.
3. Notice that there is no "Value" parameter, or any other way to specify a string to sign.

**Expected behavior**
You should be able to input a string to have signed.

**Environment (please complete the following information):**

- OS: Ubuntu Server 23.04, Docker Container
- n8n Version: 1.14.2
- Node.js Version: Whatever version you guys have in your latest Docker build.
- Database system: Probably SQLite - I don't have the Docker setup using an external DB for this yet.
- Operation mode: Not sure. Probably main? It's self hosted...?

**Additional context**
It looks like there are a number of other fields that have duplicates, so maybe that isn't the issue?

The "Value" parameter shows up in the "Hash" operation:
![Screenshot_20231103_160019](https://github.com/n8n-io/n8n/assets/47391698/0ba7aa75-8539-42c5-93eb-73e250bf7309)

But not the "Sign" operation:
![Screenshot_20231103_160315](https://github.com/n8n-io/n8n/assets/47391698/36279766-61cd-40f6-b820-ad61447438c6)

**Comment by Joffcom** [comment] 2023-11-06 08:54
Hey @carsonbird,

Thanks for the report, I have popped in a PR to fix this. I have also made a note about our tests not picking up the value.

**Comment by janober** [comment] 2023-11-08 14:10
Fix got released with [`n8n@1.16.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.16.0)

**Comment by Joffcom** [comment] 2023-11-08 14:39
Hey @carsonbird,

Thanks again for letting us know about this, The issue is now fixed and released as part of `1.16.0`

**Closed** 2023-11-08 14:39 UTC
Labels: Released

**Comment by carsonbird** [comment] 2023-11-09 02:07
@Joffcom Sweet! What was the issue? I'd love to contribute in the future.
