### ISSUE TITLE
New canvas issue-not able to move canvas using ctrl+move

### ISSUE THREAD

**Issue by automa8r-n8n** [n8n-io/n8n#11755] opened 2024-11-15 12:34 UTC
### Bug Description

In the new canvas update for n8n, the user is unable to move the canvas using the Ctrl + Move shortcut, which was previously functional. The canvas remains stationary, and the shortcut does not trigger the expected behavior.

### To Reproduce

Steps to Reproduce:

1. Open n8n with the updated/new canvas interface.
2. Create a new workflow or open an existing one.
3. Try moving the canvas using Ctrl + Left Click + Drag.

### Expected behavior

The canvas should move smoothly following the user's mouse drag while holding down the Ctrl key.

### Operating System

Windows

### n8n Version

1.68.0

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-15 12:34
Hey @automa8r-n8n,

We have created an internal ticket to look into this which we will be tracking as "GHC-448"

**Comment by Joffcom** [comment] 2024-11-15 12:42
Hey @automa8r-n8n,

This should have been resolved already, Are you sure you are using 1.68.0?

**Comment by automa8r-n8n** [comment] 2024-11-15 12:52
Yes, I am using 1.68.0. However it is working fine with old canvas but as soon as I switch to new canvas this issue is occurring.

**Comment by Joffcom** [comment] 2024-11-15 12:58
Odd I am not able to reproduce, Which browser are you using? I wonder if it is a Windows issue.

**Comment by automa8r-n8n** [comment] 2024-11-15 13:09
I am using Edge.

**Comment by mybabysexy** [comment] 2024-11-19 03:52
I'm using Edge and got this error too, but the behavior is different:
- Ctrl + move works when manually click the canvas
- Open a node -> close -> ctrl + move not working, must click the canvas again then it works again

**Comment by cbrady77586** [comment] 2024-11-22 22:10
I'm also not able to move around on the new Canvas. I had tried maybe a week ago and it wouldn't work. Just tried again after upgrading.

# Debug info

## core

- n8nVersion: 1.68.0
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/131.0.0.0 safari/537.36
- isTouchDevice: false

**Comment by alexgrozav** [comment] 2024-12-04 12:59
Hi. I've investigated this and unfortunately it's an upstream issue (https://github.com/bcakmakoglu/vue-flow/discussions/1706) of the canvas plugin we rely on.

Until it's fixed, please use `Space + Left mouse click + drag` or `Middle mouse + drag` to pan the canvas.

**Comment by tomi** [comment] 2024-12-10 12:21
Fixed in #12104

**Comment by tomi** [comment] 2024-12-10 12:21
Keeping this open until it has been released

**Comment by janober** [comment] 2024-12-11 14:25
Fix got released with [`n8n@1.72.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.72.0)

**Comment by MFYDev** [comment] 2024-12-12 04:15
just met this issue, using latest version of n8n which just got released on windows edge browser, the new canvas cannot be moved at all, do not know how you defined got fixed, have to switch back to old canvas @tomi

**Comment by tomi** [comment] 2024-12-12 15:47
@MFYDev just to confirm, you are using version `1.72.0`? Do you have any errors in the browser console?

**Comment by MFYDev** [comment] 2024-12-12 21:57
@tomi Hi Tomi, I rebooted the whole server and clear the full cache both on Cloudflare and Browser and now the new canvas can be dragged, I have no idea why the cache could lead to that issue because back to yesterday there was no errors in the console at all

**Comment by tomi** [comment] 2024-12-13 07:55
@MFYDev thank you for confirming. Must have been some component caching the old version of the FE code.

**Closed by tomi** 2024-12-13 07:55 UTC
Labels: in linear, Released
