### ISSUE TITLE
Postgres Node does not output error branch

### ISSUE THREAD

**Issue by ShawnSack** [n8n-io/n8n#11572] opened 2024-11-05 20:15 UTC
### Bug Description

I am using the postgres node to update a row. If the row cannot be found, the result is an error. When I enable Continue on error using error output, no data is output to the error branch on error. I would like to create a handler for when a row is not found, but I can't do this if the error branch does not output the error. 

![image](https://github.com/user-attachments/assets/9cdc0c49-8bfe-4ddc-916f-8a74aeaad176)
![image](https://github.com/user-attachments/assets/4842ee38-03a4-45b4-ad6f-85d918873e64)

### To Reproduce

1. Create Postgres Node
2. Go to settings and set "On Error" to "Continue (using error output)"
3. Create an update query that will yield no matching rows
4. Set "Query Batching" to "Independently" (So I get an error per query)
5. Attach a code node to error branch
6. Execute

### Expected behavior

Expect an output to error branch for each error encountered

### Operating System

Ubuntu 22.04

### n8n Version

1.65.2

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-05 20:15
Hey @ShawnSack,

We have created an internal ticket to look into this which we will be tracking as "GHC-395"

**Comment by Joffcom** [comment] 2024-11-22 12:08
Hey @ShawnSack,

This looks to be a duplicate of #8791 which should be fixed soon. For now though I am going to mark this as closed so we don't have the duplication.

**Closed by Joffcom** 2024-11-22 12:08 UTC
Labels: in linear
