### ISSUE TITLE
Code node fails

### ISSUE THREAD

**Issue by maurimuchico-work** [n8n-io/n8n#5925] opened 2023-04-06 20:47 UTC
**Describe the bug**
After upgrading to the latest version "code" node fails.
It's was tested that this bug is coming at least from version 0.215.1 and it was working on 0.203.1

**To Reproduce**

1. Place a "Code" node
2. Click on "Execute Node"
3. See error
![image](https://user-images.githubusercontent.com/123373946/230488508-b6a6ee31-dabf-40fe-a292-59a1ca027e30.png)

**Expected behavior**
It should return "Node executed successfully" and the output should be: myNewField = 1.

**Environment (please complete the following information):**

- OS: Windows 11 22H2
- n8n: 0.222.1
- Node.js: 16.20.0
- Database system: SQLite
- Operation mode main

**Additional context**
The database used was a new one.

**Comment by Joffcom** [comment] 2023-04-06 21:01
That is strange I ran that same thing this morning 🤔

Is there anything else in the workflow and you are using the single node run option or the execute workflow button?

**Comment by Joffcom** [comment] 2023-04-10 16:11
Hey @maurimuchico-work 

No news yet, it was a 4 day weekend so won't be checking properly until tomorrow.

**Comment by Joffcom** [comment] 2023-04-11 07:28
Hey @maurimuchico-work,

I have tried to reproduce this on 223.0 by adding a code node and clicking execute but it is working as expected for me, How do you currently have n8n installed / running? Does it always fail as well or just the first time?

**Comment by Joffcom** [comment] 2023-04-11 15:32
Hey @maurimuchico-work,

Your report had no mention of community nodes so if it is related to them can you link me to the community nodes you installed on the clean database that you reproduced the issue on?

We have seen some issues with community nodes if they are incorrectly including some dependencies.

**Comment by Joffcom** [comment] 2023-04-13 07:46
Hey @maurimuchico-work,

Sorry when I said community nodes I meant private nodes, If you don't include your private nodes does everything work as expected? I have seen issues in third party nodes cause issues with n8n before so it is very possible that the issue is related to something odd in the nodes but as I can't reproduce this issue using the initial steps provided we may need access to the nodes to work out what is going on.

**Comment by Joffcom** [comment] 2023-04-19 03:17
Hey @maurimuchico-work 

That is good to know, I will close this now. Thanks for the update.

**Closed** 2023-04-19 03:18 UTC
