### ISSUE TITLE
AI advanced step following a HTTP request is crashing every time

### ISSUE THREAD

**Issue by abdallahalhakim77** [n8n-io/n8n#11711] opened 2024-11-12 23:39 UTC
### Bug Description

I am trying to run an AI step after HTTP request and the page keeps crashing

### To Reproduce

See screenshots. I can't get past this step. 

<img width="1473" alt="Screenshot 2024-11-12 at 3 30 27 PM" src="https://github.com/user-attachments/assets/7aaf8696-e926-4bd1-90d9-8312d0b0d10c">

<img width="1473" alt="Screenshot 2024-11-12 at 3 32 21 PM" src="https://github.com/user-attachments/assets/407b4d5c-75ae-45f5-b5df-eed9dc7543bb">

<img width="1473" alt="Screenshot 2024-11-12 at 3 32 42 PM" src="https://github.com/user-attachments/assets/58130bdd-d26a-4ca6-a5ea-ed8108c225c1">

### Expected behavior

use AI to analyze the results from the previous step

### Operating System

chrome browser

### n8n Version

1.66.0

### Node.js Version

18.16.10

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-12 23:39
Hey @abdallahalhakim77,

We have created an internal ticket to look into this which we will be tracking as "GHC-430"

**Comment by burivuhster** [comment] 2024-11-13 14:35
Hey @abdallahalhakim77 thanks for reporting!

Can you please share your workflow JSON to help us reproduce the issue?

**Comment by jeanpaul** [comment] 2024-11-26 16:57
Hi @abdallahalhakim77 

I'm closing this issue for now, because we couldn't reproduce it. Please feel free to re-open the issue if you can provide a workflow JSON to help us reproduce and debug this issue. Thanks!

**Closed by jeanpaul** 2024-11-26 16:57 UTC
Labels: in linear
