### ISSUE TITLE
Configuração Webhook se perdendo

### ISSUE THREAD

**Issue by lucenajj** [n8n-io/n8n#11780] opened 2024-11-19 02:46 UTC
### Bug Description

Todas as vezes que saio e entro no mesmo workflow a configuraçao do webhook se perde e fica solicitando credencias, porem no meu caso nao estou usando credencial

### To Reproduce

1 - Abre o workflow no meu caso de agendamento em que uso webhook para configurar a Evo
2 - Salvo e logo em seguida vou para a tela Home onde visualizo todos os meus workflows
3 - Abro o mesmo workflow da etapa 1 e quando entro para ver as configurações do no esta me pedindo autenticação

### Expected behavior

Não alterar as configurações ao menos que eu mesmo troque

### Operating System

Ubuntu 20.04

### n8n Version

1.67

### Node.js Version

nao sei

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-19 02:46
Hey @lucenajj,

We have created an internal ticket to look into this which we will be tracking as "GHC-459"

**Comment by Joffcom** [comment] 2024-11-19 04:14
Hey @lucenajj 

Can you update your post to be in English so we can help?

**Comment by lucenajj** [comment] 2024-11-19 11:19
Every time I log out and log in to the same workflow, the webhook configuration gets lost and keeps asking for credentials, but in my case I'm not using credentials

To Reproduce
1 - Open the workflow in my scheduling case where I use the webhook to configure the Evo
2 - Save and then go to the Home screen where I see all my workflows
3 - I open the same workflow from step 1 and when I log in to see the node settings, it's asking me for authentication

Expected behavior
Don't change the settings unless I change them myself

Operating System
Ubuntu 20.04

n8n Version
1.67

Node.js Version
I don't know

Database
PostgreSQL

Execution mode
main (default)

**Comment by FEndo** [comment] 2024-11-22 15:00
I'm facing exactly the same issue here. 

Operating System
Ubuntu 20.04

n8n Version
1.66

Node.js Version
I don't know

Database
PostgreSQL

Execution mode
main (default)

**Comment by FEndo** [comment] 2024-11-22 15:07
Just updated to the version 1.69.0 and it solved the issue, using the new canva.

**Comment by Joffcom** [comment] 2024-11-26 08:37
Moving to closed as likely a duplicate of #11575

**Closed by Joffcom** 2024-11-26 08:37 UTC
Labels: in linear
