### ISSUE TITLE
Getting 404 error when using Github node "Edit File" on custom branch

### ISSUE THREAD

**Issue by HenriChabert** [n8n-io/n8n#7725] opened 2023-11-15 17:59 UTC
**Describe the bug**
When using node "Edit file" from Github integration, with a custom branch, I get the following error:

```
ERROR: The resource you are requesting could not be found
404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#get-repository-content"} - Not Found
````

**To Reproduce**

1. Create a workflow
2. Setup Github Credentials
3. Create a manual trigger
4. Create a Github Node "Edit file"
5. Use an existing repository, for which a file exists in a branch (`branchA`) but not in another one(`branchB`). Let's call this file `example.json`
6. Fill parameter *branch* with the branch `branchA` where the file `example.json` exists

**Expected behavior**
The file from `branchA` should be found and edited properly

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version: 1.15.2

**Additional context**
After investigating the issue, I found out that the problem comes from the following line:
 https://github.com/n8n-io/n8n/blob/f96c1d204400028c55a2120d0569180379c0649f/packages/nodes-base/nodes/Github/GenericFunctions.ts#L84C69-L84C69

Looking at Github API, it seems that parameter `ref` should be passed inside the querystring, not the body. Furthermore, using a body in a GET request does not make much sense.

Proposed fix would be the following function:
```typescript
/**
 * Returns the SHA of the given file
 *
 * @param {(IHookFunctions | IExecuteFunctions)} this
 */
export async function getFileSha(
	this: IHookFunctions | IExecuteFunctions,
	owner: string,
	repository: string,
	filePath: string,
	branch?: string,
): Promise<any> {
	const getQs: IDataObject = {};
	if (branch !== undefined) {
		getQs.ref = branch;
	}
	const getEndpoint = `/repos/${owner}/${repository}/contents/${encodeURI(filePath)}`;
	const responseData = await githubApiRequest.call(this, 'GET', getEndpoint, {}, getQs);

	if (responseData.sha === undefined) {
		throw new NodeOperationError(this.getNode(), 'Could not get the SHA of the file.');
	}
	return responseData.sha;
}
```

**Comment by Joffcom** [comment] 2023-11-15 18:53
Hey @HenriChabert 

Thanks for the report, this appears to be a duplicate of #7614 so for now I am going to mark this as closed and we can pick this up on that issue.

This should be fixed tomorrow by doing pretty much what you have suggested.

**Closed** 2023-11-15 18:53 UTC
