### ISSUE TITLE
Salesforce node: "Add a lead to a campaign" under Contact Actions

### ISSUE THREAD

**Issue by trijste** [n8n-io/n8n#6593] opened 2023-07-04 14:16 UTC
**Describe the bug**
This bug confuses two actions, as the same action exists under Lead Actions.

**To Reproduce**

1. Interrogate Salesforce node
2. Under Lead, see "Add a lead to a campaign"
3. Under Contact, see "Add a lead to a campaign" 

**Expected behavior**
Under Contact Actions it should be "Add a contact to a campaign"

**Environment (please complete the following information):**

- OS: MacOS
- n8n Version 0.234.0

**Additional context**
I <3 n8n

**Comment by Joffcom** [comment] 2023-07-04 14:22
Hey @trijste,

Thanks for taking the time to report this, I have just taken a look and while they are the same thing one uses a contact id and the other users a lead id as leads and contacts are not the same thing in Salesforce.

Because of this I don't believe this is a bug but if we do an overhaul of the salesforce node we could maybe move this to a campaign resource and use a toggle to select between contact or lead.

I think for now as this is not a bug and is intentional I am going to mark this as closed, Thanks again for the report though 🙌🏻

**Comment by trijste** [comment] 2023-07-04 15:34
Thanks @Joffcom for taking the time to review. The operations under the surface are not an issue. The issue is with the syntax. Leads and Contacts are separate objects in Salesforce. Referring to an action on a contact as an action on a lead is incorrect.

<img width="220" alt="CleanShot 2023-07-04 at 11 32 00@2x" src="https://github.com/n8n-io/n8n/assets/23725702/c7687868-330e-4f36-bb87-663785c21389">

When the user subsets the list of actions to show campaign related actions, which one should they pick if they want to add contacts to a campaign, not leads?

**Comment by trijste** [comment] 2023-07-04 19:52
Thanks for understanding @Joffcom. I've noticed a couple issues now. I'll let you know if I find any more. I use the Salesforce node a lot.

**Comment by Joffcom** [comment] 2023-07-05 10:19
Hey @trijste,

I have just popped in the fix for this one which will be merged once the tests have finished and will be available in the next release, I am going to get this one marked as closed for now as it should be resolved :)

Thanks again for raising this and the clarification on where the issue was.

**Closed by Joffcom** 2023-07-05 10:19 UTC

**Comment by janober** [comment] 2023-07-05 13:30
Fix got released with [`n8n@0.234.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.234.1)
