### ISSUE TITLE
ActiveCampaign Node

### ISSUE THREAD

**Issue by sutidor** [n8n-io/n8n#14] opened 2019-08-26 12:39 UTC
![Activecampaign+Workflow execution](https://user-images.githubusercontent.com/34579211/63691235-f5c5f780-c80e-11e9-967e-6079c27320c8.jpg)

The ActiveCampaign module executes correctly but it won't stop. Also you can see the unmatching ID issue bottom right which occurs when trying to stop an execution manually.

**Comment by janober** [comment] 2019-08-26 17:30
Hi!
Just tried but I am unable to reproduce the problem you have. For me it execute the node, creates the user and then stops and that no matter how often I try. Does it happen to you all the time or just once?

The only thing which would make sense to me right now is some network issues. The editor-ui waits for an event (via EventSource) from the backend which tells it that the node did finish executing and that the workflow is done. If that does not happen it simply keeps on thinking that the workflow is still running. If for some reason that event gets lost (because of a connection/wifi issue) exactly what you described would happen.
It would keep on loading forever and when trying to stop it, an error would occure (as the execution which you try to stop would not exist anymore and can so not be stopped).

If you go in executions on the left side it will load the current data from the server and should then display you what actually runs. If noting is running you can then simply refresh the window.

To avoid that problem with bad network connections (if that is actually it) n8n woud either have to check if there are any messages which could not be delivered or a more simple solution ask the server all X seconds if the execution is actually still running or not. Should probably also make sure that the workflow does not get displayed as running anymore once it got an error that the execution does not exist. Will look into that.

**Comment by janober** [comment] 2019-08-29 05:13
As I did not hear back I assume what I wrote above is the actual reason and so close this issue for now. If not feel free to comment and open the issue again.

**Closed by janober** 2019-08-29 05:13 UTC
