### ISSUE TITLE
Error parsing $input.all() in Request Node

### ISSUE THREAD

**Issue by lvitti** [n8n-io/n8n#11269] opened 2024-10-15 14:37 UTC
### Bug Description

I am trying to process requests in batches of N elements that are sent in the body as an array. 
The problem is that these elements have a property with an array of strings, but when trying to parse them in the body, it seems they are not processed correctly.

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/bad39362-bb45-4503-928b-a4dddc99bafc">
<img width="479" alt="image" src="https://github.com/user-attachments/assets/d0dae6c2-9765-40ad-a156-041fc9d3d963">

I am defining a list of 10 elements to process, splitting them into batches of 5, and in the request, I use the variable $input.all() to map and send all the results.

However, with the property that contains the array of strings, the closing `]` is missing.

![image](https://github.com/user-attachments/assets/fcf4c206-ea78-49c9-a8f5-41bc62661428)

[My_workflow.json](https://github.com/user-attachments/files/17380327/My_workflow.json)

### To Reproduce

1. Execute the Loop node
2. Open the Request node and open the body editor

### Expected behavior

It should return a payload like:

```json
[
   {
      "name":"Test 0",
      "tags":["custom_tag"]
   },
   {
      "name":"Test 1",
      "tags":["custom_tag"]
   },
   ...
]
```

### Operating System

Docker

### n8n Version

1.62.5

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-10-15 14:37
Hey @lvitti,

We have created an internal ticket to look into this which we will be tracking as "GHC-322"

**Comment by Joffcom** [comment] 2024-10-15 15:29
Hey @lvitti,

This looks like a duplicate of https://github.com/n8n-io/n8n/issues/10180 which should be resolved soon. Can you let me know if the issue looks similar to yours? From what I can see the issue has nothing to do with $input.all() and it is more than likely the `map` causing the problems.

**Comment by lvitti** [comment] 2024-10-15 20:46
Hi, @Joffcom, yes you are right it's seems to be the same issue.
Honestly, I'm not sure what it could be related to, but it happened to me with the exact situation I mentioned. However, it does seem to be more related to the map().

Thanks!

**Comment by Joffcom** [comment] 2024-10-16 09:26
Perfect, in that case I am going to mark this one as closed as it is likely related. The issue for this should be resolved soon we have a PR in place for it just need to merge it and release.

**Closed by Joffcom** 2024-10-16 09:26 UTC
Labels: in linear
