### ISSUE TITLE
2 ssh nodes in 1 Workflow results in Memory Error

### ISSUE THREAD

**Issue by MarkHoeing** [n8n-io/n8n#6560] opened 2023-06-28 11:59 UTC
**Describe the bug**
If there are 2 ssh nodes with command in it the Workflow gets the Error: 
Problem executing workflow
There might not be enough memory to finish the execution.

**To Reproduce**
Bild an Workflow with 1 Start and 2 ssh nodes direkt in 1 Line.
After the execusion of the 2nd node you wil recieve this error. 
I tried differend credentials as well as Docker or windowsbased installation. Or 2 Subworkflows.

**Expected behavior**
In 1 Workflow you should be able to run 2 ssh nodes.
For loop or swith reasons.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 0.230.3

- OS: Windows 10 19045.3086
- n8n Version 0.228.2
- Node.js 18.16.0
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment] 2023-06-28 12:04
Hey @MarkHoeing,

I have just given this a go and I am not able to reproduce the issue.

![image](https://github.com/n8n-io/n8n/assets/4688521/550eeb97-0343-4688-9a60-bd406cd6e12b)

In my nodes the first one is running `whoami` and the second is running `ls ~/`, Can you try the same 2 commands so we can see if this is a general bug or something directly related to the commands you are running.

What SSH Server are you connecting to and is it OpenSSH on Windows?

**Comment by MarkHoeing** [comment] 2023-06-28 12:15
Hi,

I just found out:
When the first Node is openSSH on Windows the second results in an error.
When the 2 nodes connects to ssh on the Dockerhost (Linux) it works perfect.

Thanhs Mark


Von: Jon ***@***.***>
Gesendet: Mittwoch, 28. Juni 2023 14:05
An: n8n-io/n8n ***@***.***>
Cc: Höing, Mark ***@***.***>; Mention ***@***.***>
Betreff: Re: [n8n-io/n8n] 2 ssh nodes in 1 Workflow results in Memory Error (Issue #6560)

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>
ACHTUNG!: Diese E-Mail stammt von einem externen Absender. Stellen Sie sicher, dass der Absender vertrauenswürdig ist, bevor Sie Anhänge oder Links öffnen.


Hey @MarkHoeing<https://github.com/MarkHoeing>,

I have just given this a go and I am not able to reproduce the issue.

[image]<https://user-images.githubusercontent.com/4688521/249455046-550eeb97-0343-4688-9a60-bd406cd6e12b.png>

In my nodes the first one is running whoami and the second is running ls ~/, Can you try the same 2 commands so we can see if this is a general bug or something directly related to the commands you are running.

What SSH Server are you connecting to and is it OpenSSH on Windows?

-

**Comment by Joffcom** [comment] 2023-06-28 12:27
Hey @MarkHoeing,

Perfect in that case this is a known issue when it comes to the Windows OpenSSH implementation with how it handles connection closing.

We have another ticket for this here: https://github.com/n8n-io/n8n/issues/2907, To avoid duplicate issues I am going to mark this as closed and I will pop a note on the internal ticket so we can look into it sooner.

**Closed by Joffcom** 2023-06-28 12:27 UTC
