### ISSUE TITLE
In the expression editor window, code suggestions are lost when including Chinese characters.

### ISSUE THREAD

**Issue by huisunan** [n8n-io/n8n#8542] opened 2024-02-03 17:49 UTC
**Describe the bug**

In the expression editor window, code suggestions are lost when including Chinese characters.

**To Reproduce**

![image](https://github.com/n8n-io/n8n/assets/30598579/3da28381-62b4-443c-8bd2-538a476adb0a)
![image](https://github.com/n8n-io/n8n/assets/30598579/7fa7014f-1acf-4d7d-8219-2a7549ff3eaf)

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 1.0.1]
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**

**Comment by Joffcom** [comment] 2024-02-03 18:25
Hey @huisunan 

This looks to be a duplicate of the issue below. I am going to mark this as closed and I will link this issue to the internal ticket for fixing this. 

https://github.com/n8n-io/n8n/issues/5527

**Closed** 2024-02-03 18:25 UTC
