### ISSUE TITLE
Duplicated run in UI

### ISSUE THREAD

**Issue by Yoshino-s** [n8n-io/n8n#7890] opened 2023-12-01 03:26 UTC
**Describe the bug**
The UI always show duplicated run turn, but actually they doesn't exist.

**To Reproduce**
Enter into a workflow, run it, quit the editor to go to the list, and enter again, and trigger it again

During Run, there always shows more than one run flow, even using `Execute Once`
<img width="615" alt="image" src="https://github.com/n8n-io/n8n/assets/28624661/e4755252-3c66-468c-844e-3c338480eb53">

<img width="515" alt="image" src="https://github.com/n8n-io/n8n/assets/28624661/a70898b8-9950-4bb9-8672-0ff611f73c21">

But after run:
<img width="585" alt="image" src="https://github.com/n8n-io/n8n/assets/28624661/8d19eec7-c3c5-4a8c-a971-b03533e0ab65">

Each time enter and exit, the count add one

<img width="829" alt="image" src="https://github.com/n8n-io/n8n/assets/28624661/13557922-9aaf-4f90-976a-5decf8f36229">

**Expected behavior**

**Environment (please complete the following information):**

- OS: Darwin 23.0.0 Darwin Kernel Version 23.0.0: Tue Jul 18 20:35:32 PDT 2023; root:xnu-10002.0.199.505.1~3/RELEASE_ARM64_T8112 arm64
- n8n Version: 1.19.0 on the lastest master commit at `ade3acf8001a594235710c00c98a1e12965cf352`
- Node.js Version :v18.16.1
- Database system: SQLite
- Operation mode: main

**Comment by Yoshino-s** [comment] 2023-12-01 03:28
After logout and login/clean browser data, it can be recovery, but quit and enter the editor, it will show again

**Comment by Joffcom** [comment] 2023-12-06 10:03
Hey @Yoshino-s,

I am not able to reproduce this, When you say quit the editor what you are doing? I have tried refreshing the page and loading it in a new tab with no luck.

**Comment by Yoshino-s** [comment] 2023-12-07 03:33
[2023-12-07 11-27-05.mkv.zip](https://github.com/n8n-io/n8n/files/13594549/2023-12-07.11-27-05.mkv.zip)

I made a screen record about how to reproduct it

**Comment by Joffcom** [comment] 2023-12-07 11:50
Hey @Yoshino-s,

Perfect, I was missing a few things like the stop and making sure to click to the workflow rather than refresh the page. I have created a dev ticket which we will be tracking as `ADO-1564` to fix this but I suspect as this is a minor UI issue it will probably not be fixed anytime soon.

**Comment by RicardoE105** [comment] 2024-01-03 20:19
This got fixed with https://github.com/n8n-io/n8n/pull/8148 and will be available in the next release!

**Closed** 2024-01-03 20:20 UTC
Labels: in linear
