### ISSUE TITLE
n8n with wekan

### ISSUE THREAD

**Issue by DimDz** [n8n-io/n8n#4086] opened 2022-09-13 07:03 UTC
**Describe the bug**
Hello, I am a wekan user and login with its API brings the internal-server-error status code 500.

**To Reproduce**
Using latest wekan and latest n8n.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- n8n Version latest
- Node.js Version 14.20

**Comment by Joffcom** [comment] 2022-09-13 07:34
Hey @DimDz,

Thanks for reporting this one, I have had a quick look and I also get the same result but when testing with Postman against Wekan version 6.44.0 I am also seeing the same internal server error message.

I will have a look through the issue on the Wekan project to see if anything jumps out.

**Comment by Limezy** [comment] 2022-09-13 08:00
Same issue for me, @DimDz thanks for reporting

**Comment by Joffcom** [comment] 2022-09-13 08:07
Hey @Limezy,

I have popped a post on the Wekan issue (4595), We are still authenticating using the form data method but it looks like at some point it changed to JSON and the Wekan API docs have not been updated to mention that. Now we know what the issue is we can make the change but I will need to do some testing with older versions to work out if this is going to be a quick change or if it will require a new node version so we can support older installs of Wekan as well.

Internally we are tracking this as [N8N-4619](https://linear.app/n8n/issue/N8N-4619)

**Comment by Limezy** [comment] 2022-09-13 08:43
Well noted, thanks !

**Comment by Joffcom** [comment] 2022-09-13 09:42
Hey @Limezy & @DimDz,

If you want to give it a bash this should be fixed in https://github.com/n8n-io/n8n/pull/4088, I have done some testing on v4.52, v6.18 and v6.44 and they appear to be working for me 👍🏻

**Comment by Limezy** [comment] 2022-09-13 10:12
Unfortunately I'm using n8n installed through a Yunohost package, so I don't have any quick way to compile your PR branch to test on my side !

**Comment by DimDz** [comment] 2022-09-13 11:25
Just tested it and it works. Thanks so much @Joffcom

**Closed** 2022-09-15 08:23 UTC
Labels: node/issue
