### ISSUE TITLE
Merge Multiplex not working as expected

### ISSUE THREAD

**Issue by o-psi** [n8n-io/n8n#5203] opened 2023-01-20 00:18 UTC
**Describe the bug**
The merge multiplex node is giving some issues in the latest updates. It produces one item of output for 6+1 inputs. 

**To Reproduce**
Make a merge multiplex where it says 6 items total, and one item total of each input.  It returns one output. When executing the merge node itself from the editor it says 

**Expected behavior**

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.212.0
- Node.js Version 18.3
- Database system SQLite
- Operation mode own

**Additional context**

[RMM___INVNJA___Ticket_Billing_2.json.txt](https://github.com/n8n-io/n8n/files/10462150/RMM___INVNJA___Ticket_Billing_2.json.txt)
![Screenshot 2023-01-19 at 6 09 57 PM](https://user-images.githubusercontent.com/24534046/213590526-5832314e-42dc-4760-8076-73f09abaa585.jpg)

**Comment by janober** [comment] 2023-01-20 01:59
It looks like the nodes on input 1 have two runs. Is it possible that the first of the two runs contains only one item? Because then this would be the expected behavior as the Merge node would then process 1 item on input 1 and one item from input 2.

**Comment by o-psi** [comment] 2023-01-20 16:46
Maybe I'm looking in the wrong place for the issue, then. This script was working before updating to 0.212.0 from 0.197.0, and reverting, it doesn't show the "items total"

**Comment by janober** [comment] 2023-01-27 19:29
Closing this issue for now.

If you retest and still have issues, please provide an example workflow demonstrating this issue. We will then have a look and fix asap. Thanks!

**Closed by janober** 2023-01-27 19:29 UTC
