### ISSUE TITLE
missing acuity scheduling apikey credential in the predefined credential type in http request node

### ISSUE THREAD

**Issue by mredodos** [n8n-io/n8n#12291] opened 2024-12-18 20:42 UTC
### Bug Description

When you set a trigger for that node acuity scheduling you can set a credential with user and api key https://docs.n8n.io/integrations/builtin/credentials/acuityscheduling/?utm_source=n8n_app&utm_medium=credential_settings&utm_campaign=create_new_credentials_modal

BUT when you try a custom http request and go to the predefined credential type you cant found that but just the oauth versions

### To Reproduce

http request 
predefined credential
search acuity scheduling

### Expected behavior

im expect to found 2 type of credential instead of 1

### Operating System

docker

### n8n Version

last

### Node.js Version

last

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-12-18 20:42
Hey @mredodos,

We have created an internal ticket to look into this which we will be tracking as "N8N-7987"

**Comment by Joffcom** [comment] 2024-12-18 22:01
Hey @mredodos 

This is to be expected, we have been updating credentials slowly to support the newer credential option and have not got to Acuity yet.

Sadly as this is not a bug and is an enhancement / feature request I will need to close this issue however I will take a look and see if this is an enhancement we can quickly do.

Let me know if you have any other questions on this one.

**Closed by Joffcom** 2024-12-18 22:01 UTC
Labels: in linear

**Comment by mredodos** [comment] 2024-12-19 10:11
So is not a huge problem you can set manually basic auth. the problem is just you cant retrieve the credential you have add before in the trigger node.
