### ISSUE TITLE
Inconsistency with date serialization between manual and auto execution of Database Queries [MySQL, Postgres]

### ISSUE THREAD

**Issue by branch3** [n8n-io/n8n#3101] opened 2022-04-07 15:53 UTC
**Describe the bug**
Querying a date or datetime field returns an actual JavaScript-Date-Object in the auto executions, but when running the nodes manually as well as in the previews of the json data, the field is serialized into a String.
This causes issues when using this field later on, for example comparing it in a subsequent query. 
- For the auto executions, the json field needs to be serialized ( for example with toISOString )
- When testing the nodes manually, serializing it creates an issue.

**To Reproduce**
1. Create a simple SQL table (MySQL or MariaDB for instance) : 
```
CREATE TABLE test_datetime (created_at DATETIME);
INSERT INTO test_datetime VALUE (NOW());
```
2. Run the attached workflow Or try the following queries in `MySQL` nodes
2.1. `SELECT created_at FROM test_datetime LIMIT 1` 
2.2. Then `SELECT * FROM test_datetime WHERE created_at='{{$json["created_at"]}}'` 
2.3. This returns nothing when running the "Execute Workflow", since the `created_at` is an actual JavaScript-Date-Object. However executing the node manually works since the `created_at` is serialized into a string.
2.4. The only way to make it work both ways is by using this hack : `{{new Date($json["created_at"]).toISOString()}}`

**Expected behavior**
The way in which a Date or Datetime object is serialized or not, should be consistent across automatic and manual executions. Either one or the other should be chosen.
This will have a breaking change on some deployments, but it is necessary so that the behaviour is consistent between testing, previewing, and running workflows.

**Environment:**
 - n8n Version [0.171.0]
 - Database system [SQLite]

**Additional context**
Here is the workflow provided : 
```
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        200,
        400
      ]
    },
    {
      "parameters": {
        "operation": "executeQuery",
        "query": "SELECT created_at FROM test_datetime LIMIT 1;"
      },
      "name": "SQL Query date field created_at",
      "type": "n8n-nodes-base.mySql",
      "typeVersion": 1,
      "position": [
        480,
        400
      ],
      "credentials": {
        "mySql": {
          "id": "1",
          "name": "mysql-listen-leon-reader"
        }
      }
    },
    {
      "parameters": {
        "operation": "executeQuery",
        "query": "=SELECT * FROM test_datetime WHERE created_at=\"{{$json[\"created_at\"].toISOString()}}\""
      },
      "name": "\"Execute Workflow\" OK, manually NOT OK",
      "type": "n8n-nodes-base.mySql",
      "typeVersion": 1,
      "position": [
        740,
        400
      ],
      "notesInFlow": true,
      "credentials": {
        "mySql": {
          "id": "1",
          "name": "mysql-listen-leon-reader"
        }
      },
      "notes": "created_at needs to be serialized"
    },
    {
      "parameters": {
        "operation": "executeQuery",
        "query": "=SELECT * FROM test_datetime WHERE created_at=\"{{$json[\"created_at\"]}}\""
      },
      "name": "\"Execute Workflow\" NOT OK, manually OK",
      "type": "n8n-nodes-base.mySql",
      "typeVersion": 1,
      "position": [
        740,
        600
      ],
      "notesInFlow": true,
      "credentials": {
        "mySql": {
          "id": "1",
          "name": "mysql-listen-leon-reader"
        }
      },
      "notes": "created_at is already serialized"
    },
    {
      "parameters": {
        "operation": "executeQuery",
        "query": "=SELECT * FROM test_datetime WHERE created_at=\"{{new Date($json[\"created_at\"]).toISOString()}}\""
      },
      "name": "Works both ways",
      "type": "n8n-nodes-base.mySql",
      "typeVersion": 1,
      "position": [
        740,
        800
      ],
      "notesInFlow": true,
      "credentials": {
        "mySql": {
          "id": "1",
          "name": "mysql-listen-leon-reader"
        }
      },
      "notes": "created_at converted and serialized"
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "SQL Query date field created_at",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "SQL Query date field created_at": {
      "main": [
        [
          {
            "node": "\"Execute Workflow\" OK, manually NOT OK",
            "type": "main",
            "index": 0
          },
          {
            "node": "\"Execute Workflow\" NOT OK, manually OK",
            "type": "main",
            "index": 0
          },
          {
            "node": "Works both ways",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by Joffcom** [comment] 2022-04-14 12:11
Hey @branch3,

I am not sure if this is actually a bug, It can be annoying though when the types are not consistent. What is really odd is when following the steps to reproduce I don't get any result back from the 3 nodes with a manual exection or an internally triggered exection no errors just no data and I was expecting at least one record back in 2 of them.

I have tried to reproduce on 171 and 172 with no luck, What I will do though is add this to our internal product ideas board.

**Comment by branch3** [comment] 2022-06-16 15:37
Hi Joff
In a later version 0.177.0, you'r saying : 

> Automatically convert Luxon dates to strings#
> n8n now automatically converts Luxon DateTime objects to strings.

see : [https://docs.n8n.io/reference/release-notes/#automatically-convert-luxon-dates-to-strings](https://docs.n8n.io/reference/release-notes/#automatically-convert-luxon-dates-to-strings)

However when testing on 0.179.0 the workflow shared above, the issue persists.

So what did you mean in your release-notes by automatically converting Luxon dates to string ? I would have expected this to correct this behaviour and close this issue.

Thanks !

**Comment by Joffcom** [comment] 2023-01-17 17:24
Just to add this is being tracked internally as `N8N-5966`

**Comment by manwithpowers** [comment] 2023-10-29 15:24
Apologies for jumping into an old thread, but I'd just like to add that I've spent the better part of a week trying to debug a few of my workflows that would work fine when executing manually but cause errors when executed automatically and it's because of this exact issue. 
It's been particularly frustrating because even in the execution history/log, n8n is showing the dates formatted/read correctly in various Nodes but was ultimately not actually parsing those Date fields correctly when run automatically (via triggers, schedule, etc).
If there is going to be a difference in the way n8n handles serialization of MySQL dates it would be great if that was at least surfaced in the execution history as otherwise it's very misleading and difficult to figure out where the problem is.
I am working around the issue by using @branch3 hack e.g.`{{ new Date($json.start_date).toISOString() }}`

**Comment by Joffcom** [comment] 2024-10-08 07:51
Good news this looks like it was likely resolved in a past release, if this is still an issue let me know and we can open it again.

**Closed by Joffcom** 2024-10-08 07:51 UTC
Labels: in linear
