### ISSUE TITLE
The callback to the wait node reported an error

### ISSUE THREAD

**Issue by checkblue** [n8n-io/n8n#11864] opened 2024-11-25 06:49 UTC
### Bug Description

After execution in my own program I HTTP callback to notify N8N of the completion of the waiting node, but the request was not successful and reported a 500 error.

**Http Return Error:**    
```
request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '68',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /webhook-waiting/534191 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.2.1\r\n' +
        'Content-Length: 68\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      insecureHTTPParser: undefined,
      path: '/webhook-waiting/534191',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'workflow.elven.com',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: AxiosHeaders {
      server: 'nginx/1.24.0',
      date: 'Mon, 25 Nov 2024 04:07:19 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '75',
      connection: 'close',
      etag: 'W/"4b-z3/mVsoog+wRNiJc9N8IaFiUNAE"',
      vary: 'Accept-Encoding'
    },
       data: {
          code: 0,
          message: "Cannot read properties of undefined (reading 'node')"
        }
  }
```

**N8N server error:**

    Error: 
    at new NodeOperationError (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/errors/node-operation.error.js:12:21)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/StopAndError/StopAndError.node.js:92:15)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:42)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:66
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20

### To Reproduce

1. Start the N8N process
2. Setting up waiting nodes
3. Callback waiting node (HTTP Method POST)
4. Return 500 error

### Expected behavior

I expect the callback wait node to succeed

### Operating System

Linux version 6.1.92

### n8n Version

1.68.0

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-25 12:13
@checkblue we are not able to reproduce this, Are you able to provide a minimal workflow that we can run which will reproduce the problem?

**Comment by MarcL** [comment] 2024-12-11 12:08
Hey @checkblue!

We haven’t heard back for a while so we’re going to close this for now.

If you’re still running into the issue, or have more details to share, feel free to reopen it or create a new one. 

Thanks!

**Closed by MarcL** 2024-12-11 12:08 UTC
Labels: in linear
