### ISSUE TITLE
[Text Classifier] Problem in node ‘Text Classifier‘ Could not get parameter - System Prompt Template

### ISSUE THREAD

**Issue by tony-jinwoo-ahn** [n8n-io/n8n#10911] opened 2024-09-20 17:10 UTC
### Bug Description

I attempted to classify Gmail emails using the Text Classifier node. I added categories and connected the OpenAI Chat Model to the node. However, when I clicked the "Test Step" button, the output returned the following error:

`Error: Could not get parameter at getNodeParameter`

To resolve this issue, I had to manually add the following option:
`{ "parameterName": "options.systemPromptTemplate" }`

This behavior is confusing. I believe this option should be enabled by default.

### To Reproduce

1. Add Gmail Trigger node
2. Add Text Classifier node
3. Connect OpenAI Chat Model to the Text Classifier node
4. Fill "Text to Classify" and add Categories
5. Click "Test step" button

### Expected behavior

Text Classifier node should run. If systemPromptTemplate option is required, I believe this option should be enabled by default.

### Operating System

mac (using docker)

### n8n Version

1.58.2

### Node.js Version

?

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-09-20 17:10
Hey @tony-jinwoo-ahn,

We have created an internal ticket to look into this which we will be tracking as "GHC-245"

**Comment by tony-jinwoo-ahn** [comment] 2024-09-20 17:12
@Joffcom Thank you!

**Comment by Joffcom** [comment] 2024-09-26 10:07
Hey @tony-jinwoo-ahn,

I am moving this to closed as it looks to be a duplicate of https://github.com/n8n-io/n8n/issues/10336

Let me know if you have any questions on this.

**Closed by Joffcom** 2024-09-26 10:07 UTC
Labels: in linear
