### ISSUE TITLE
Input mapping shows only the last 8 nodes.

### ISSUE THREAD

**Issue by cyberlink1** [n8n-io/n8n#11517] opened 2024-11-02 21:06 UTC
### Bug Description

The pulldown for input mapping only displays the last 8 nodes and nodes beyond that are not accessable.

### To Reproduce

Select node more than 8 nodes from the first and try to map an input in the first node.

### Expected behavior

I would expect to be able to map an input from any previous node.

This becomes a real issue with using the Chat Memory Manager node. I key the memory off the users email address. Chat Memory Manager nodes part way through the flow fail because the initial IMap node is not accessible as an input node to get the email address. 

### Operating System

docker

### n8n Version

latest docker

### Node.js Version

official docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-02 21:06
Hey @cyberlink1,

We have created an internal ticket to look into this which we will be tracking as "GHC-381"

**Comment by fedme** [comment] 2024-11-04 14:28
Hi @cyberlink1,

Could I ask you to provide a screen recording or a screenshot that shows the issue you're describing? I wasn't able to replicate the issue by following the text description alone, so a video/image would help me a lot.

Thank you!

**Comment by cyberlink1** [comment] 2024-11-04 16:17
> Hi @cyberlink1,
> 
> Could I ask you to provide a screen recording or a screenshot that shows the issue you're describing? I wasn't able to replicate the issue by following the text description alone, so a video/image would help me a lot.
> 
> Thank you!

Late last night I got it to work. Here is the strangeness of it.

This is the whole workflow
![fail1](https://github.com/user-attachments/assets/abe0b3b4-e922-4f4f-94bd-43f89640db95)

This is the part that was failing
![fail2](https://github.com/user-attachments/assets/8663ba08-844f-479f-802e-30ae765dd8a1)

However, removing these merge nodes suddenly made it work again. 
![fail3](https://github.com/user-attachments/assets/94673a12-30ff-49e4-a801-6d83e027d28c)


I dont know why they made the issue happen.

**Comment by fedme** [comment] 2024-11-06 08:07
Hi @cyberlink1, unfortunately I am still unable to reproduce it even with those screenshots.

If the issue has disappeared for you we can close this ticket (and you can open a new one when the issue appears again), otherwise if the issue is still present it would really help if you could share the JSON of a small workflow where this happens together with a video recording showing the issue in details.

Thank you!

**Comment by fedme** [comment] 2024-11-07 13:31
Closing as unable to reproduce, If this happens again re-open the issue (attaching the JSON of a small workflow where this happens together with a video recording showing the issue in details) and we can take another look

**Closed by fedme** 2024-11-07 13:31 UTC
Labels: in linear
