### ISSUE TITLE
New Canvas With Webhook

### ISSUE THREAD

**Issue by Eduardoavargas** [n8n-io/n8n#11610] opened 2024-11-07 03:09 UTC
### Bug Description

When using webhook without authentication in a workflow and using it with authentication in another workflow, you are setting authentication in all workflows, this only happens if you use the new canvas

### To Reproduce

Click on webhook

### Expected behavior

Do not change the authentication method of other workflows

### Operating System

Ubuntu

### n8n Version

1.66

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-07 08:47
Hey @Eduardoavargas,

I have made a workflow with a webhook in it with no auth, Created another workflow with a webhook in it and set it to use Header auth then I have hit save and gone back to the first workflow and the auth is still unset.

Do you have more detailed steps on how to reproduce this as I assumed this is what you were doing but for me on 1.66.0 with Firefox I am not able to reproduce it.

**Comment by MaximeGratens** [comment] 2024-11-07 10:29
Same issue in our side, all of our webhooks are forced to used a basic auth after reload.

**Comment by Joffcom** [comment] 2024-11-07 13:31
Steps from #11622 

```
Steps to Reproduce the Issue

    Create a Workflow:
        Open N8N and start a new workflow or open an existing one.

    Add Webhook Node:
        Add a Webhook node to the workflow as your initial trigger.

    Set Webhook Authentication to None:
        Open the webhook node settings and set the Authentication option to None.
        Save the workflow to confirm this setting.

    Add a New Node with Header Auth:
        Add a node that requires authentication (e.g., an HTTP request node or any custom node).
        Set this new node's Authentication to Header Auth and configure the required details.
        Save the settings and the workflow.

    Verify the Webhook Authentication:
        Go back to the Webhook node and check if the Authentication has switched to Header Auth.
        If it has not, change it back to None, save, and then check if it reverts to Header Auth after a save or reload of the workflow.

```

**Comment by Eduardoavargas** [comment] 2024-11-07 13:32
Jon, it happens exactly like the test you did, but I use Chrome. At night
I'll try to reproduce it in Firefox.

Em qui., 7 de nov. de 2024 às 10:13, Jon ***@***.***>
escreveu:

**Comment by Joffcom** [comment] 2024-11-07 13:39
So this is what I am trying in Chrome, If anyone can let me know what I missed that would be handy


https://github.com/user-attachments/assets/42b2abcc-8474-414d-ad70-1aa6c6b433f5

**Comment by Eduardoavargas** [comment] 2024-11-07 13:43
in the second workflow it sets authentication as basic, and in fact it
happened when I set authentication as basic in the form trigger

Em qui., 7 de nov. de 2024 às 10:39, Jon ***@***.***>
escreveu:

**Comment by Joffcom** [comment] 2024-11-07 16:42
Looking back I think this will be the same as #11575 I am going to close this issue to avoid the duplcate but please keep an eye on the other issue.

**Closed** 2024-11-07 16:42 UTC

**Comment by Joffcom** [comment] 2024-11-13 10:30
@Eduardoavargas do you also get this on 1.67.0?

**Comment by jamesn81** [comment] 2024-11-18 14:38
Had this same issue until I updated just now to `1.67.1`

But that seems to solve it at my end.

**Comment by Eduardoavargas** [comment] 2024-11-18 16:29
I'll update tonight, and come back here to report if it's resolved.

Em seg., 18 de nov. de 2024 às 11:39, James North ***@***.***>
escreveu:
