### ISSUE TITLE
$evaluateExpression cannot handle arrow function or inner function

### ISSUE THREAD

**Issue by nantoniazzi** [n8n-io/n8n#1492] opened 2021-02-25 17:20 UTC
**Describe the bug**
I'm trying to use arrow function in some expressions (I want to filter elements of my previous node) but I always get an error.
I tried to reproduce it in a Function node.

``` javascript
const data = $evaluateExpression('{{  [1, 2, 3, 4, 5].filter(v => v > 2).join(`,`)  }}')
```
**error**: *"Expression is not valid: Malformed arrow function parameter list"*

it doesn't work for anonymous function either
``` javascript
const data = $evaluateExpression('{{  [1, 2, 3, 4, 5].filter(function(v) { return v > 2}).join(`,`)  }}')
```
**error**: *"Expression is not valid: missing ) after argument list"*

I thought it was related to the riot template engine, but I have not the problem executing those expressions in a standalone riot template installation.

**To Reproduce**
Run this node:
```
{
  "nodes": [
    {
      "parameters": {
        "functionCode": "const data = $evaluateExpression('{{  [1, 2, 3, 4, 5].filter(v => v > 2).join(`,`)  }}')\nreturn [{json: {value: data} }];"
      },
      "name": "DEBUG",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        440,
        300
      ]
    }
  ],
  "connections": {}
}
```

**Expected behavior**
The Function node should returns
```
[{json: {value: '3,4,5'}]
```

instead it raises an error

**Environment (please complete the following information):**
 - n8n Version 0.108.0
 - Node.js Version v14.15.5

**Comment by janober** [comment] 2021-02-25 22:45
Thanks for reporting but that is sadly a known problem. It originates in the library that n8n uses underneath the hood for the expressions [riot-tmpl](https://github.com/riot/tmpl).

You can reproduce with it with you example like this:
```javascript
const tmpl = require('riot-tmpl').tmpl;
tmpl('{  [1, 2, 3, 4, 5].filter(v => v > 2).join(`,`)  }', {})
```

Sadly do we currently not have the resources to fix that bug in that library and I am not even sure if it would get merged as it did not get updated for 4 years. So we would either have to fork it at some point or look for an alternative.

**Comment by baflo** [comment] 2021-09-17 11:54
Is there any workaround solution for this?

**Comment by janober** [comment] 2021-09-17 15:20
Only using a Function-Node and then reference the value afterward.

**Comment by tennox** [comment] 2022-08-28 12:01
Is that also why
```
{{require('html-entities').encode("<tag>blub")}}
```
doesn't work?

Or shall I create a separate issue?

**Comment by Joffcom** [comment] 2024-01-04 09:04
Hey @nantoniazzi,

I am just going through some older issues and it looks like this was fixed when we changed from Riot to Tournament in `1.9.0`

![image](https://github.com/n8n-io/n8n/assets/4688521/f7863d49-f792-4817-9252-2150d5bc6b3e)

For now as this looks to be all good I am going to mark this as closed, If you are still seeing this issue let me know and we can open it again.

**Closed by Joffcom** 2024-01-04 09:04 UTC
