### ISSUE TITLE
The 'static/webhook-icon.svg' image is missing, resulting in a 404 error

### ISSUE THREAD

**Issue by dominikmukrecki** [n8n-io/n8n#8092] opened 2023-12-19 12:24 UTC
**Describe the Bug**
The platform is experiencing an issue where the 'static/webhook-icon.svg' image is missing. This results in a 404 error, indicating that the image file cannot be located.

**To Reproduce**

1. Go to any part of the platform where the 'static/webhook-icon.svg' is expected to be displayed.
2. Notice the absence of the icon, typically represented by a broken image link or a 404 not found error in its place.
3. This issue is consistent across all instances where the image is referenced.

**Expected Behavior**
The expected behavior is for the 'static/webhook-icon.svg' image to load correctly, displaying the webhook icon as intended without any errors.

**Environment (please complete the following information):**
- OS: Docker image, Swarm mode
- n8n Version: 1.21.1
- Database System: Postgres
- Operation Mode: Queue Mode with separate workers and webhook processors

**Additional Context**
This issue impacts the visual representation of webhooks across the platform, potentially leading to confusion or a degraded user experience. It's important to investigate the file's existence, path correctness, and server's handling of static files to resolve this error.

![image](https://github.com/n8n-io/n8n/assets/64379788/dc2ff057-eeb6-4134-b33b-c4370ffcdccb)
![image](https://github.com/n8n-io/n8n/assets/64379788/528d759c-6317-4bba-a053-79f693112c8c)
![image](https://github.com/n8n-io/n8n/assets/64379788/70ff7624-98e0-4adc-b74d-0547faa5a98d)
![image](https://github.com/n8n-io/n8n/assets/64379788/da486030-a1c5-46b6-9636-49783ce10851)

**Comment by Joffcom** [comment] 2024-01-02 12:08
Hey @dominikmukrecki,

I am not able to reproduce this on `1.21.1` are you still seeing this or is it working now after a refresh maybe?

**Comment by Joffcom** [comment] 2024-05-15 19:02
Moving to closed for now as we are not able to reproduce this when running from source or in a docker container.

**Closed by Joffcom** 2024-05-15 19:02 UTC
