### ISSUE TITLE
HTTP Request Authorization failed without trailing slash starting from n8n@1.22.4

### ISSUE THREAD

**Issue by SimonMayerhofer** [n8n-io/n8n#8375] opened 2024-01-17 18:09 UTC
**Describe the bug**
Starting from Version 1.22.4 one of the APIs I use no longer authorize correctly when a trailing slash is not used.
The service is our CRM close.com. Didn't test it with others.

Before 1.22.4 I could access any endpoint without a trailing `/`.
Starting from 1.22.4 the endpoint needs to have a trailing  `/`.

Examples:
- Working: `https://api.close.com/api/v1/me/`
- Not Working anymore: `https://api.close.com/api/v1/me`

An information which might be relevant, but I'm not sure:
close.com API Authentication is over basic auth where the API key is the user and the password stays blank. (https://developer.close.com/topics/authentication/)

**To Reproduce**

<details>
<summary>Workflow</summary>

```
{
  "meta": {
    "instanceId": "cb00ec8101547d530ab58bef05716756fbf7e110d42483b8e221c856f3797681"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "facab319-00eb-4bd0-882c-8ef1d8158438",
      "name": "When clicking \"Test Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        120,
        420
      ]
    },
    {
      "parameters": {
        "url": "=https://api.close.com/api/v1/me",
        "authentication": "genericCredentialType",
        "genericAuthType": "httpBasicAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Accept",
              "value": "application/json"
            }
          ]
        },
        "options": {}
      },
      "id": "1fdf0cc5-159e-4b29-b6ab-d7135ed6af61",
      "name": "not working",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        340,
        560
      ],
      "retryOnFail": true,
      "maxTries": 5,
      "waitBetweenTries": 5000,
      "credentials": {
        "httpBasicAuth": {
          "id": "2prosOhiw37KTihV",
          "name": "close.com"
        }
      }
    },
    {
      "parameters": {
        "url": "=https://api.close.com/api/v1/me/",
        "authentication": "genericCredentialType",
        "genericAuthType": "httpBasicAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Accept",
              "value": "application/json"
            }
          ]
        },
        "options": {}
      },
      "id": "27eca22a-e864-434e-b678-63ce2e57b911",
      "name": "working",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        340,
        360
      ],
      "retryOnFail": true,
      "maxTries": 5,
      "waitBetweenTries": 5000,
      "credentials": {
        "httpBasicAuth": {
          "id": "2prosOhiw37KTihV",
          "name": "close.com"
        }
      }
    }
  ],
  "connections": {
    "When clicking \"Test Workflow\"": {
      "main": [
        [
          {
            "node": "not working",
            "type": "main",
            "index": 0
          },
          {
            "node": "working",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

</details>

1. Use close.com API (or maybe others as well?)
2. See error

**Expected behavior**
API Endpoint is working with or without trailing slash like before version 1.22.4

**Environment (please complete the following information):**

- OS: Ubuntu 20.04.6 LTS
- n8n Version [1.22.4](https://github.com/n8n-io/n8n/releases/tag/n8n%401.22.4)
- Node.js Version unkown (docker)
- Database system SQLite;
- Operation mode `main`

I don't know if this is behavior is wanted, but for my workflows it was a breaking change.

**Comment by Joffcom** [comment] 2024-01-17 18:47
Hey @SimonMayerhofer,

Is it possible that the api has changed?

Do you know which version of n8n you were using before 1.22.4? It might be worth going back to that version to see if the issue is still there

**Comment by SimonMayerhofer** [comment] 2024-01-17 18:50
Nope API didn't change. I can reproduce to fix it by switching to 1.22.3. As soon as I'm on 1.22.4 or above the issue appears again. Any version before 1.22.4 is working. tested it from 1.18.1 upwards.

**Comment by Joffcom** [comment] 2024-01-17 19:08
Perfect, knowing it is ok in 1.22.3 is very handy as it narrows down possible causes.

Have you tried 1.25.0 as well? In theory a / shouldn't make a difference so it will be a fun one to track down

**Comment by Joffcom** [comment] 2024-05-15 19:00
Hey @SimonMayerhofer,

It looks like the auto redirect is now resolved so if you wanted to go back to not having the trailing slash you should be all good 😄 

I am going to get this one marked as closed for now.

**Closed by Joffcom** 2024-05-15 19:00 UTC
