### ISSUE TITLE
Spotify playlist fetch loops infinitely and causes out of memory error

### ISSUE THREAD

**Issue by faevourite** [n8n-io/n8n#2028] opened 2021-07-25 15:20 UTC
**Describe the bug**
Using the Spotify node's Playlist->Get Tracks call results in an infinite loop, where tracks are fetched continuously until n8n's memory is exhausted.

**To Reproduce**
1. Use n8n 0.125.0 or later
2. Import this workflow and configure for some playlists: https://n8n.io/workflows/794
3. Run it
4. Note that the Spotify Get Tracks Original task runs forever. n8n logs have the generic nodejs error about garbage collecting not being able to clean up enough memory.

**Expected behavior**
Step 4 should complete within a few seconds at most, like it did in pre-0.125.0 versions (I have it working fine on 0.123.1).

**Environment (please complete the following information):**
 - OS: docker on ubuntu linux 20.04
 - n8n Version 0.125.0
 - Node.js Version whatever comes with the docker image of 0.125.0
 - Database system SQLite
 - Operation mode own

**Additional context**
I believe this is an infinite loop because in my Spotify Developer account where I have an app set up exclusively for my personal n8n installation the number of requests skyrocketed after 0.125.0 update. I only have one Spotify recipe running, so it appears that recipe is making lots of requests.

Could https://github.com/n8n-io/n8n/pull/1884 be where the issue was introduced?

**Comment by gerardlouw** [comment] 2021-08-06 19:46
Hi! Author of the workflow here. Unfortunate about the infinite loop - I just ran into the same issue. It looks like this was caused by a bug in the Spotify playlist fetcher, suddenly limiting to 1000 results. So if your archive playlist already had 1000 songs, but the playlist you're archiving had a song not appearing in those 1000 songs, then it would just repeatedly add it, never seeing it get added. Hopefully this is fixed with @X-pech's pull request.

**Comment by gerardlouw** [comment] 2021-08-06 20:04
A change to the workflow which would make it less prone to this kind of bug in the future (and thus more reliably... idempotent) would be to build the archive in reverse, by instead prepending songs. This can by done by adding the "Position" property under "Additional Fields" and setting it to 0.

**Comment by janober** [comment] 2021-08-08 08:00
Got fixed by @X-pech and just merged. Will be released with the new version today.

**Closed by janober** 2021-08-08 08:00 UTC

**Comment by janober** [comment] 2021-08-08 11:17
Got released with n8n@0.133.0

**Comment by faevourite** [comment] 2021-08-08 13:34
Thanks, all! Confirmed fixed in 0.133.0.
