### ISSUE TITLE
`npm run dev` on fresh clone doesn't work

### ISSUE THREAD

**Issue by frane** [n8n-io/n8n#1167] opened 2020-11-16 11:43 UTC
**Describe the bug**
`npm run dev` on fresh clone doesn't work. Running the command build successfully and starts the UI on localhost:8080, however it returns a message: 
```
Init Problem
There was a problem loading init data:
API-Server can not be reached. It is probably down.
```
Browser shows that it's trying to connect to http://localhost:5678 but does not succeed with `Failed to load resource: Could not connect to the server.
http://localhost:5678/rest/push?sessionId=44mdzchjq09`

**To Reproduce**
1. Clone the repo freshly into a new directory
2. Bootsrap
3. `npm run dev`

**Expected behavior**
UI and API should be started and run on the same port, or at least be configured to find each other.

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - n8n Version 0.93
 - Node.js Version 15.1.0

**Additional context**
`npm run build && npm run start:default` works as expected starting API and UI on localhost:5678

**Comment by janober** [comment] 2020-11-16 12:11
Ah yes, it seems like you forgot the `npm run build` between step 2 & 3 as described here:
https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#actual-n8n-setup

Without build, it can not work if you access the port 5678 as it is serving the data from the `dist` folder in the editor-UI. As it will not exist or be empty before the build, no data can be served. That is why I did add the build as an initial setup step.
It should however work if you access port 8080 as that uses the frontend dev version with hot reload.

**Comment by frane** [comment] 2020-11-16 15:47
So...
```
> npm run build
> npm stard:default
```
--> WORKS
while
```
> npm run build
> npm run dev
```
--> fails

I've tested it multiple times.

Find my browser and terminal logs attached. 
[n8n_browser.log](https://github.com/n8n-io/n8n/files/5547358/n8n_browser.log)
[n8n_terminal.log](https://github.com/n8n-io/n8n/files/5547359/n8n_terminal.log)

**Comment by janober** [comment] 2020-11-16 17:18
That is strange. Thanks a lot. Will have a look.

**Comment by MedAliMarz** [comment] 2021-03-02 16:01
After investigating a littlbe, I had this error while using the latest version of node

![Image Pasted at 2021-3-2 16-07](https://user-images.githubusercontent.com/36171143/109675944-86099900-7b78-11eb-91d5-449464bc9acf.png)

for now the root cause is unclear, but you can use the node v14 (LTS version) to avoid such issue.

**Comment by fernandosq** [comment] 2021-04-23 12:19
I have the same error  @frane , u resolved it? when I do npm run dev it don´t work

**Comment by frane** [comment] 2021-04-23 12:25
> I have the same error @frane , u resolved it? when I do npm run dev it don´t work

No didn't manage to get it to work yet.

**Comment by arladmin** [comment] 2021-04-26 07:23
Hi @janober , i'm facing a similar issue.
After:
```
lerna bootstrap --hoist
npm run build
npm run dev
```
i go to http://localhost:8081/workflow
and see the error:
```
Error message: 'There was a problem loading init data: API-Server can not be reached. It is probably down'
```

Now, i've gone through this: https://docs.n8n.io/nodes/creating-nodes/troubleshooting.html#editor-ui
but still can't get it to work.
How else to diagnose possible issues?

Thanks.

**Comment by krynble** [comment] 2021-05-17 10:31
Hello.

I made a test a few moments ago using docker Ubuntu image.

- run container using `docker run -it ubuntu bash`
- run `apt-get update`
- run `apt-get -y install curl`
- Add Node.JS 14 repo (used `curl -fsSL https://deb.nodesource.com/setup_14.x | bash -`)
- Install Node.JS via `apt-get install -y nodejs`
- Install GIT `apt install -y git`
- Clone repo `git clone https://github.com/n8n-io/n8n.git`
- Install lerna `npm install -g lerna`
- Go to n8n dir: `cd n8n`
- Install dependencies: `lerna bootstrap --hoist`
- Build n8n: `npm run build`
- Run `npm run start` once (just to make sure n8n has created the config files and database). Kill it using `CTRL+C`
- Test if n8n works:
- - Start n8n in the background using `nohup npm run dev &` - this will start n8n dev mode and detach it from your current terminal window
- - Wait about 2 minutes for n8n to fully compile and start
- - Test if n8n is fine: `curl http://localhost:5678` and you should see some HTML output
- - Test if n8n dev mode is fine: `curl http://localhost:8080` and you should also see some HTML
- - Test if n8n API is working: `curl http://localhost:5678/healthz` should yield `{"status":"ok"}`

You can now use `exit` and stop the container.

These steps should also work on Ubuntu workstation. Maybe what is missing in the steps you did was run `npm run start` once just to see n8n running.

Let me know if the above steps helped.

**Comment by rishi003** [comment] 2021-05-21 19:51
As @janober mentioned above, running `npm run build` fixed it.

**Comment by krynble** [comment] 2021-05-25 07:45
Great, I will be closing this issue but feel free to reopen if needed.

**Closed by krynble** 2021-05-25 07:45 UTC
