### ISSUE TITLE
pipedrive oauth2 credential does not handle correctly state variable for app install whe workflows started in pipedrive portal

### ISSUE THREAD

**Issue by thej4ck** [n8n-io/n8n#12137] opened 2024-12-10 15:35 UTC
### Bug Description

if i register the app from pipedrive all work out well.
if i install from pipedrive i obtain an error:
![image](https://github.com/user-attachments/assets/f5942317-6238-48ac-a5bf-599c7c4e947c)

thats becouse the pipedrive documentation wants the state parameter added.

# Debug info

## core

- n8nVersion: 1.69.2
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: bf8c8df7-25d2-4e26-8ffa-96d6773a85b6

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/131.0.0.0 safari/537.36
- isTouchDevice: false

## security

- secureCookie: false

Generated at: 2024-12-10T15:34:52.898Z

### To Reproduce

configure correctly a private app in pipedrive, using n8n.
configure a n8n pipedrive oauth credential. it works.
go to pipedrive custom app installation panel
click on install
you get the error

### Expected behavior

installation workflow closed correctly

### Operating System

browser

### n8n Version

1.69.2

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-12-10 15:35
Hey @thej4ck,

We have created an internal ticket to look into this which we will be tracking as "N8N-7937"

**Comment by Joffcom** [comment] 2024-12-11 10:57
Hey @thej4ck,

At the moment we don't support adding credentials to n8n from outside of n8n like this, The best place to start with this could be as a feature request but for now I will leave this open and let the team who will be looking into this in more detail decide what to do.

**Comment by Joffcom** [comment] 2024-12-17 10:23
Moving to closed for now as working as intended, We only directly support auth initiated from inside n8n.

**Closed by Joffcom** 2024-12-17 10:23 UTC
Labels: in linear
