### ISSUE TITLE
OpenAI Assistant & gpt4-o

### ISSUE THREAD

**Issue by mbakgun** [n8n-io/n8n#9398] opened 2024-05-14 16:13 UTC
### Bug Description

I'm getting an error while requesting the OpenAI Assistant using the gpt-4o model as an assistant with APIv1, because gpt-4o cannot be used with the APIv1 schema.

Problem in node ‘OpenAI Assistant‘
400 The requested model 'gpt-4o' cannot be used with the Assistants API in v1. Follow the migration guide to upgrade to v2: https://platform.openai.com/docs/assistants/migration.

### To Reproduce

To reproduce this problem  you can use this public example: https://n8n.io/workflows/2098-chat-with-openai-assistant-by-adding-a-memory/ 

And please update your model as below : 

<img width="413" alt="Screenshot 2024-05-14 at 6 12 45 PM" src="https://github.com/n8n-io/n8n/assets/8726393/2c72a30b-2ea0-432a-bfc7-231805483f3e">

### Expected behavior

The expected behavior is a working assistant. 

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.39.4

### Node.js Version

18.16.0

### Database

MySQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-05-15 06:30
Hey @mbakgun,

Using the example provided with a GPT4-O model it appears to be working as expected, Looking at your screenshot though rather than using an existing assistant are you trying to make a new one?

I have also tried this and for me it is working in 1.41.0, Are you able to provide an example that reproduces this?

**Comment by mbakgun** [comment] 2024-05-15 06:41
Hi @Joffcom, I'm trying to create a new assistant, you can find the whole settings. 
<img width="1069" alt="Screenshot 2024-05-15 at 8 39 34 AM" src="https://github.com/n8n-io/n8n/assets/8726393/7585c410-d65c-4102-b5f4-3c9eae68c586">



https://github.com/n8n-io/n8n/assets/8726393/9d7ab7ae-fd14-4ae1-b288-1b3f4051f6b9

**Comment by Joffcom** [comment] 2024-05-15 09:30
Hey @mbakgun,

Even following that I am not able to reproduce the issue, Is your OpenAI account fairly new? We are going to need to update the node so I have created `NODE-1350` as the dev ticket to get this updated.

**Comment by mbakgun** [comment] 2024-05-15 11:07
Nope @Joffcom,  I've been around for more than 2 years. I believe @OlegIvaniv's pr addresses the required changes. 
I'll update here as soon as I get that update.

**Comment by Joffcom** [comment] 2024-05-15 12:25
@mbakgun it does indeed, We were chatting about it internally. It is mix of old node and newer n8n version.

**Comment by mbakgun** [comment] 2024-05-15 14:38
Alright, thanks :) I'm looking forward to test it

**Comment by Joffcom** [comment] 2024-05-15 20:19
Opening until the PR is merged and released 🙂

**Comment by gvargas9** [comment] 2024-05-16 18:03
This is working fine. I have tested it.  The only thing that it is still a bug is that every message sent via chat, ends up creating a new Thread.   But this is a separate bug

**Comment by janober** [comment] 2024-05-22 16:09
Fix got released with [`n8n@1.43.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.43.0)

**Closed** 2024-05-29 08:00 UTC
Labels: in linear, Released
