### ISSUE TITLE
Execute Node enters to infinitive loop

### ISSUE THREAD

**Issue by maurimuchico-work** [n8n-io/n8n#5500] opened 2023-02-16 18:56 UTC
**Describe the bug**
First executions from the "Execute Node" button never end.

**To Reproduce**

1. Place a "Set" data transformation node
2. Click on "Execute Node"
3. Execution loops indefinitely
In the following picture you can see the execution running
![image](https://user-images.githubusercontent.com/123373946/219458101-50ecac07-c7a5-431d-bdc1-dda946ff35f1.png)
In the following picture you can see the flow and the label indicating that an execution is running
![image](https://user-images.githubusercontent.com/123373946/219458313-f2c5ada7-a6fe-47d3-96c9-037dfd7ce7fe.png)

**Expected behavior**
If you refresh the n8n site and re-run the flow, then you get the expected behaviour in which the execution ends successfully. 
![image](https://user-images.githubusercontent.com/123373946/219458437-76a57c7f-28ef-46d1-9ac9-56e31843c669.png)

**Environment (please complete the following information):**

- OS: 5.4.219-126.411.amzn2.x86_64
- n8n Version: 0.215.2
- Node.js Version: v16.19.0
- Database system: PostgreSQL
- Operation mode main

**Additional context**
- It also happens with custom full versioned nodes
- It happens whether the flow is saved or not
- The last version in which everything worked well was 0.198.1

**Comment by Joffcom** [comment] 2023-02-20 09:50
Hey @maurimuchico-work,

I have just given this a go on the latest release and I have not been able to reproduce it. Is there maybe more to it other than adding a Set node and hitting Execute Node?

**Comment by craigz** [comment] 2023-02-23 23:04
this may be related to the issue with the latest version 0.217.0 that i just created: issue [5561](https://github.com/n8n-io/n8n/issues/5561).

i had not updated in about 2 weeks, so today was my first time seeing executions start and simply never end, but perhaps it was introduced prior to the latest version as this issue suggests.

**Comment by Joffcom** [comment] 2023-03-01 16:46
Hey @maurimuchico-work,

Can you try the latest release and let me know if this is still an issue for you.

**Comment by Joffcom** [comment] 2023-03-02 13:29
Hey @maurimuchico-work,

That is annoying, I have not been able to reproduce it which makes it tricky to fix. Can you share more about your setup? Docker, NPM, Any reverse proxies or extra caching?

**Comment by Joffcom** [comment] 2023-03-03 21:47
Hey @maurimuchico-work 

I am still unable to reproduce this so I still have the same questions the closer I can mimic your environment the more likely it is that I will be able to reproduce it.

It could be they swapping `N8N_PUSH_BACKEND` to `websocket` will solve it but it is hard to confidently say it will without knowing more. Feel free to try it anyway though.

**Comment by Joffcom** [comment] 2023-03-08 19:06
Hey @maurimuchico-work 

I am out of ideas, can you share your full config and any details on proxies or similar that are set up as well?

I have seen similar issues in the past when nginx is not configured correctly as a reverse proxy.

Did you try connecting directly to the ip of n8n bypassing anything else to see if that works that would maybe help workout where the issue is.

**Comment by Joffcom** [comment] 2023-03-17 22:05
Hey @maurimuchico-work 

I would say if it is working direct the only thing it could be is the proxy config.

I will need to dig through our community forum to see what options have been used in the past.

**Comment by Joffcom** [comment] 2023-03-31 08:25
Hey @maurimuchico-work,

I have not found anything yet, Have you managed to get it working?

**Comment by Joffcom** [comment] 2023-04-07 15:42
Hey @maurimuchico-work,

When you reproduced it locally using docker was that connecting directly to n8n or going through a proxy?

**Comment by Joffcom** [comment] 2023-04-13 07:57
Hey @maurimuchico-work,

I would say if you were not able to reproduce it locally it seems unlikely to be directly related to n8n itself and is more likely to be something specific to the environment.

In this case and as mentioned before I suspect the issue is likely to be around the configuration of the proxy, Looking back at the config it could be the ingress rules are not being picked up properly or wasn't set correctly.

**Comment by Joffcom** [comment] 2023-06-14 16:36
I am going to mark this as closed as it doesn't look to be an application bug and more of a configuration issue, If this is still an issue it would be worth opening a thread on our support forum: https://community.n8n.io

**Closed by Joffcom** 2023-06-14 16:36 UTC
