### ISSUE TITLE
Error Handling Issue in HTTP Request Node during PUT Operation

### ISSUE THREAD

**Issue by domcaram** [n8n-io/n8n#9665] opened 2024-06-07 09:25 UTC
### Bug Description

When attempting to perform a PUT request using the HTTP Request node in n8n, I encounter the following error:

`Cannot read properties of undefined (reading 'error')`

Full Stack Trace:

`TypeError: Cannot read properties of undefined (reading 'error') 
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:666:253 
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1079:20`

Although the PUT request appears to proceed as expected, it seems that the code attempts to read the error property even when there is no error present in the response. This forced reading of the error variable causes the TypeError mentioned above.

### To Reproduce

	1.	Set up an HTTP Request node with a PUT method.
	2.	Execute the workflow.
	3.	Observe the error in the execution logs.

### Expected behavior

The workflow should handle responses without errors gracefully and should not attempt to read the error property when it is undefined.

### Operating System

Debian 12 (Bookworm)

### n8n Version

1.44.1

### Node.js Version

v20.13.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-06-07 09:32
Hey @domcaram,

What other settings do you have in the node? I have just given this a test with the `1.45.0` release and I can't reproduce this but I have seen this happen in `1.45.0` with other nodes as well.

![image](https://github.com/n8n-io/n8n/assets/4688521/bcf717f5-0907-4af7-b933-2c7ebdda260c)

**Comment by domcaram** [comment] 2024-06-07 09:42
Hey @Joffcom,

The only customization I have made is setting the timeout to 50000

Node settings:
![image](https://github.com/n8n-io/n8n/assets/13980865/8c7aa0ce-913b-4265-873e-5e3e8f9f1134)

Thank you

**Comment by domcaram** [comment] 2024-06-07 09:48
@Joffcom i just upgraded from 1.44.1 to 1.45.0.  

HTTP Request node settings:
![image](https://github.com/n8n-io/n8n/assets/13980865/cd01608d-6172-4de8-bcb9-79bc5744d122)

(HTTP Request node version 1 (Latest version: 4.2)

**Comment by Joffcom** [comment] 2024-06-07 09:49
@domcaram I suspect that is node version won't help can you add a new http request node and see if that has the same option.

With the upgrade before you went to 1.44.1 which version were you running?

**Comment by domcaram** [comment] 2024-06-07 09:58
@Joffcom adding a new HTTP Request node shows a slightly different version and module:

![image](https://github.com/n8n-io/n8n/assets/13980865/b3c1d5d4-69e4-4ea9-a6fc-874d311776e7)

To update n8n, I use watchtower, which checks daily for new latest versions. This workflow originates from one of the earliest versions of n8n (possibly 0.2)

I'm now trying with the new version

**Comment by domcaram** [comment] 2024-06-07 10:03
@Joffcom Yes that's probably correct. On 1.42 it was working, I also tried downgrading the image but during the container startup i get an `SQLITE_ERROR`:

`QueryFailedError: SQLITE_ERROR: no such column: WorkflowEntity__WorkflowEntity_shared.userId
    at handler (/usr/local/lib/node_modules/n8n/node_modules/@n8n/typeorm/driver/sqlite/SqliteQueryRunner.js:88:37)
    at replacement (/usr/local/lib/node_modules/n8n/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/usr/local/lib/node_modules/n8n/node_modules/sqlite3/lib/sqlite3.js:15:21)
Error: Exiting due to an error.`

**Comment by domcaram** [comment] 2024-06-07 15:15
Hey @Joffcom,

I just saw that this issues has been fixed and merged in master. May I ask when this will be live?

Thank you

**Comment by Joffcom** [comment] 2024-06-07 15:33
Hey @domcaram,

I suspect there will be a 1.45.1 release at some point, It may be Monday now though.

**Comment by sprankhub** [comment] 2024-06-11 07:44
Any news on 1.45.1, @Joffcom? This is breaking our automations :face_with_peeking_eye:

**Comment by Giorgio-gatti** [comment] 2024-06-11 09:25
Same problem here when use UPDATE operation in SQL from n8n.

`{
  "errorMessage": "Cannot read properties of undefined (reading 'error')",
  "errorDetails": {},
  "n8nDetails": {
    "n8nVersion": "1.44.1 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "TypeError: Cannot read properties of undefined (reading 'error')",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:666:253",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1079:20"
    ]
  }
}`

**Comment by janober** [comment] 2024-06-12 14:05
Fix got released with [`n8n@1.44.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.44.2)

**Comment by Joffcom** [comment] 2024-06-17 14:25
Updating will resolve this, Let me know how you get on after an update and if it is still an issue.

**Closed by Joffcom** 2024-06-17 14:25 UTC
Labels: in linear, Released
