### ISSUE TITLE
Sometimes 404 (Not Found) in Webhooks

### ISSUE THREAD

**Issue by arkhelieldan** [n8n-io/n8n#1257] opened 2020-12-17 14:31 UTC
**Describe the bug**
Performing some tests, I noticed that in the first request made to the Webhook, the error 404 (Not Found) is returned.

After making a new request, response 200 is sent and the Webhook is activated.

To check the error, I used POSTMAN to make sure what was happening, and intermittently the Webhook returned error 404 (Not Found). I used the same configuration described on the page: https://docs.n8n.io/reference/server-setup.html

Here is my docker file:
```

version: "3"

services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - ${DATA_FOLDER}/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "0.0.0.0:5678:5678"
    labels:
      - traefik.enable=true 
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_TUNNEL_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=REMOVED
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=REMOVED
      - DB_POSTGRESDB_PASSWORD=REMOVED
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_FOLDER}/.n8n:/root/.n8n
```

**To Reproduce**
1. CREATE A WEBHOOK
2. TESTS USING POSTMAN TO TRIGGER THE EVENT
3. NUMBER OF TESTS: 10
4. See error 404 (NOT FOUND)

**Expected behavior**
All requests return 200.

**Environment (please complete the following information):**
 - OS: [Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.93.0]

**Additional context**
I'm using in AWS behind Loadbalancer and WAF, but i did tests using DNS pointed directly at the host and i see the same behavior.

**Comment by RicardoE105** [comment] 2020-12-17 23:19
Hello @arkhelieldan 

How are you executing the webhook? are you hitting the executing workflow button? or are you activating the workflow? if you are using the former, it might the issue as it deactivates the webhook after 2 minutes, this is meant for developing and testing purposes. If you want the webhook to not be removed automatically you have to activate the workflow (switch on the top right).

**Comment by arkhelieldan** [comment] 2020-12-18 12:04
Hi @RicardoE105, i activate the Webhook using top button (Workflow is active in production).

**Comment by arkhelieldan** [comment] 2020-12-23 12:31
Hi.
I fixed the issue, the problem it was WAF that not redirect to Webhook endpoint correctly.

**Comment by janober** [comment] 2020-12-23 12:55
So you mean your firewall did block it?

**Comment by janober** [comment] 2020-12-27 22:05
As the problem is fixed and seems like it was not related to n8n do I close this issue for now.

**Closed by janober** 2020-12-27 22:05 UTC
