### ISSUE TITLE
Node-refencing expressions fail to evaluate in loops

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1518] opened 2021-03-07 12:36 UTC
**Describe the bug**

When using a loop; expressions don't always work:

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/193115/110239931-d3f01980-7f49-11eb-937a-0d050aae1000.png">

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/193115/110240026-2e897580-7f4a-11eb-8619-9ceee76702e0.png">

Having the same expression before the loop, works just fine.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.26.0] 0.110.3
 - Node.js Version [e.g. 10.16.0]

**Additional context**

**Comment by janober** [comment] 2021-03-07 12:49
Where is that node "Merge options"? I can not see it in the above screenshot. So I assume it is not part of the loop (unless you did rename it in the meantime). In this case, it makes sense as expressions always reference data from the same execution. Meaning the first time it would work, as then all nodes are in Execution "0" (or in other words executed 1x, in the loop and outside of it) and then on further iterations, the nodes in the loop are in execution `n` and the one outside all still at `0`. 

To reference a specific iteration you can use `$items()` and define that you always want to use the data of the first execution as documented here:
https://docs.n8n.io/nodes/expressions.html#method-items-nodename-string-outputindex-number-runindex-number

Hope that helps!

**Comment by haf** [comment] 2021-03-07 12:51
No, "Merge options" is not in the loop like you successfully deduce.

However, it is part of the same execution of the workflow, so I am doing what you suggest already. Are you saying that $node[...] is keyed to a specific loop iteration and not the global workflow execution instance?

**Comment by janober** [comment] 2021-03-07 12:56
Uh very sorry. I used the wrong term. I did not mean "Execution" I did mean "Run".

Exactly. `$node` always uses the data of the same run. In the first run (0) it will get data of run `0` of other nodes and on further runs it will do the same. That is why it fails as the node outside of the loop will not have any data of other runs (as it did only run 1x).

**Comment by haf** [comment] 2021-03-07 12:57
But the docs say this:

> Works exactly like $item with the difference that it will always return the data of the first output and the last run of the node.

And since that node only has a single run, I don't see why it doesn't contain the first (and last, the only) output?

**Comment by janober** [comment] 2021-03-07 13:01
Ah yes, you are correct! Now thinking back did I actually change that behavior a while ago to work exactly like now documented. 

Can you please provide a simple example workflow? We can then have a look and see what is going wrong there.

**Comment by haf** [comment] 2021-03-07 13:05
I tried a few more permutations with `$items` and got this to work:

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/193115/110240847-22071c00-7f4e-11eb-8407-4586c9d7dcfe.png">

**Comment by haf** [comment] 2021-03-07 13:06
I think the problem is that `$node` behaves like you said, but not like the docs say.

**Comment by janober** [comment] 2021-03-07 13:10
No, it works like documented:
```json
{
  "nodes": [
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{$node[\"Increment\"].data[\"counter\"]}}",
              "value2": 5
            }
          ]
        }
      },
      "name": "IF",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1050,
        500
      ]
    },
    {
      "parameters": {},
      "name": "Start Loop",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        650,
        300
      ]
    },
    {
      "parameters": {
        "values": {
          "number": [
            {
              "name": "counter",
              "value": "={{$node[\"Start Loop\"].json[\"counter\"]+1}}"
            }
          ],
          "string": [
            {
              "name": "initCounter",
              "value": "={{$node[\"Init Counter\"].json[\"counter\"]}}"
            }
          ]
        },
        "options": {}
      },
      "name": "Increment",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        850,
        300
      ]
    },
    {
      "parameters": {
        "values": {
          "number": [
            {
              "name": "counter"
            }
          ]
        },
        "options": {}
      },
      "name": "Init Counter",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        450,
        300
      ]
    },
    {
      "parameters": {
        "functionCode": "const allData = []\n\nlet counter = 0;\ndo {\n  try {\n    const items = $items(\"Increment\", 0, counter).map(item => item.json);\n    allData.push.apply(allData, items);\n  } catch (error) {\n    return [{json: {allData}}];  \n  }\n\n  counter++;\n} while(true);\n\n\n"
      },
      "name": "Merge Data",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        1250,
        500
      ]
    }
  ],
  "connections": {
    "IF": {
      "main": [
        [
          {
            "node": "Start Loop",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Merge Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Start Loop": {
      "main": [
        [
          {
            "node": "Increment",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Increment": {
      "main": [
        [
          {
            "node": "IF",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Init Counter": {
      "main": [
        [
          {
            "node": "Start Loop",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

Can you please create an example workflow that we can debug and fix the issue for your edge-case. Thanks!

**Comment by haf** [comment] 2021-03-07 15:38
Here are the nodes in question:

```

    {
      "parameters": {
        "operation": "executeQuery",
        "query": "=SELECT 'query multiple rows here';"
      },
      "name": "Read country_results_daily",
      "type": "n8n-nodes-base.postgres",
      "typeVersion": 1,
      "position": [
        1540,
        460
      ],
      "credentials": {
        "postgres": "Logary db"
      }
    },

    {
      "parameters": {
        "batchSize": 1,
        "options": {}
      },
      "name": "SplitInBatches",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 1,
      "position": [
        1770,
        460
      ]
    },

    {
      "parameters": {
        "authentication": "oAuth2",
        "operation": "lookup",
        "sheetId": "={{$node[\"Merge options\"].json[\"sheetId\"]}}",
        "range": "='{{$node[\"Merge options\"].json['resultsSheet' + '-' + $json[\"platform\"]] || $node[\"Merge options\"].json['resultsSheet'] || 'Results'}}'!A:F",
        "lookupColumn": "rowId",
        "lookupValue": "={{$json[\"rowId\"]}}",
        "options": {
          "continue": true
        }
      },
      "name": "Existing row",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 1,
      "position": [
        1980,
        170
      ],
      "credentials": {
        "googleSheetsOAuth2Api": "gsheet"
      }
    },

    {
      "parameters": {
        "conditions": {
          "boolean": [
            {
              "value1": "={{Object.keys($node[\"Existing row\"].data).length !== 0}}",
              "value2": true
            }
          ]
        }
      },
      "name": "Existing row?",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        2200,
        170
      ]
    },

    {
      "parameters": {},
      "name": "NoOp already added",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        2450,
        150
      ]
    },

    {
      "parameters": {
        "mode": "passThrough",
        "output": "input2"
      },
      "name": "Choose data",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        2450,
        640
      ]
    },

    {
      "parameters": {
        "authentication": "oAuth2",
        "operation": "append",
        "sheetId": "={{'1CHANGE_MEU' ||$node[\"Merge options\"].json[\"sheetId\"]}}",
        "range": "='{{$items(\"Merge options\", 0, 0)[0].json['resultsSheet' + '-' + $json[\"platform\"]] || $items(\"Merge options\", 0, 0)[0].json['resultsSheet']}}'!A:AZ",
        "options": {
          "valueInputMode": "USER_ENTERED"
        }
      },
      "name": "Write result",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 1,
      "position": [
        2830,
        640
      ],
      "credentials": {
        "googleSheetsOAuth2Api": "gsheet"
      }
    },


```

**Comment by janober** [comment] 2021-03-07 15:55
Thanks, but could you please provide an example we can simply run. So without external dependencies like any kind of database or Google Sheets.

**Comment by haf** [comment] 2021-03-07 22:14
I'm sorry, I don't have time right to help you out more.

**Comment by janober** [comment] 2021-03-07 22:28
Ah OK is understandable.

But because the code you did post is not a valid workflow, and even if it would be, it would be very hard to impossible to reproduce the issue without the context (all the data from DB and Sheets), and because I am so unable to reproduce what you describe, I sadly can not do much more.

I leave the issue open for a while and if nobody else reports anything similar I will close the issue.

**Comment by haf** [comment] 2021-03-11 17:09
I can give you the workflow file privately, if that works for you?

**Comment by haf** [comment] 2021-03-12 15:44
@janober If you would like that, please give me an e-mail I can send them to.

**Comment by janober** [comment] 2021-03-12 16:23
Thanks, did just write you an email.

**Comment by haf** [comment] 2021-03-20 12:10
I gave up trying to reproduce it after 30 minutes: mostly got stuck on how/which nodes to replace my real nodes with.

I suggest you build in a tracing layer e.g. with `@opentelemetry/api`  and simply have us upload the trace here.

**Comment by janober** [comment] 2021-07-11 09:42
Close this issue for now. Once you have a case we can reproduce please comment here we can then open it again.

**Closed by janober** 2021-07-11 09:42 UTC
