### ISSUE TITLE
Error when execute FileTrigger

### ISSUE THREAD

**Issue by jeremybep** [n8n-io/n8n#3647] opened 2022-07-04 07:17 UTC
**Describe the bug**
When i switch to `active` a workflow with FileTrigger n8n can't execute it and crash.

**To Reproduce**
1. Select FileTrigger
2. Set trigger like this
![image](https://user-images.githubusercontent.com/72266507/177101489-11b78ec7-046c-4d47-b0c2-32b6baf3836a.png)

**Expected behavior**
This should trigger file modifications

**Environment (please complete the following information):**
 - OS: windows 10 (latest build)
 - n8n Version 0.184.0
 - Node.js Version 16.14.0
- npm Version 8.3.1

**Additional context**
Console error :
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: UNKNOWN: unknown error, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\Users\jeremyb\AppData\Roaming\npm\node_modules\n8n\node_modules\chokidar\index.js:647:10)
    at NodeFsHandler._boundHandleError (C:\Users\jeremyb\AppData\Roaming\npm\node_modules\n8n\node_modules\chokidar\lib\nodefs-handler.js:303:43)
    at C:\Users\jeremyb\AppData\Roaming\npm\node_modules\n8n\node_modules\chokidar\lib\nodefs-handler.js:137:5
    at foreach (C:\Users\jeremyb\AppData\Roaming\npm\node_modules\n8n\node_modules\chokidar\lib\nodefs-handler.js:41:5)
    at fsWatchBroadcast (C:\Users\jeremyb\AppData\Roaming\npm\node_modules\n8n\node_modules\chokidar\lib\nodefs-handler.js:136:3)
    at FSWatcher.<anonymous> (C:\Users\jeremyb\AppData\Roaming\npm\node_modules\n8n\node_modules\chokidar\lib\nodefs-handler.js:185:9)
    at FSWatcher.emit (node:events:520:28)
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:210:12) {
  errno: -4094,
  syscall: 'watch',
  code: 'UNKNOWN',
  filename: null
}
```

**Comment by jbd7** [comment] 2022-10-18 12:36
This issue showing up with Google helped me restore my n8n, and here's a contribution that possibly relates to the same root cause.

**Context:** After saving a workflow, my n8n container would crash a few seconds after starting, using 90% CPU and ramping to 100%. I couldn't load the n8n web UI.  With sqlite3, I manually set my last workflow to inactive, and I could finally load n8n.

**To Reproduce**: Create a FileTrigger node as on screenshot. Volumes in my env variables are owned by `root`.
![image](https://user-images.githubusercontent.com/13196991/196428449-2814f656-8b6e-4e90-80e5-ece3938ae7e7.png). 

**Expected behavior**: n8n throws an error that it cannot access a given folder, that it doesn't have permissions, ... anything but does not get stuck into a bootloop.

**Environment (please complete the following information):**
- OS : Ubuntu 22, kernel 5.15.0-50-generic 
- n8n Version 0.197.1 installed with Docker

Error trace
```
me@vps315624:/opt/n8n$ sudo docker-compose up
[+] Running 1/0
 ⠿ Container n8n-n8n-1  Created                                                                                   0.0s
Attaching to n8n-n8n-1
n8n-n8n-1  | Initializing n8n process
n8n-n8n-1  | n8n ready on 0.0.0.0, port 3456
n8n-n8n-1  | Version: 0.197.1
n8n-n8n-1  |  ================================
n8n-n8n-1  |    Start Active Workflows:
n8n-n8n-1  |  ================================
n8n-n8n-1  |    - GuiltyWorkflow (ID: 2)
n8n-n8n-1  |      => Started
n8n-n8n-1  |
n8n-n8n-1  | Editor is now accessible via:
n8n-n8n-1  | https://n8n.mydomain.com:3456/
n8n-n8n-1  | node:internal/errors:477
n8n-n8n-1  |     ErrorCaptureStackTrace(err);
n8n-n8n-1  |     ^
n8n-n8n-1  |
n8n-n8n-1  | Error: EACCES: permission denied, watch '/root'
n8n-n8n-1  |     at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
n8n-n8n-1  |     at Object.watch (node:fs:2301:34)
n8n-n8n-1  |     at createFsWatchInstance (/usr/local/lib/node_modules/n8n/node_modules/chokidar/lib/nodefs-handler.js:119:15)
n8n-n8n-1  |     at setFsWatchListener (/usr/local/lib/node_modules/n8n/node_modules/chokidar/lib/nodefs-handler.js:166:15)
n8n-n8n-1  |     at NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/n8n/node_modules/chokidar/lib/nodefs-handler.js:331:14)
n8n-n8n-1  |     at NodeFsHandler._handleDir (/usr/local/lib/node_modules/n8n/node_modules/chokidar/lib/nodefs-handler.js:559:19)
n8n-n8n-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
n8n-n8n-1  |     at async NodeFsHandler._addToNodeFs (/usr/local/lib/node_modules/n8n/node_modules/chokidar/lib/nodefs-handler.js:609:16)
n8n-n8n-1  | Emitted 'error' event on FSWatcher instance at:
n8n-n8n-1  |     at FSWatcher._handleError (/usr/local/lib/node_modules/n8n/node_modules/chokidar/index.js:647:10)
n8n-n8n-1  |     at NodeFsHandler._addToNodeFs (/usr/local/lib/node_modules/n8n/node_modules/chokidar/lib/nodefs-handler.js:637:18)
n8n-n8n-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
n8n-n8n-1  |   errno: -13,
n8n-n8n-1  |   syscall: 'watch',
n8n-n8n-1  |   code: 'EACCES',
n8n-n8n-1  |   path: '/root',
n8n-n8n-1  |   filename: '/root'
n8n-n8n-1  | }
n8n-n8n-1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by Joffcom** [comment] 2023-01-18 13:09
Hey @jeremybep,

Are you still seeing this issue on the latest release?

**Comment by Joffcom** [comment] 2023-06-14 11:49
Marking as closed for now, If this is still an issue let me know and we can open it again.

**Closed by Joffcom** 2023-06-14 11:49 UTC
Labels: node/issue
