### ISSUE TITLE
Anthropic Chat Model LangChain subnode options lacks "Base URL" like Open AI Chat Model

### ISSUE THREAD

**Issue by v-karbovnichy** [n8n-io/n8n#11122] opened 2024-10-06 19:10 UTC
### Bug Description

I am trying to move all Chat models to a proxy provider and cannot do that with Anthropic due to lack of Base URL option.
It's not OpenRouter, so proxied Anthropic API is the same as real Anthropic API, so I can't use "Open AI Chat Model"

### To Reproduce

1. Create new workflow
2. Add "AI Agent" node
3. Add "Anthropic Chat Model" subnode
4. Double-click on "Anthropic Chat Model" subnode
5. Click on "Add option" dropdown button
6. Notice lack of "Base URL" option

### Expected behavior

"Base URL"  option is present

### Operating System

Ubuntu 22.04

### n8n Version

1.59.3

### Node.js Version

idk, I use official docker image for n8n

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-10-06 19:10
Hey @v-karbovnichy,

We have created an internal ticket to look into this which we will be tracking as "GHC-291"

**Comment by v-karbovnichy** [comment] 2024-10-06 19:15
Related codebase:

https://github.com/n8n-io/n8n/blob/7e8955b322b1d2c84c0f479a5977484d8d5e3135/packages/%40n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts#L153-L159

https://github.com/n8n-io/n8n/blob/7e8955b322b1d2c84c0f479a5977484d8d5e3135/packages/%40n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts#L138-L172

**Comment by Joffcom** [comment] 2024-10-06 19:29
Hey @v-karbovnichy 

As this is not a bug I am going to close this issue, we use GitHub issues to track bugs with the application and enhancement / feature requests should be created on the [support forum](https://community.n8n.io) this allows us to see if it is something that the community wants and to prioritise it.

Let me know if you have any questions on this.

**Closed by Joffcom** 2024-10-06 19:29 UTC
Labels: in linear
