### ISSUE TITLE
Bug(Google BigQuery) "Cannot read properties of undefined (reading 'map')"

### ISSUE THREAD

**Issue by HikaruEgashira** [n8n-io/n8n#6411] opened 2023-06-13 01:17 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Server occur `"Cannot read properties of undefined (reading 'map')"`

1. Add Crediential `Google BigQuery OAuth2 API`
2. Create Node `Google BigQuery OAuth2 API`
3. Click Project Select Input

| first network | 1s after |
| --- | --- |
| <img width="1512" alt="スクリーンショット 2023-06-13 10 06 05" src="https://github.com/n8n-io/n8n/assets/39324739/d0c6701f-bff2-405c-a5de-238e4b70508e"> | <img width="1512" alt="スクリーンショット 2023-06-13 10 05 41" src="https://github.com/n8n-io/n8n/assets/39324739/eb898717-4002-469f-b70b-6e0963efe644"> |

**Expected behavior**

**Environment (please complete the following information):**

- OS: n8n.cloud
- n8n Version 0.230.3
- Node.js Version n8n.cloud
- Database system n8n.cloud
- Operation mode own

**Additional context**
If an error occurs when the paginationToken is included, it is likely a bug in the pagination functionality. The pagination process is complex, and we have been unable to identify the issue.

https://github.com/n8n-io/n8n/blob/master/packages/core/src/LoadNodeListSearch.ts

**Comment by Joffcom** [comment] 2023-06-13 07:10
Hey @HikaruEgashira,

I have not been able to reproduce this using our internal BigQuery Account, How many projects are you working with?

**Comment by HikaruEgashira** [comment] 2023-06-13 07:27
Thanks for watching.
Over 60 projects exists.

**Comment by Joffcom** [comment] 2023-06-13 08:33
Hey @HikaruEgashira,

Annoyingly I can only add 50 so I have had to request a limit increase to test this one, I did however update the code locally to only return 10 items on each request to force the pagination to work and that seems to return without issue. The error message you have in the title is the response to the nodes-list-search request?

**Comment by HikaruEgashira** [comment] 2023-06-13 11:45
I apologize for not attaching the screen displaying the error. Yes, you can see the error in the response. The second pagination worked fine this time, but an error occurred on the third request.

<img width="1512" alt="スクリーンショット 2023-06-13 20 41 58" src="https://github.com/n8n-io/n8n/assets/39324739/81abed54-5ece-4128-81f8-e0fdbcbd3471">

**Comment by Joffcom** [comment] 2023-06-13 14:10
That is interesting, Can you tell me what your cloud username is?

**Comment by HikaruEgashira** [comment] 2023-06-14 22:12
[hikae](https://hikae.app.n8n.cloud/)
if other infomation needed, please [contact](mailto:contact@egahika.dev)

**Comment by Joffcom** [comment] 2023-06-16 09:19
Hey @HikaruEgashira,

I have taken a look and can't see any errors in the logs there, It is very odd. It does sound like something is going wrong with the pagination I just can't reproduce it. Hopefully my count will be increased soon so I can test.

**Comment by HikaruEgashira** [comment] 2023-06-16 14:38
@Joffcom 
I have found a reproducible procedure. When you scroll within the screen displaying the skeleton for retrieving the next page, you can observe an error occurring.

**Comment by Joffcom** [comment] 2023-06-16 14:44
@HikaruEgashira

For me when I had it set to 10 the scrolling was working fine, I am wondering if it is something with the amount or if there is something we are not expecting like maybe some special characters.

**Closed** 2023-10-15 15:40 UTC
