### ISSUE TITLE
Issues with Executions

### ISSUE THREAD

**Issue by jwaldrip** [n8n-io/n8n#1476] opened 2021-02-22 15:47 UTC
**Describe the bug**
When upgrading to use a redis queue, we get issues with executions.

**To Reproduce**
1. Go to a workflow
2. Click on start workflow
3. (nothing happens)
4. Click stop (error: There was a problem stopping the execution)
5. Goto execution
6. There was a problem loading the data:
syntax error at or near ")"

**Expected behavior**
I expect to see executions work.

**Environment (please complete the following information):**
 - n8n Version [e.g. 0.109.0]
 - Node.js Version [e.g. 14.x.x]

**Additional context**
The same final error message happens when trying to view the executions list.

**Comment by janober** [comment] 2021-02-22 15:49
Thanks a lot for reporting. We will try reproduce and fix.

**Comment by jwaldrip** [comment] 2021-02-22 18:20
Is it okay to run multiple main processes in n8n, or should there only be one main process and 1 or more workers?

**Comment by janober** [comment] 2021-02-22 22:07
No there is only one main process allowed and 1 or more workers.
You can find the documentation here:
https://docs.n8n.io/reference/scaling-n8n.html

**Comment by krynble** [comment] 2021-02-23 09:40
Hey @jwaldrip I am on this issue now.

I tried manually running a workflow and it is working fine.

Found an issue when trying to stop workflows that I will work on now, but the behavior you mentioned where nothing happens I was unable to reproduce.

Can you share some details about the workflow you are trying to reproduce?

**Comment by jwaldrip** [comment] 2021-02-23 22:41
@krynble I am hitting `/rest/executions-current?filter=%7B%7D` which is what the frontend is hitting. I am then getting this error:

```
{
"code": 0,
"message": "syntax error at or near \")\"",
"stack": "QueryFailedError: syntax error at or near \")\"\n    at new QueryFailedError (/usr/local/lib/node_modules/n8n/node_modules/typeorm/error/QueryFailedError.js:11:28)\n    at PostgresQueryRunner.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:247:31)\n    at step (/usr/local/lib/node_modules/n8n/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)\n    at Object.throw (/usr/local/lib/node_modules/n8n/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)\n    at rejected (/usr/local/lib/node_modules/n8n/node_modules/typeorm/node_modules/tslib/tslib.js:113:69)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
}
```

**Comment by krynble** [comment] 2021-02-24 10:10
Hello @jwaldrip 

Thanks for the information you provided. I found the issue about the executions list and also fixed an issue with stopping workflows.

Sadly I have no idea what might be happening with the start execution manually issue as this is something that was not modified with the updates to run with queues.

Pull requests https://github.com/n8n-io/n8n/pull/1483 and https://github.com/n8n-io/n8n/pull/1484

About the manual execution, can I ask you for some more information? Can you provide me the details of the request that happens when you click the `Execute Workflow` button from your browser's Developer Console?

**Comment by jwaldrip** [comment] 2021-02-24 15:21
@krynble It seems to have resolved itself with the correct clustering setup. When I run a single main and multiple worker and webhook processes, it works fine.

**Comment by krynble** [comment] 2021-02-24 15:38
Awesome! Thanks for the updates @jwaldrip 

I will be closing this issue for now then as the fixes mentioned will be released on the next releases.

**Closed by krynble** 2021-02-24 15:38 UTC
