### ISSUE TITLE
Webhook Node Bug: Authentication Defaults to 'Header Auth' Across Workflows

### ISSUE THREAD

**Issue by Droid-box** [n8n-io/n8n#11880] opened 2024-11-25 16:06 UTC
### Bug Description

I found a bug in the webhook node. After adding a new credential for webhook authentication ("Header Auth"), it worked fine initially. However, now all other webhook triggers, even in different workflows, default to "Header Auth" for authentication, even if they were previously set to "None." I’ve manually changed them back to "None," but they keep reverting to "Header Auth."

### To Reproduce

1. Create a new workflow.  
2. Add three webhook nodes and set the authentication for two of them to "None."  
3. Open one of the webhook nodes and:  
   - Set the authentication to "Header Auth."  
   - Create a new credential for "Header Auth" in the credentials section.  
   - Test the webhook in Postman using the created credential, testing both "Test URL" and "Production URL."  
4. Save the workflow.  
5. Exit the workflow and reopen it.  
6. Check the two other webhook nodes to see if their authentication settings ("None") have been overwritten to "Header Auth."  
7. Check other workflows using webhook nodes to confirm if their authentication settings have also been overwritten.  
8. Notice that despite resetting the affected nodes back to "None," they continue to revert to "Header Auth" after saving and reopening the workflow.  

### Expected behavior

Webhook nodes should retain their specified authentication settings without being overwritten. When a node is set to "None," it should remain as "None" regardless of changes made to other webhook nodes or the addition of new credentials. This behavior should persist after saving, exiting, and reopening the workflow, and should not affect other workflows or nodes.

### Operating System

Not sure. I used railway.app n8n template

### n8n Version

1.65.2

### Node.js Version

Not sure. I used railway.app n8n template

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-25 16:06
Hey @Droid-box,

We have created an internal ticket to look into this which we will be tracking as "GHC-496"

**Comment by Joffcom** [comment] 2024-11-25 16:10
Hey @Droid-box,

Can you try updating to 1.69.1 and let me know if you have the same issue? We have had other reports of this but have not been able to reproduce it and it has not been reported for any recent versions.

**Comment by Joffcom** [comment] 2024-11-26 08:37
Moving to closed as likely a duplicate of #11575

**Closed by Joffcom** 2024-11-26 08:37 UTC
Labels: in linear
