### ISSUE TITLE
[RabbitMQ Trigger] Not close connection at "Stop Listening"

### ISSUE THREAD

**Issue by jmtt89** [n8n-io/n8n#9159] opened 2024-04-17 19:20 UTC
### Bug Description

On Rabbit Management UI i see creating a new connection every time i click the "Test Step" and  it does not close when click "Stop Listening" 

### To Reproduce

1. Create Trigger RabbitMQ
2. Create Queue on RabbitManagement (All Defaults)
3. Click on "Test Step"
4. Click on "Stop Listening"
5. Click on "Test Step" again
6. Check the total number of connections (2)

### Expected behavior

close connection with rabbit every time i stop listening.

### Operating System

Kubernetes

### n8n Version

image docker.n8n.io/n8nio/n8n 

### Node.js Version

image docker.n8n.io/n8nio/n8n

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-04-18 14:34
Hey @jmtt89,

Thanks for the report, I have managed to reproduce this and have created `NODE-1306` as the internal ticket to fix it.

**Comment by luizeof** [comment] 2024-04-25 13:22
Hi @Joffcom , how are you?

Could you tell me if this issue is related to the fact that RabbitMQ Trigger no longer fetches items from the queue with the execute button?

When in production, it works normally.

But when pressing the execute button to test, the rabbit trigger node stays in an infinite loop and does not continue the workflow.

I have noticed this from version 0.36 onwards.

**Comment by jmtt89** [comment] 2024-04-25 15:11
Hi, I think it is because every time you click "test" you open a new connection, in Rabbitmq the messages are not delivered repeatedly to the consumers, they are only delivered to one of them (not necessary the last created)

**Comment by luizeof** [comment] 2024-04-25 16:27
> Hi, I think it is because every time you click "test" you open a new connection, in Rabbitmq the messages are not delivered repeatedly to all conections, they are only delivered to one of them (not necessary the last created)

Thank you very much, so I believe it is related.

**Comment by Joffcom** [comment] 2024-04-25 20:27
Yeah it could be related, the node really needs some updating.

**Comment by Joffcom** [comment] 2024-07-15 07:39
Hey @jmtt89,

Good news, It looks like the main connection issue you reported with this has been resolved in `1.50.0`. I have done some testing this morning and it appears to still be present in `1.49.0` so I suspect we changed something in the core in the last version which has resolved this.

Can you update and let me know if you see the same issue.

**Comment by Joffcom** [comment] 2024-08-20 13:43
Moving to closed for now as we believe this is solved.

**Closed by Joffcom** 2024-08-20 13:43 UTC
Labels: in linear
