### ISSUE TITLE
Gotify does not enable markdown, cannot configure API or provide custom fields

### ISSUE THREAD

**Issue by disconn3ct** [n8n-io/n8n#8433] opened 2024-01-24 17:10 UTC
**Describe the bug**
Markdown is listed as enabled [here](https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.gotify/) but it does not include the required `extras` data, nor expose a way to do so. More broadly, gotify expects users to use the `extras` block for any custom information related to the message but the plugin does not allow it.

**To Reproduce**

1. Enable gotify and wire it to an instance
2. Send a message containing markdown, or attempt to set any extras fields (eg `extras.client::notification.bigImageUrl`)
3. See unparsed text in the web UI and the android app, no icons, etc.

**Expected behavior**
It should be possible to pass custom fields to the request. By default, the extras field should enable Markdown as indicated by the docs.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 1.0.1]
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Gotify/Gotify.node.ts#L90 defines the fields, and https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Gotify/Gotify.node.ts#L178 uses them.

The default additionalFields should include:
```json
"extras": {
  "client::display": "text/markdown"
}
```

**Comment by Joffcom** [comment] 2024-01-24 17:23
Hey @disconn3ct,

I can't see markdown mentioned on that page but this sounds like a feature request to me and not a bug.

Would you be able to a feature request on the community support forum and we can prioritise adding this based on community feedback.

Alternatively if you want to add this feature you can put in a PR for it.

Let me know if you have any questions on this.

**Comment by disconn3ct** [comment] 2024-01-24 18:29
Correction. It is listed directly in the node UI.
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Gotify/Gotify.node.ts#L87
This is not a feature request.

**Comment by Joffcom** [comment] 2024-01-24 19:58
Hey @disconn3ct,

So it is, In that case I will make sure markdown is working in the morning.

**Comment by Joffcom** [comment] 2024-01-25 12:06
Hey @disconn3ct,

I have popped in a PR which will fix the markdown issue, This PR adds a new option that you can set to specify if it is markdown or plain.

**Comment by janober** [comment] 2024-02-02 13:24
Fix got released with [`n8n@1.27.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.27.2)

**Closed** 2024-02-02 16:35 UTC
Labels: Released
