### ISSUE TITLE
schudule triggers trigger multiple times and I am getting this weird error about google sheets please fix

### ISSUE THREAD

**Issue by machiavelliking** [n8n-io/n8n#12378] opened 2024-12-26 17:07 UTC
### Bug Description

<img width="1445" alt="Screenshot 2024-12-26 at 11 58 26 AM" src="https://github.com/user-attachments/assets/5f6fc5f2-29dc-4002-9365-633a449c8b09" />
i get this error everytime I try to save the workflow can someone help please 

### To Reproduce

create a workflow and add a google sheetGoogle

### Expected behavior

wont let me save the the workflow 

### Operating System

mac

### n8n Version

1.71.3

### Node.js Version

what?

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-12-26 17:07
Hey @machiavelliking,

We have created an internal ticket to look into this which we will be tracking as "N8N-8013"

**Comment by janober** [comment] 2024-12-26 18:59
Can you please clarify what the actual problem is. Right now the title and the description seem to describe two totally different problems.

Additionally  does the error message make sense if the ID is not valid, which seems likely. Can you please ensure it is valid. If you are not able to find a valid ID, disable the workflow. Then saving will also be possible with an invalid ID.

Are you setting the ID manually or do you set it via the selector? With the selector it should always set a valid ID as it retrieves it the ID via the API.

**Comment by machiavelliking** [comment] 2024-12-26 22:09
Thanks for getting back to me. I am not using ids rather getting the sheet
I want from a list. I am not sure what’s happening.

Also whenever I do a scheduled job I.e schedule a job to run at a
particular time. It triggers multiple times I saw someone posted this error
last year but it has not been resolved.

**Comment by janober** [comment] 2024-12-26 22:13
Thanks a lot for your response. Could you please share the workflow JSON. Thanks!

**Comment by machiavelliking** [comment] 2024-12-26 23:30
here you go

**Comment by janober** [comment] 2024-12-27 07:04
Sorry, but there is nothing. Please answer via GitHub instead of email.

**Comment by janober** [comment] 2024-12-27 13:50
We did not get it. For that reason, I suggested to use GitHub and not email.

Generally, is the chance high that it is not a bug but rather a different problem. So, in this case, would also GitHub be wrong and our forum should be used anyway. For that reason, do I close this issue until it is confirmed that it is actually a bug.

Our forum can be found here: [community.n8n.io](https://community.n8n.io/)
There is also the chance much higher that you will get help with your issue faster. Please ensure to directly share your workflow JSON. Thanks!

**Closed by janober** 2024-12-27 13:50 UTC
Labels: in linear

**Comment by machiavelliking** [comment] 2024-12-27 15:09
[send_session_reminder_messages.json](https://github.com/user-attachments/files/18261261/send_session_reminder_messages.json)

**Comment by machiavelliking** [comment] 2024-12-27 15:09
are you able to see it now?

**Comment by machiavelliking** [comment] 2024-12-27 16:20
hi in addition I am getting this weird rate limit but we have only used 14% of your monthly limit your quick response to this will be greatly appreciated 
<img width="1210" alt="Screenshot 2024-12-27 at 11 17 55 AM" src="https://github.com/user-attachments/assets/8d80c7e9-194d-4df7-9fd5-226b02976adc" />
<img width="1445" alt="Screenshot 2024-12-27 at 11 16 54 AM" src="https://github.com/user-attachments/assets/8d72d432-412e-45e4-a354-d34c2b01a69d" />

**Comment by machiavelliking** [comment] 2024-12-31 15:08
Will be nice to at least response smh. Worst customer service ever

Marcus King, CTO
Lavni <https://mylavni.com>
