### ISSUE TITLE
bootstrap doesn't work with npm 7 peerDependency changes

### ISSUE THREAD

**Issue by frane** [n8n-io/n8n#1149] opened 2020-11-11 09:47 UTC
**Describe the bug**
The current setup seems not to be compatible with npm 7 peerDependency changes (see: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major).
```
$ npm run bootstrap

> bootstrap
> lerna bootstrap --hoist --no-ci

info cli using local version of lerna
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 6 packages
lerna WARN EHOIST_PKG_VERSION "n8n-editor-ui" package depends on uuid@^8.1.0, which differs from the hoisted uuid@^3.4.0.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! npm install exited 1 in 'n8n'
lerna ERR! npm install stderr:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: ts-node@8.10.2
npm ERR! node_modules/ts-node
npm ERR!   ts-node@"^8.9.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional ts-node@">=9.0.0" from jest-config@26.6.3
npm ERR! node_modules/jest-config
npm ERR!   jest-config@"^26.6.3" from @jest/core@26.6.3
npm ERR!   node_modules/@jest/core
npm ERR!     @jest/core@"^26.6.3" from jest@26.6.3
npm ERR!     node_modules/jest
npm ERR!       jest@"^26.4.2" from the root project
npm ERR!       1 more (ts-jest)
npm ERR!     1 more (jest-cli)
npm ERR!   jest-config@"^26.6.3" from jest-cli@26.6.3
npm ERR!   node_modules/jest-cli
npm ERR!     jest-cli@"^26.6.3" from jest@26.6.3
npm ERR!     node_modules/jest
npm ERR!       jest@"^26.4.2" from the root project
npm ERR!       1 more (ts-jest)
npm ERR!   2 more (jest-runner, jest-runtime)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**To Reproduce**
1. Freshly clone the n8n repo
2. `npm run bootstrap`

**Expected behavior**

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - n8n Version: 0.92.0 / latest master
 - Node.js Version: node: 15.1, npm: 7.0.8

**Additional context**
Using the `--legacy-peer-deps` setting or rather setting an .npmrc with `npm config set legacy-peer-deps true` temporarily fixes the issue.

**Comment by SvenBayer** [comment] 2020-11-14 12:02
I can confirm this error, however with CDK. https://github.com/aws/aws-cdk
I think this is related specifically to the jest testing library. https://github.com/facebook/jest/tree/master/packages/jest-config
I created an issue here. Hope this is the right location:
https://github.com/facebook/jest/issues/10820

**Comment by rarkins** [comment] 2021-03-03 10:34
I had a similar case which was resolved by running `hash -r` after `npm i -g npm`. The problem was that bash cached the old path for `npm` and `npx`, and `hash -r` clears that cache.

**Comment by carlocorradini** [comment] 2021-03-12 11:34
> --legacy-peer-deps

Same issue here.

Any update? 🙄

**Comment by Vin0uz** [comment] 2021-04-11 17:17
Same here, with Node 15 and npm 7.

Should it be added in the contributing guide as a temp fix, or at least inform about this problem ? (It would have saved me from searching a fix :p)

**Comment by nsomaru** [comment] 2021-07-13 10:02
Similar issue:
```
lerna notice cli v4.0.0                                                                                                    
lerna info versioning independent                                                                                          
lerna info Bootstrapping 6 packages                                                                                        
lerna WARN EHOIST_PKG_VERSION "n8n-node-dev" package depends on tmp-promise@^2.0.2, which differs from the hoisted tmp-promi
se@^3.0.2.                                                                                                                 
lerna info Installing external dependencies                                                                                
lerna info hoist Installing hoisted dependencies into root                                                                 
lerna info hoist Pruning hoisted dependencies                                                                              
lerna info hoist Finished pruning hoisted dependencies                                                                     
lerna ERR! npm install exited 1 in 'n8n'                                                                                   
lerna ERR! npm install stderr:
npm ERR! code ERESOLVE                                                                                                      
npm ERR! ERESOLVE unable to resolve dependency tree                                                                         
npm ERR!                                                                                                                    
npm ERR! While resolving: n8n@undefined                                                                                     
npm ERR! Found: eslint@6.8.0                                                                                                
npm ERR! node_modules/eslint                                                                                                
npm ERR!   eslint@"^6.8.0" from the root project                                                                            
npm ERR!   peer eslint@">=6.2.2" from @vue/eslint-config-standard@5.1.2                                                     
npm ERR!   node_modules/@vue/eslint-config-standard                                                                         
npm ERR!     @vue/eslint-config-standard@"^5.0.1" from the root project                                                     
npm ERR!   2 more (eslint-plugin-import, eslint-plugin-node)                                                                
npm ERR!                                                                                                                    
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.0.0" from eslint-plugin-promise@5.1.0 
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   peer eslint-plugin-promise@">= 4.2.1" from @vue/eslint-config-standard@5.1.2
npm ERR!   node_modules/@vue/eslint-config-standard
npm ERR!     @vue/eslint-config-standard@"^5.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/n8n/.npm/eresolve-report.txt for a full report.
```

**Comment by janober** [comment] 2021-07-13 12:33
@nsomaru and the above-mentioned solution or using Node.js@14 and npm@6 did not work for you?

**Comment by nsomaru** [comment] 2021-07-25 04:47
@janober I'm no expert with nodejs, sorry. I google brute-forced a solution and unfortunately it seems like when tmux crashes you lose history and my host decided to reboot at some point.

**Comment by krynble** [comment] 2021-08-10 12:26
Hello! I recently came back to investigate this issue and it seems like a problem with Vue.js.

Updating it causes other bigger issues and it's part of our roadmap but not in an immediate future.

For now, if you're having this issue I would suggest using the temporary fix suggested by @frane  which is using `npm config set legacy-peer-deps true` or just using our officially supported versions which are Node.js 14.x and npm 6.x.

**Closed by krynble** 2021-08-10 12:26 UTC
