### ISSUE TITLE
If get unexpected behavour and Microsft SQL wrong return

### ISSUE THREAD

**Issue by Ofabiojvalentim** [n8n-io/n8n#3418] opened 2022-06-02 03:39 UTC
If you execute this query for exemple: select name, phone from users where phone = 'phonenumber' and that returns (this output item is empty) then if statement bring me two branch either true and false

![image](https://user-images.githubusercontent.com/106720178/171547812-8b5b44dd-f0ec-4dc1-8d6a-37e01f431f40.png)

if you see on this pic  value1 is missing reference because Microsft SQL node returns syntactically wrong answer, correct is a row with columns and empty values in each column

**Comment by xewonder** [comment] 2022-06-07 16:07
Seems that n8n is not very good at SQL!  
#3425

**Comment by Joffcom** [comment] 2022-06-15 09:43
Hey @Ofabiojvalentim,

Do you have a workflow you can share that reproduces this issue?

**Comment by Joffcom** [comment] 2023-01-18 11:34
Hey @Ofabiojvalentim,

For now I am going to mark this as closed as I was not able to reproduce the issue and there wasn't a sample workflow provided.

I suspect there may have been a merge node involved somewhere or something was a bit odd in the output, If you are able to reproduce this still on the latest release let me know and we can get this opened.

**Closed by Joffcom** 2023-01-18 11:34 UTC
