### ISSUE TITLE
Dragging around new canvas no longer works

### ISSUE THREAD

**Issue by alan-visionreach** [n8n-io/n8n#11961] opened 2024-11-28 18:53 UTC
### Bug Description

On the new canvas, when holding CTRL, the hand appears but unable to move around the canvas

### To Reproduce

1. Open workflow editor
2. Hold CTRL key
3. Click and hold mouse
4. Move mouse - the canvas display does not move

### Expected behavior

The canvas to move with the mouse as with the old canvas

### Operating System

Ubuntu Linux 22.10

### n8n Version

1.69.2

### Node.js Version

18.7.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-11-28 18:54
Hey @alan-visionreach,

We have created an internal ticket to look into this which we will be tracking as "GHC-525"

**Comment by alan-visionreach** [comment] 2024-11-28 18:56
Notice this has already been recorded in other issues.

**Comment by tomi** [comment] 2024-11-29 09:45
Duplicate of #11940 --> Closing

**Closed by tomi** 2024-11-29 09:45 UTC
Labels: in linear

**Comment by tomi** [comment] 2024-11-29 09:50
Actually duplicate of #11961
