### ISSUE TITLE
Workflow Executions filtering doesn't work

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#3036] opened 2022-03-24 08:32 UTC
**Describe the bug**

Especially when many versions have been executed (500) it happens to me very often that I can no longer find a workflow. (a workflow runs with me which starts after and after about 500 other workflows).
For this I like to use:
![grafik](https://user-images.githubusercontent.com/44057030/159873600-2ac502c2-3f7e-4353-8bac-62ddae19e5ec.png)

**To Reproduce**

Start a worklfow that starts many other workflows over a long time and try to filter.
The database contains this information.

**Expected behavior**

Currently, an extra column in the database with: workflow id might be useful.

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version: 0.168.2
 - Node.js Version: v17.5.0
 - Database system: postgres
 - Operation mode: main

**Comment by Joffcom** [comment] 2022-03-29 10:47
Hey @lublak,

I have a workflow running now to try and reproduce this one, One question I have while it is running... Is this a bug or more of a usability problem?

**Comment by lublak** [comment] 2022-03-30 06:53
Hey Joff,

currently I don't remember how I produced it.
Basically ran workflow which started another workflow.

![grafik](https://user-images.githubusercontent.com/44057030/160768821-19de0c88-5614-41ea-81ae-5c4d286baa92.png)

I think these were the previous settings?
In any case, the "running" was not displayed.
That it is deleted with a success of course is clear.

![grafik](https://user-images.githubusercontent.com/44057030/160769243-bfa34f9f-270e-49b8-af60-82ea6062f480.png)

I will try again this weekend if necessary. Since this process takes a long time and I have to empty the system before.

**Comment by branch3** [comment] 2022-04-08 13:48
Hi there, I don't know if the little issue I'm seeing is quite the same : 
When filtering by workflow, the Status filter doesn't load "Running" or "waiting" workflows. It shows them on the counter on the top left, but not in the execution list.
Maybe it's because they are some old executions ?
See picture
![image](https://user-images.githubusercontent.com/11662436/162448854-c59af3a8-c95e-47e2-8a5a-a35a84b32b7c.png)

**Comment by Joffcom** [comment] 2022-04-08 17:08
@branch3 does it show finished? There was a bug fixed in 171.1 I think that fixes in progress executions from showing.

**Comment by janober** [comment] 2022-10-01 15:23
As we did not get an answer for 6 months and there is a good chance this issue got resolved already do I close this ticket.

**Closed by janober** 2022-10-01 15:23 UTC
