### ISSUE TITLE
Slack - Update Status erroring with message moment_1.default.tz is not a function

### ISSUE THREAD

**Issue by rorpage** [n8n-io/n8n#8336] opened 2024-01-15 14:10 UTC
**Describe the bug**
When executing the Slack node to Update Status, there is an error that says: `ERROR: moment_1.default.tz is not a function`. I believe this is similar to #8184.

**To Reproduce**
Try to update Slack Status:
  1. Include the Slack node in a workflow
  2. Set the operation to "Update User's Profile"
  3. Specify an expiration time or not, both cause the issue.
  4. When executing, view the error: `TypeError: moment_1.default.tz is not a function`

**Expected behavior**
This was working before an update to Moment and would set Slack statues appropriately.

**Environment (please complete the following information):**
    - OS: Linux (Docker Container from Docker hub)
    - n8n Version: 1.22.6 (and previous ones down to .3)
    - Node.js Version: v18.18.2 (Docker Container from Docker hub)
    - Database system: SQLite
    - Operation mode: left untouched

**Additional context**
None, thanks!

**Comment by Joffcom** [comment] 2024-01-15 14:14
Hey @rorpage,

I have just given this a go in 1.24.0 and I was not able to reproduce it, Can you try updating and let me know if the newer version is working for you.

**Comment by rorpage** [comment] 2024-01-15 14:21
@Joffcom Absolutely, trying it now! I will report back shortly.

I didn't see a PR that resembled #8185 for the Slack node so I thought I'd give a fix a try, but if it's working in a newer version, then that's awesome!

**Comment by netroy** [comment] 2024-01-15 14:26
I believe this is very edge-case issue where the `Slack` node is getting loaded into memory before any other part of the code has had the opportunity to load `moment-timezone`.

#8185 Fixed this for the Schedule node. But, looks like we need to completely remove `import moment from 'moment'` to make sure this edge-case never happens. #8337 will do that.

**Comment by rorpage** [comment] 2024-01-15 14:28
@netroy You're too fast! :D Thanks for doing that!

@Joffcom I was able to reproduce it in 1.24.0 just now.

**Comment by netroy** [comment] 2024-01-15 15:48
> I'm on Windows and did one have documentation update

Did you by any change run the `corepack` command in the `packages/cli` folder instead of the repo root folder ?

**Comment by rorpage** [comment] 2024-01-15 16:00
I did not. I was in the root folder. Should I have? Did I miss a step?

**Comment by rorpage** [comment] 2024-01-16 13:35
Confirmed to work with 1.24.1. Thank you all!

**Comment by Joffcom** [comment] 2024-01-16 16:01
Hey @rorpage,

That is good to hear, I will get this marked as closed.

**Closed by Joffcom** 2024-01-16 16:01 UTC
