### ISSUE TITLE
webhooks becoming unhooked

### ISSUE THREAD

**Issue by rendervis** [n8n-io/n8n#1873] opened 2021-06-08 06:38 UTC
**Describe the bug**
Trigger workflow with Cron, mode set on "Every day", returns from time to time for no apparent reason:

ERROR: UNKNOWN ERROR
  {
  "status": "rejected",
  "reason": {
  "name": "StatusCodeError",
  "statusCode": 404,
  "message": "404 - {"code":404,"message":"The requested webhook \"POST webhook-name  " is not registered."
  }
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Save new Workflow with Cron'
2. Click on 'Activate'
3. ... wait for it

**Expected behaviour**
Trigger other workflows on a daily basis.

**Environment (please complete the following information):**
 - OS:  macOs Big Sur 11.3
 - n8n Version 0.104.2
 - Node.js Version  14 
 - Database system  SQLite 
 - Operation mode   own

**Comment by janober** [comment] 2021-06-09 00:17
Thanks for reporting.

That is honestly the first time I hear about that. Please make first sure, to update to the latest version as yours is already 4.5 months old (the current one is 0.123.1). If that issue still exists please report back. Thanks!

**Comment by mvhirsch** [comment] 2021-06-09 12:35
@rendervis do you run in worker-mode? There was a bug (already fixed in newer versions) concerning unregistering webhooks on worker-shutdowns.

**Comment by rendervis** [comment] 2021-06-09 12:55
@janober updated to the latest version

@mvhirsch  I have a trigger Cron with mode set to "Every day" and it's triggering 2 other workflows. They are all active and working properly. Except for the times the triggerWorkflow it's not finding the workflows it supposed to trigger.
Thanks for responding.
Will keep  you posted

**Comment by janober** [comment] 2021-06-10 03:32
Even if you do not run in "queue" mode could what @mvhirsch mentioned still be the problem. If multiple n8n instances overlap (like if you run in k8s, docker-swarm, ... and if you have it setup to first start a new instance before killing the existing fone) then the instance which shuts down, would delete the webhooks from the database which would then leave the other one without registered webhooks.

**Comment by haf** [comment] 2021-06-10 07:02
@rendervis The version you mention is the cli version in package.json that we use for import/export :) The server is the most recent version from three days ago.

**Comment by haf** [comment] 2021-06-10 07:05
@janober Does this mean you require n8n to run as a statefulset? We do run it as a Deployment, and this means that while restarting nodes and such, there are briefly two overlapping instances.

**Comment by janober** [comment] 2021-06-12 18:34
No need to extra setup a scaling n8n. You can also just set the environment variable [`N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN`](https://docs.n8n.io/reference/scaling-n8n.html#avoiding-downtime) to stop n8n from deleting the webhooks. Additionally is it possible that some workflows run twice. If you have for example a Cron-Trigger node setup to trigger at the time you have two instances running at the same time will it trigger twice.

**Comment by haf** [comment] 2021-06-13 19:00
Opinion: It would be more architecturally sound to do a leader election for the scheduling rather than descheduling the webhooks. 

We will look into the env bar. Thanks 🙏!

**Comment by janober** [comment] 2021-06-13 20:30
Ah yes, totally agree that would be much better and would have many advantages. The same is sadly also true for many things in n8n and any other project I know.

The problem is just that all of that also has to get designed, implemented, tested, maintained, ... which all takes considerable time and resources and there are just so many battles you can fight in parallel. This is one we did not want to start yet but has to be fought at some point for sure.

**Comment by janober** [comment] 2021-08-08 09:53
Closing this issue as I see it currently more as a feature request than a bug. Overlapping instances (or blue-green deployments) are currently (will change in the future) simply not supported right now.

**Closed by janober** 2021-08-08 09:53 UTC
