### ISSUE TITLE
postgres insert node should not required ID to be set

### ISSUE THREAD

**Issue by bamboowonder** [n8n-io/n8n#7441] opened 2023-10-13 17:20 UTC
**Describe the bug**
the postgres insert node requires the primary key (id) field to be set.  this causes issues when id are auto-incremented or otherwise set automatically by the database on insert.
it would seem that ID should be required only for update or upsert.

**To Reproduce**

1. add a postgres node, insert mode
2. use manual mapping
3. note that the primary key / id field cannot be removed

**Expected behavior**
do NOT required primary key / id on insert to be set.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version 1.8.2
- docker
- Database system:  postgres 15

**Comment by Joffcom** [comment] 2023-10-13 18:05
Hey @bamboowonder 

Thanks for the report, it looks like this is a duplicate of #7084.

I am going to mark this as closed and we can focus on the other issue.

**Closed** 2023-10-13 18:05 UTC
