### ISSUE TITLE
Spotify get users playlists

### ISSUE THREAD

**Issue by larsassink** [n8n-io/n8n#12102] opened 2024-12-09 11:03 UTC
### Bug Description

In the spotify node, I am unable to get all the user's playlists. I am getting hit with this error:

Cannot read properties of null (reading '$error')

### To Reproduce

1. Add spotify node
2. Select "get user's playlists"
3. Select return all
4. Test step

### Expected behavior

It always worked and listed all the playlists

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.70.3

### Node.js Version

18.17.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-12-09 11:03
Hey @larsassink,

We have created an internal ticket to look into this which we will be tracking as "GHC-588"

**Comment by netroy** [comment] 2024-12-09 11:06
This is a duplicate of #12026, and will be fixed in #12080.

**Closed by netroy** 2024-12-09 11:06 UTC
Labels: in linear

**Comment by larsassink** [comment] 2024-12-09 12:35
Thanks @netroy.
