### ISSUE TITLE
Workflow could not be activated: "Could not get parameter"

### ISSUE THREAD

**Issue by rogaha** [n8n-io/n8n#10694] opened 2024-09-05 14:45 UTC
### Bug Description

When i try to activate it the following message pops up:
Workflow could not be activated: There was a problem activating the workflow: "Could not get parameter"
<img width="700" alt="Screenshot of Google Chrome at Sep 5, 2024 at 11_41_47 AM" src="https://github.com/user-attachments/assets/65c472d0-f0af-4e3b-9b27-151bbf7e27ca">

### To Reproduce

Click on the activate button

### Expected behavior

Activated workflow

### Operating System

MacOS

### n8n Version

1.58.0

### Node.js Version

18.16.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment] 2024-09-05 14:46
Hey @rogaha,

We have created an internal ticket to look into this which we will be tracking as "GHC-206"

**Comment by netroy** [comment] 2024-09-05 16:59
can you please share the workflow to reproduce this 🙏🏽 ?

**Comment by meJeppoy** [comment] 2024-09-05 17:13
Hi, I'm getting this same error on a recently created automation. I'm also using a self-hosted instance of n8n via Render. I've synced my forked version of n8n via my render UI. In testing mode, it seems everything in my workflow is working fine but I'm not able to activate it as this same error will pop-up. Checked all credentials and instances and all is working fine while in testing mode.
![image](https://github.com/user-attachments/assets/05797f56-196e-401b-890b-d75c45e9a84e)

**Comment by fysoul17** [comment] 2024-09-05 17:37
I'm encountering the same issue with the exact same node settings as @meJeppoy. The workflow was functioning correctly up until this morning on version 1.56.0. However, after updating to version 1.58.0, the error started appearing, even for workflows that were previously working, as shown in the attached screenshot.

![image](https://github.com/user-attachments/assets/3937f6f4-3d27-4743-bae1-13ac64445227)

**Comment by netroy** [comment] 2024-09-05 17:45
can either of you please share a workflow json exported from the UI? that would really help with reproducing and fixing this.

**Comment by meJeppoy** [comment] 2024-09-05 18:02
[Email_Classifier.json](https://github.com/user-attachments/files/16898488/Email_Classifier.json)
Here you go.

**Comment by fysoul17** [comment] 2024-09-05 18:03
[workflow.json](https://github.com/user-attachments/files/16898544/workflow.json)
here too

**Comment by rogaha** [comment] 2024-09-09 18:39
any updates here?

**Comment by Joffcom** [comment] 2024-09-10 07:20
Hey @rogaha,

I have looked at the internal ticket and it looks like it may be fixed in 1.58.1 can you try updating?

**Comment by rogaha** [comment] 2024-09-11 06:33
sure, will do.

**Comment by rogaha** [comment] 2024-09-11 06:55
yep, it seems to be fixed in `1.58.1`. thanks, @Joffcom

**Comment by Joffcom** [comment] 2024-09-12 16:38
Hey @rogaha,

Perfect, I will get this one closed, Thanks for confirming.

**Closed by Joffcom** 2024-09-12 16:38 UTC
Labels: in linear
