### ISSUE TITLE
NocoDB node unusable since 1.7.1

### ISSUE THREAD

**Issue by enerch** [n8n-io/n8n#7242] opened 2023-09-24 20:19 UTC
**Describe the bug**
Defining Project ID got impossibel. No suggestion is made and it's not possible to type anything in the field. This worked fine some weeks ago.

- n8n Version 1.7.1

**Comment by Joffcom** [comment] 2023-09-25 08:34
Hey @enerch,

I have just given this a quick go on `1.8.0` with NocoDB `0.111.4` and it is working as expected using an API token and a User token.

![image](https://github.com/n8n-io/n8n/assets/4688521/d322b188-56e5-4833-aeb5-f066633a1057)

I am also able to type in the input field and the Table Name field is correctly picking up the options available.

![image](https://github.com/n8n-io/n8n/assets/4688521/4acb8b08-058a-48a7-aaa6-4679e9cb2ab8)

Are you able to clarify a bit more on what isn't working and which version of NocoDB you are currently using as I am not currently able to reproduce this.

**Comment by glasschan** [comment] 2023-10-06 03:27
**Same here.** The instance is deployed at `1.0` and upgraded all the way to `1.8.2` now. (docker-compose from here)

the nocodb version is `0.111.4`

![image](https://github.com/n8n-io/n8n/assets/10547691/01c3c75e-c33d-42b1-9acc-2d95d9fd480d)

👆this is from a new workflow and new node

![image](https://github.com/n8n-io/n8n/assets/10547691/8ed7aaf6-06fd-4537-9c0c-0e31566ae5f9)

👆this is from a working workflow and now is dead

![image](https://github.com/n8n-io/n8n/assets/10547691/23ee7b7a-2877-4c62-bb16-85095838d1ff)
![image](https://github.com/n8n-io/n8n/assets/10547691/d8e45eae-8f12-4056-b082-5eb67a50ed69)
![image](https://github.com/n8n-io/n8n/assets/10547691/50b41c73-6e0a-4fa9-b0ca-6cee1bc9b7ad)

I also tried the HTTP request node and import curl from the nocodb, still gives me error. which is working in nocodb and postman

**Comment by Joffcom** [comment] 2023-10-06 05:19
Hey @glasschan,

Can you set the output option for the http request node to use string for the response type instead of auto detect or json so we can see what is coming back?

I am expecting it to be html and there to be an error in there possibly around the credential.

I have just tested my NocoDB install with 1.8.2 using both authentication options and it still appears to be working so at the moment I think it could be something in the configuration stopping it from working.

**Comment by glasschan** [comment] 2023-10-06 05:37
![image](https://github.com/n8n-io/n8n/assets/10547691/407b43fe-1960-4113-b3c2-a8406a0c670b)

```
�h >�����g���@Bh;[��
E��ܫ��?Q������sϠ��%]Q���\n�,U�����R�f�8��.�C�^	�!$�t0o"�)�x�2��ݿ��IH\����K�7�D�,����� �B�J����$p�����Sӡ9�����4W���W�s��f��u���fI9CQ<��%��$��,�DY�f�"qI�-Zؼ*PoV�wg�N�PbL~�~����[���*�B������I���\nٞWҫ+�W�T�D�V����G�*ؗ� .1Q��bL���
'�M{5GG���	h�c�5�ꓫ-��ͻ0���f[l�q�n�� ��2)�&/��Qs�q�e���<��f�v9s�������v-��{�������f��9�#I�,z�,����l�a!�9V�2]00�)���5�L�}����6x"��q�(/"���G���
_�6�մ4��z�J�s�.��>��9�1�5>���C
�Lp�س��G�\�\�7�W���T��&�ʶs��J�$��X�f�G/�b>�0["Q8#u�����6�D��A C�M���5����0i6���?��K�]a�Q<q����&Q^$i*C? �?x�"m�yYd�|���v�rrQX����`t�<c&�*-�t��Y�D�N�O�e���:�L�-�å�μ�`��
���A S'�Ty��_�����M�4�oZ�`��KeQ*�d�"?H�Lw�����V!~?��j�#x4��Q�\nS+��lTH_R�L��{�?�0��Q�ղ���p1�	T24���Zmc8�	������|�@4<������y�¡��ncae8���V]��&\nI<KaI�,�ț,�d���A,{1�<�_��r2��}l�B���䴩�m�4�����.S��nN4^�w��(�H��Q�{��gGw�h/k�e`U�D K�6���$�k�`]�[�2R��w`�D�w;l����m;B�828DՅJ�=�����_@Q5�G�=��������;hvp�|�ށ"�α��:]�dѯ_�V��e|���i�ʿ>A�u,���˝��I�F{V�5e*U,�ʶma��"W�}�Le�ɫW�8��5������P0�a����t%Y�P���b�.,A��������yuC�@�2:`|�{��l/�8Du��h����e'�+e2n�����N�W���9Ɍ��G�����e)3�Q��|{p�GRVm���sޘ�$-��e��켷���X��=��v��\:>,�p%x�$�� NJd)���f9��A�~�:��XԆ�]�\�#'�۔a:�=̬��:vQw����,��}Y��*�uv���آ.(4u���?*'����.�3��+����c�reXB�r��\�~���T��i�W�}���.er�)�S��q���Lpj�g���q���b����6�p�8�����Kv���o(ro=�V���h�Pּ�d�!n�U�@:�pPH�ZU�`��`���D�H֛H"�R%!q�7����>�@\��)��G��$)�IQV����I9�����
```

it come back with these 😂

**Comment by Joffcom** [comment] 2023-10-06 07:20
Hey @glasschan,

Well that isn't right and it looks like the data has got messed up along the way, My gut feel is Cloudflare is compressing the data trying to be helpful and we don't know how to handle a compressed response.

Can you disable compression in Cloudflare for that site and see if that works and also try connecting to your NocoDB instance bypassing Cloudflare and see if that works that will tell us if the issue is linked to something Cloudflare is doing that we need to handle or if there is some issue with working with the NocoDB response that we are not able to reproduce in a quick test.

**Comment by glasschan** [comment] 2023-10-06 07:45
you are right. is cloudflare.

![image](https://github.com/n8n-io/n8n/assets/10547691/16c0e738-5f92-492e-a71b-a4368cd904b1)
and this `Accept-Encoding` Header can reproduce the same result even with cloudflare off, don't know if this help you to investigate.

**Comment by glasschan** [comment] 2023-10-06 07:47
but Cloudflare has been activated since day one without any issues, so........anyways thanks so much!!

**Comment by Joffcom** [comment] 2023-10-06 08:11
Hey @glasschan,

That is very helpful thanks, I will need to dig into what is happening here. I thought that there was nomrally a header to let a client know the content might be compressed so something could be missing there or maybe we previously had that set and removed it for some reason.

This has been a massive help though as we now know where to look 🙌🏻

**Comment by Joffcom** [comment] 2024-05-20 18:35
Just to follow up on this one, As this is not directly an issue with the node itself or n8n and it is environmental I am going to close this for now.

In the future we may think about adding options to work around cases like this.

**Closed by Joffcom** 2024-05-20 18:35 UTC
